-- =============================================================================
-- SPINDLE ERP — ECOMMERCE MODULE  (OPTIMISED v3)
-- FILE 01 : MASTER — Categories, Product Catalog, Variants, Images
-- PostgreSQL 16+
--
-- OPTIMISATIONS FROM ENTITY ANALYSIS:
--
-- ec_product_catalog:
--   • item_id → inv_items (Item entity).  Item already owns:
--       itemCode, itemName, sku, barcode, costPrice, unitPrice, weight,
--       volume, dimensions, minimumStock, maximumStock, itemType,
--       hasLotTracking, brand, model, purchaseUnit, salesUnit
--     So ec_product_catalog holds ONLY the storefront/marketing layer.
--   • REMOVED: total_sales, total_views  (computed from ec_product_analytics)
--   • REMOVED: specification (use inv_items.internalNotes or a new text field
--     added to inv_items — no duplicate)
--   • minimum_order_qty / maximum_order_qty kept as NULLABLE override:
--     NULL = "use inv_items.minimumStock"; non-null = storefront override
--   • short_description retained (marketing blurb, not inv_items.description)
--
-- ec_product_variants:
--   • item_id FK → inv_items mandatory (each variant IS a separate Item)
--   • REMOVED: sku, barcode, cost_price  (read from Item via item_id)
--   • weight/length/width/height kept as NULLABLE physical overrides for
--     shipping-rate calculations (variant pack size differs from item master)
--   • selling_price / compare_price kept (storefront pricing layer)
--
-- ec_category_attributes / ec_product_attribute_values / ec_product_tags:
--   • These are STOREFRONT CMS constructs — no ERP equivalent → keep as-is
--
-- ItemBrand / ItemModel → already on inv_items.brand / inv_items.model
--   • No ec_brands table. Storefront brand is derived from item.brand.brandName
-- =============================================================================

-- =============================================================================
-- STOREFRONT CATEGORY  (CMS/SEO tree — separate from inv_item_categories)
-- inv_item_categories = inventory classification (stock type, costing)
-- ec_categories       = customer-facing navigation / PDP hierarchy
-- Linked implicitly via ec_product_catalog → inv_items → inv_item_categories
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_categories
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- BaseEntity pattern: org + audit columns
    created_at          TIMESTAMP(6),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),
    organization_id     BIGINT NOT NULL REFERENCES org_organizations(id),

    parent_category_id  BIGINT REFERENCES ec_categories(id),

    category_code       VARCHAR(50)  NOT NULL,
    category_name       VARCHAR(200) NOT NULL,
    slug                VARCHAR(250) NOT NULL,

    short_description   VARCHAR(500),
    description         TEXT,

    image_url           VARCHAR(700),
    banner_url          VARCHAR(700),
    icon                VARCHAR(100),

    -- SEO (storefront-only, no ERP equivalent)
    meta_title          VARCHAR(255),
    meta_keywords       VARCHAR(500),
    meta_description    VARCHAR(1000),

    display_order       INTEGER  DEFAULT 0,
    level_no            INTEGER  DEFAULT 1,
    is_menu             BOOLEAN  DEFAULT TRUE,
    is_featured         BOOLEAN  DEFAULT FALSE,
    active              BOOLEAN  DEFAULT TRUE,
    deleted             BOOLEAN  DEFAULT FALSE,

    CONSTRAINT uq_ec_cat_code UNIQUE (organization_id, category_code),
    CONSTRAINT uq_ec_cat_slug UNIQUE (organization_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_ec_cat_org      ON ec_categories (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_cat_parent   ON ec_categories (parent_category_id);
CREATE INDEX IF NOT EXISTS idx_ec_cat_slug     ON ec_categories (slug);
CREATE INDEX IF NOT EXISTS idx_ec_cat_active   ON ec_categories (active);
CREATE INDEX IF NOT EXISTS idx_ec_cat_featured ON ec_categories (is_featured);

-- =============================================================================
-- CATEGORY ATTRIBUTE DEFINITION  (filterable/searchable attribute schema)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_category_attributes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at      TIMESTAMP(6),
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(100),

    category_id     BIGINT NOT NULL REFERENCES ec_categories(id) ON DELETE CASCADE,

    attribute_name  VARCHAR(150) NOT NULL,
    attribute_label VARCHAR(150),

    data_type       VARCHAR(30) NOT NULL
        CHECK (data_type IN ('TEXT','NUMBER','BOOLEAN','DATE','LIST','COLOR')),

    is_required     BOOLEAN DEFAULT FALSE,
    searchable      BOOLEAN DEFAULT TRUE,
    filterable      BOOLEAN DEFAULT TRUE,
    sortable        BOOLEAN DEFAULT FALSE,
    display_order   INTEGER DEFAULT 0,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_catattr_cat ON ec_category_attributes (category_id);

-- =============================================================================
-- PRODUCT CATALOG  (storefront/marketing layer on top of inv_items)
--
-- Relationship: ONE ec_product_catalog row per ONE inv_items row (1:1)
--
-- What this table adds over inv_items:
--   • Storefront slug / SEO meta
--   • Marketing title and rich descriptions
--   • Merchandising flags (featured, trending, new_arrival…)
--   • Publishing workflow (published, publish_date)
--   • CMS content (youtube_video, return_policy, shipping_information)
--   • Storefront category FK
--   • Order quantity overrides (NULL = use inv_items.minimumStock)
--
-- What this table does NOT duplicate from inv_items:
--   • itemCode, itemName, sku, barcode         → read via item_id
--   • costPrice, standardCost, unitPrice       → read via item_id
--   • weight, volume, dimensions               → read via item_id
--   • minimumStock, maximumStock               → use min/max_order_qty override
--   • brand, model                             → read via item_id.brand / item_id.model
--   • itemType, hasLotTracking                 → read via item_id
--   • purchaseUnit, salesUnit, operationUnit   → read via item_id
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_catalog
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at              TIMESTAMP(6),
    created_by              VARCHAR(100),
    updated_at              TIMESTAMP(6),
    updated_by              VARCHAR(100),
    organization_id         BIGINT NOT NULL REFERENCES org_organizations(id),

    -- ── Core ERP link ──────────────────────────────────────────────────────
    -- MANDATORY: every product MUST be a published inv_items record
    -- (FINISHED_GOOD or SERVICE type recommended)
    item_id                 BIGINT NOT NULL REFERENCES inv_items(id),

    -- Storefront category (separate from inv_item_categories)
    category_id             BIGINT REFERENCES ec_categories(id),

    -- ── Storefront identity ────────────────────────────────────────────────
    slug                    VARCHAR(250) NOT NULL,
    product_title           VARCHAR(300) NOT NULL,  -- marketing name, may differ from itemName

    -- ── Rich content ──────────────────────────────────────────────────────
    short_description       VARCHAR(1000),
    description             TEXT,
    -- specification not duplicated here — use inv_items.internalNotes
    -- or request addition of a 'specification TEXT' column to inv_items

    -- ── SEO (storefront-only) ─────────────────────────────────────────────
    seo_title               VARCHAR(255),
    seo_keywords            VARCHAR(500),
    seo_description         VARCHAR(1000),

    -- ── CMS content ───────────────────────────────────────────────────────
    youtube_video           VARCHAR(500),
    warranty_information    VARCHAR(500),
    return_policy           TEXT,
    shipping_information    TEXT,

    -- ── Order quantity overrides ───────────────────────────────────────────
    -- NULL = inherit from inv_items.minimumStock / maximumStock
    -- Non-null = storefront-specific per-order limit (e.g. max 5 per customer)
    minimum_order_qty       NUMERIC(12,2),
    maximum_order_qty       NUMERIC(12,2),

    -- ── Merchandising flags ────────────────────────────────────────────────
    featured                BOOLEAN DEFAULT FALSE,
    best_seller             BOOLEAN DEFAULT FALSE,
    trending                BOOLEAN DEFAULT FALSE,
    new_arrival             BOOLEAN DEFAULT FALSE,
    recommended             BOOLEAN DEFAULT FALSE,

    -- ── Publishing ────────────────────────────────────────────────────────
    published               BOOLEAN DEFAULT FALSE,
    publish_date            TIMESTAMP(6),

    -- ── REMOVED: total_sales, total_views ─────────────────────────────────
    -- These are now computed from ec_product_analytics
    -- Service layer: SELECT SUM(purchases), SUM(product_views) WHERE product_id = ?
    -- No dual-write sync bug possible.

    active                  BOOLEAN DEFAULT TRUE,
    deleted                 BOOLEAN DEFAULT FALSE,

    CONSTRAINT uq_ec_prod_slug UNIQUE (organization_id, slug),
    CONSTRAINT uq_ec_prod_item UNIQUE (organization_id, item_id)  -- enforces 1:1
);

CREATE INDEX IF NOT EXISTS idx_ec_prod_org      ON ec_product_catalog (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_prod_item     ON ec_product_catalog (item_id);
CREATE INDEX IF NOT EXISTS idx_ec_prod_cat      ON ec_product_catalog (category_id);
CREATE INDEX IF NOT EXISTS idx_ec_prod_slug     ON ec_product_catalog (slug);
CREATE INDEX IF NOT EXISTS idx_ec_prod_featured ON ec_product_catalog (featured);
CREATE INDEX IF NOT EXISTS idx_ec_prod_best     ON ec_product_catalog (best_seller);
CREATE INDEX IF NOT EXISTS idx_ec_prod_trending ON ec_product_catalog (trending);
CREATE INDEX IF NOT EXISTS idx_ec_prod_pub      ON ec_product_catalog (published, publish_date);
CREATE INDEX IF NOT EXISTS idx_ec_prod_active   ON ec_product_catalog (active, deleted);

-- =============================================================================
-- PRODUCT IMAGE
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_images
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at      TIMESTAMP(6),
    created_by      VARCHAR(100),

    product_id      BIGINT NOT NULL REFERENCES ec_product_catalog(id) ON DELETE CASCADE,

    image_url       VARCHAR(700) NOT NULL,
    thumbnail_url   VARCHAR(700),
    alt_text        VARCHAR(255),
    display_order   INTEGER DEFAULT 0,
    is_primary      BOOLEAN DEFAULT FALSE,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_prodimg_prod ON ec_product_images (product_id);

-- =============================================================================
-- PRODUCT VARIANT
--
-- MANDATORY: item_id → inv_items (each variant IS a distinct inv_items record)
-- This is the key design decision: variants are not lightweight rows — they map
-- to actual inventory items with their own stock, lot tracking, and costing.
--
-- REMOVED (sourced from inv_items via item_id):
--   • sku     → inv_items.sku
--   • barcode → inv_items.barcode
--   • cost_price → inv_items.costPrice (service reads this for COGS)
--
-- KEPT as NULLABLE physical overrides (variant pack may differ from item master):
--   • weight, length, width, height — used by shipping-rate calculator
--     NULL = use inv_items.weight / inv_items.volume / inv_items.dimensions
--
-- KEPT as storefront pricing:
--   • selling_price (customer-facing — may differ from inv_items.unitPrice)
--   • compare_price (strikethrough price for discounts)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_variants
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at      TIMESTAMP(6),
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(100),

    product_id      BIGINT NOT NULL REFERENCES ec_product_catalog(id) ON DELETE CASCADE,

    -- MANDATORY: each variant maps to a distinct inv_items row for stock mgmt
    item_id         BIGINT NOT NULL REFERENCES inv_items(id),

    variant_code    VARCHAR(50),
    variant_name    VARCHAR(200),

    -- Visual differentiators (storefront-only)
    color           VARCHAR(100),
    size_name       VARCHAR(100),

    -- NULLABLE physical overrides (NULL = use item master values)
    -- Used only by shipping rate calculator; inventory uses item master weight
    weight_override NUMERIC(12,3),
    length_override NUMERIC(12,3),
    width_override  NUMERIC(12,3),
    height_override NUMERIC(12,3),

    -- Storefront pricing (may differ from inv_items.unitPrice)
    selling_price   NUMERIC(18,2),
    compare_price   NUMERIC(18,2),
    -- cost_price REMOVED — always read from inv_items.costPrice via item_id

    active          BOOLEAN DEFAULT TRUE,
    deleted         BOOLEAN DEFAULT FALSE,

    CONSTRAINT uq_ec_variant_item UNIQUE (product_id, item_id)  -- one item per variant slot
);

CREATE INDEX IF NOT EXISTS idx_ec_variant_prod ON ec_product_variants (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_variant_item ON ec_product_variants (item_id);
CREATE INDEX IF NOT EXISTS idx_ec_variant_active ON ec_product_variants (active);

-- =============================================================================
-- PRODUCT ATTRIBUTE VALUES  (instance values for a specific product/variant)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_attribute_values
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id            BIGINT NOT NULL REFERENCES ec_product_catalog(id) ON DELETE CASCADE,
    category_attribute_id BIGINT NOT NULL REFERENCES ec_category_attributes(id) ON DELETE CASCADE,
    attribute_value       TEXT,

    CONSTRAINT uq_ec_prodattr UNIQUE (product_id, category_attribute_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_prodattr_prod ON ec_product_attribute_values (product_id);

-- =============================================================================
-- PRODUCT TAGS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_tags
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    tag_name        VARCHAR(100) NOT NULL,
    slug            VARCHAR(120) NOT NULL,
    CONSTRAINT uq_ec_tag UNIQUE (organization_id, slug)
);

CREATE TABLE IF NOT EXISTS ec_product_tag_map
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id) ON DELETE CASCADE,
    tag_id     BIGINT NOT NULL REFERENCES ec_product_tags(id)    ON DELETE CASCADE,
    CONSTRAINT uq_ec_prod_tag UNIQUE (product_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_prodtag_prod ON ec_product_tag_map (product_id);
