-- =============================================================================
-- SPINDLE ERP — ECOMMERCE MODULE  (OPTIMISED v3)
-- FILE 02 : CUSTOMER MODULE
-- PostgreSQL 16+
--
-- OPTIMISATIONS FROM ENTITY ANALYSIS:
--
-- ChartOfAccountSub STI (from uploaded files):
--   • CustomerAccount (@DiscriminatorValue("CUSTOMER")) extends ChartOfAccountSub
--   • CustomerAccount already has: customerCode, creditLimit, paymentTerms,
--     creditDays, salesRepresentative, customerGroup, loyaltyPoints,
--     contactPerson, contactPhone, contactEmail, address, city, country etc.
--   • For B2B customers (existing ERP trade customers), ChartOfAccountSub IS
--     the customer — no need for ec_customers row.
--   • ec_customers is ADDITIVE: for new B2C portal registrations ONLY.
--     On conversion to B2B, service creates a CustomerAccount and sets
--     erp_sub_account_id to link them.
--
-- wallet_balance REMOVED from ec_customers:
--   • Storing it here creates a dual-write sync bug with ec_customer_wallet.
--   • Service computes balance as: SELECT COALESCE(SUM(CASE WHEN
--     transaction_type='CREDIT' THEN amount ELSE -amount END),0)
--     FROM ec_customer_wallet WHERE customer_id=?
--   • Or maintain as application-level cached field only, never persisted.
--     We remove it from the table definition entirely.
-- =============================================================================

-- =============================================================================
-- EC CUSTOMER  (B2C portal registrations)
--
-- Entity pattern: DOES NOT extend BaseEntity — mirrors ItemUom/InventoryLot
-- pattern because customers register themselves (no ERP session context).
-- organizationId stored as plain Long, set server-side from SecurityHelper.
--
-- erp_sub_account_id: nullable FK to acc_chart_of_accounts_sub (CustomerAccount)
--   NULL  = portal-only customer (no ERP AR sub-ledger)
--   Set   = customer has been linked to ERP (for B2B conversion or AR posting)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customers
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),
    organization_id     BIGINT NOT NULL REFERENCES org_organizations(id),

    -- Bridge to ERP sec_users (for B2B portal SSO)
    user_id             BIGINT REFERENCES sec_users(id),

    -- Bridge to ERP AR sub-ledger (CustomerAccount discriminator)
    -- Set by EcCustomerService.linkToErp() after onboarding approval
    erp_sub_account_id  BIGINT REFERENCES acc_chart_of_accounts_sub(id),

    customer_code       VARCHAR(50)  NOT NULL,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100),
    full_name           VARCHAR(200),   -- computed/stored at save: first + last

    email               VARCHAR(200),
    phone               VARCHAR(30)  NOT NULL,
    password_hash       VARCHAR(255),

    gender              VARCHAR(20) CHECK (gender IN ('MALE','FEMALE','OTHER')),
    date_of_birth       DATE,
    profile_image       VARCHAR(500),

    -- B2B fields (populated when erp_sub_account_id is set)
    company_name        VARCHAR(200),
    tax_number          VARCHAR(100),
    national_id         VARCHAR(100),

    email_verified      BOOLEAN DEFAULT FALSE,
    phone_verified      BOOLEAN DEFAULT FALSE,

    account_status      VARCHAR(20) DEFAULT 'ACTIVE'
        CHECK (account_status IN ('ACTIVE','BLOCKED','PENDING','DELETED')),

    customer_group      VARCHAR(50),

    -- Counters (updated by service on each order — fast read for UI)
    total_orders        INTEGER DEFAULT 0,
    total_purchase      NUMERIC(18,2) DEFAULT 0,
    reward_points       INTEGER DEFAULT 0,
    -- wallet_balance REMOVED — always computed from ec_customer_wallet ledger
    -- Use: SELECT SUM(CASE WHEN transaction_type='CREDIT' THEN amount ELSE -amount END)
    --      FROM ec_customer_wallet WHERE customer_id = ?

    last_login_at       TIMESTAMP(6),
    active              BOOLEAN DEFAULT TRUE,
    deleted             BOOLEAN DEFAULT FALSE,

    CONSTRAINT uq_ec_customer_code UNIQUE (organization_id, customer_code)
);

-- Partial unique indexes (email can be null for phone-only registrations)
CREATE UNIQUE INDEX IF NOT EXISTS uq_ec_customer_email
    ON ec_customers (organization_id, email)
    WHERE email IS NOT NULL AND deleted = FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_ec_customer_phone
    ON ec_customers (organization_id, phone)
    WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_ec_cust_org    ON ec_customers (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_cust_email  ON ec_customers (email);
CREATE INDEX IF NOT EXISTS idx_ec_cust_phone  ON ec_customers (phone);
CREATE INDEX IF NOT EXISTS idx_ec_cust_status ON ec_customers (account_status);
CREATE INDEX IF NOT EXISTS idx_ec_cust_sub    ON ec_customers (erp_sub_account_id);
CREATE INDEX IF NOT EXISTS idx_ec_cust_user   ON ec_customers (user_id);

-- =============================================================================
-- CUSTOMER ADDRESS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_addresses
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),

    customer_id         BIGINT NOT NULL REFERENCES ec_customers(id) ON DELETE CASCADE,

    address_type        VARCHAR(20)
        CHECK (address_type IN ('HOME','OFFICE','BILLING','SHIPPING','OTHER')),

    contact_person      VARCHAR(200),
    contact_phone       VARCHAR(30),

    country             VARCHAR(100) DEFAULT 'Bangladesh',
    division            VARCHAR(100),
    district            VARCHAR(100),
    upazila             VARCHAR(100),
    post_code           VARCHAR(20),
    area                VARCHAR(150),
    address_line1       VARCHAR(300),
    address_line2       VARCHAR(300),
    landmark            VARCHAR(200),

    latitude            NUMERIC(12,8),
    longitude           NUMERIC(12,8),

    default_shipping    BOOLEAN DEFAULT FALSE,
    default_billing     BOOLEAN DEFAULT FALSE,
    active              BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_custaddr_cust ON ec_customer_addresses (customer_id);

-- =============================================================================
-- CUSTOMER WALLET LEDGER
--
-- This is the single source of truth for wallet balance.
-- ec_customers.wallet_balance has been REMOVED.
-- Balance query (service layer):
--   SELECT COALESCE(SUM(CASE WHEN transaction_type='CREDIT'
--                        THEN amount ELSE -amount END), 0)
--   FROM ec_customer_wallet
--   WHERE customer_id = ?
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_wallet
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),

    customer_id         BIGINT NOT NULL REFERENCES ec_customers(id) ON DELETE CASCADE,

    transaction_type    VARCHAR(20) CHECK (transaction_type IN ('CREDIT','DEBIT')),

    -- reference_type: 'ORDER' | 'REFUND' | 'TOPUP' | 'ADJUSTMENT' | 'REWARD_REDEEM'
    reference_type      VARCHAR(50),
    reference_id        BIGINT,

    narration           VARCHAR(500),

    amount              NUMERIC(18,2) NOT NULL,

    -- balance_after: running balance snapshot for fast last-known-balance lookup
    -- Populated atomically at insert time in EcWalletService
    balance_after       NUMERIC(18,2) NOT NULL,

    created_by          VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_ec_wallet_cust ON ec_customer_wallet (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_wallet_ref  ON ec_customer_wallet (reference_type, reference_id);
CREATE INDEX IF NOT EXISTS idx_ec_wallet_time ON ec_customer_wallet (created_at DESC);

-- =============================================================================
-- REWARD POINTS LEDGER
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_reward_points
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),

    customer_id         BIGINT NOT NULL REFERENCES ec_customers(id) ON DELETE CASCADE,

    reference_type      VARCHAR(50),
    reference_id        BIGINT,

    points              INTEGER NOT NULL,

    transaction_type    VARCHAR(20)
        CHECK (transaction_type IN ('EARN','REDEEM','ADJUST')),

    remarks             VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_ec_reward_cust ON ec_reward_points (customer_id);

-- =============================================================================
-- WISHLIST
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_wishlist
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) DEFAULT NOW(),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id)      ON DELETE CASCADE,
    product_id  BIGINT NOT NULL REFERENCES ec_product_catalog(id) ON DELETE CASCADE,
    CONSTRAINT uq_ec_wishlist UNIQUE (customer_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_wishlist_cust ON ec_wishlist (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_wishlist_prod ON ec_wishlist (product_id);

-- =============================================================================
-- RECENTLY VIEWED
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_recently_viewed
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES ec_customers(id)      ON DELETE CASCADE,
    product_id  BIGINT NOT NULL REFERENCES ec_product_catalog(id) ON DELETE CASCADE,
    viewed_at   TIMESTAMP(6) DEFAULT NOW(),
    ip_address  VARCHAR(50),
    device_info VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_ec_recent_cust ON ec_recently_viewed (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_recent_prod ON ec_recently_viewed (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_recent_time ON ec_recently_viewed (viewed_at DESC);

-- =============================================================================
-- CUSTOMER LOGIN HISTORY
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_login_history
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      BIGINT NOT NULL REFERENCES ec_customers(id) ON DELETE CASCADE,
    login_time       TIMESTAMP(6),
    logout_time      TIMESTAMP(6),
    ip_address       VARCHAR(50),
    browser          VARCHAR(150),
    operating_system VARCHAR(150),
    device           VARCHAR(150),
    login_status     VARCHAR(20),
    login_source     VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_ec_login_cust ON ec_customer_login_history (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_login_time ON ec_customer_login_history (login_time DESC);

-- =============================================================================
-- CUSTOMER OTP
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_otp
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES ec_customers(id) ON DELETE CASCADE,
    phone       VARCHAR(30),
    email       VARCHAR(200),
    otp_code    VARCHAR(10),
    otp_type    VARCHAR(30)
        CHECK (otp_type IN ('LOGIN','REGISTER','FORGOT_PASSWORD','VERIFY_PHONE','VERIFY_EMAIL')),
    expiry_time TIMESTAMP(6),
    verified    BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_otp_cust  ON ec_customer_otp (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_otp_phone ON ec_customer_otp (phone);
CREATE INDEX IF NOT EXISTS idx_ec_otp_email ON ec_customer_otp (email);

-- =============================================================================
-- CUSTOMER DEVICE  (push notification targets)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_devices
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT NOT NULL REFERENCES ec_customers(id) ON DELETE CASCADE,
    device_uuid  VARCHAR(200),
    device_name  VARCHAR(200),
    device_type  VARCHAR(50),
    os_name      VARCHAR(100),
    app_version  VARCHAR(50),
    push_token   TEXT,
    last_active  TIMESTAMP(6),
    active       BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_device_cust ON ec_customer_devices (customer_id);
