-- =============================================================================
-- SPINDLE ERP — ECOMMERCE MODULE  (OPTIMISED v3)
-- FILE 03 : SHOPPING CART, COUPON & CAMPAIGN
-- PostgreSQL 16+
-- (No structural changes vs v2 — this file was already clean)
-- Retained: DEFERRABLE FK fixes on coupon_usage and abandoned_cart
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_cart
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) DEFAULT NOW(),
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(100),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id     BIGINT REFERENCES ec_customers(id),
    session_id      VARCHAR(150),
    cart_status     VARCHAR(20) DEFAULT 'ACTIVE'
        CHECK (cart_status IN ('ACTIVE','ORDERED','ABANDONED','EXPIRED')),
    total_items     INTEGER       DEFAULT 0,
    subtotal        NUMERIC(18,2) DEFAULT 0,
    discount_amount NUMERIC(18,2) DEFAULT 0,
    coupon_discount NUMERIC(18,2) DEFAULT 0,
    shipping_charge NUMERIC(18,2) DEFAULT 0,
    tax_amount      NUMERIC(18,2) DEFAULT 0,
    grand_total     NUMERIC(18,2) DEFAULT 0,
    expires_at      TIMESTAMP(6),
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_cart_cust    ON ec_cart (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_cart_session ON ec_cart (session_id);
CREATE INDEX IF NOT EXISTS idx_ec_cart_status  ON ec_cart (cart_status);
CREATE INDEX IF NOT EXISTS idx_ec_cart_org     ON ec_cart (organization_id);

-- =============================================================================
-- CART ITEMS
-- unit_price: snapshot at time of add-to-cart
-- (actual inv_items.unitPrice or ec_product_variants.selling_price — whichever applies)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_cart_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) DEFAULT NOW(),
    cart_id         BIGINT NOT NULL REFERENCES ec_cart(id) ON DELETE CASCADE,
    product_id      BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    variant_id      BIGINT REFERENCES ec_product_variants(id),
    quantity        NUMERIC(12,3) NOT NULL,
    unit_price      NUMERIC(18,2) NOT NULL,   -- snapshot
    discount_amount NUMERIC(18,2) DEFAULT 0,
    tax_amount      NUMERIC(18,2) DEFAULT 0,
    line_total      NUMERIC(18,2) NOT NULL,
    remarks         VARCHAR(500),
    CONSTRAINT uq_ec_cart_product UNIQUE (cart_id, product_id, variant_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_cartitem_cart ON ec_cart_items (cart_id);
CREATE INDEX IF NOT EXISTS idx_ec_cartitem_prod ON ec_cart_items (product_id);

-- =============================================================================
-- SAVE FOR LATER
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_saved_for_later
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) DEFAULT NOW(),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id) ON DELETE CASCADE,
    product_id  BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    variant_id  BIGINT REFERENCES ec_product_variants(id),
    quantity    NUMERIC(12,3) DEFAULT 1,
    CONSTRAINT uq_ec_saved UNIQUE (customer_id, product_id, variant_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_saved_cust ON ec_saved_for_later (customer_id);

-- =============================================================================
-- COUPON
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_coupon
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP(6),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),
    organization_id     BIGINT NOT NULL REFERENCES org_organizations(id),
    coupon_code         VARCHAR(50)  NOT NULL,
    coupon_name         VARCHAR(200),
    description         TEXT,
    discount_type       VARCHAR(20) CHECK (discount_type IN ('PERCENTAGE','FIXED')),
    discount_value      NUMERIC(18,2),
    minimum_order       NUMERIC(18,2),
    maximum_discount    NUMERIC(18,2),
    usage_limit         INTEGER,
    usage_per_customer  INTEGER DEFAULT 1,
    valid_from          TIMESTAMP(6),
    valid_to            TIMESTAMP(6),
    active              BOOLEAN DEFAULT TRUE,
    CONSTRAINT uq_ec_coupon UNIQUE (organization_id, coupon_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_coupon_code ON ec_coupon (coupon_code);
CREATE INDEX IF NOT EXISTS idx_ec_coupon_org  ON ec_coupon (organization_id);

-- =============================================================================
-- COUPON USAGE
-- DEFERRABLE FK: order may not yet be committed when coupon is applied
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_coupon_usage
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id       BIGINT NOT NULL REFERENCES ec_coupon(id) ON DELETE CASCADE,
    customer_id     BIGINT REFERENCES ec_customers(id),
    order_id        BIGINT REFERENCES ec_orders(id) DEFERRABLE INITIALLY DEFERRED,
    discount_amount NUMERIC(18,2),
    used_at         TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_couponuse_coupon ON ec_coupon_usage (coupon_id);
CREATE INDEX IF NOT EXISTS idx_ec_couponuse_cust   ON ec_coupon_usage (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_couponuse_order  ON ec_coupon_usage (order_id);

-- =============================================================================
-- PROMOTION CAMPAIGN
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_campaigns
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(100),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    campaign_code   VARCHAR(50),
    campaign_name   VARCHAR(200),
    campaign_type   VARCHAR(30)
        CHECK (campaign_type IN
            ('FLASH_SALE','DISCOUNT','BUY_X_GET_Y','FREE_SHIPPING','SEASONAL','CLEARANCE')),
    banner_image    VARCHAR(700),
    description     TEXT,
    start_date      TIMESTAMP(6),
    end_date        TIMESTAMP(6),
    priority        INTEGER DEFAULT 0,
    active          BOOLEAN DEFAULT TRUE,
    CONSTRAINT uq_ec_campaign UNIQUE (organization_id, campaign_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_campaign_org   ON ec_campaigns (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_campaign_dates ON ec_campaigns (start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_ec_campaign_active ON ec_campaigns (active);

-- =============================================================================
-- CAMPAIGN PRODUCT MAPPING
-- variant_id references ec_product_variants.item_id → inv_items for price lookup
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_campaign_products
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id     BIGINT NOT NULL REFERENCES ec_campaigns(id) ON DELETE CASCADE,
    product_id      BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    variant_id      BIGINT REFERENCES ec_product_variants(id),
    discount_type   VARCHAR(20) CHECK (discount_type IN ('PERCENTAGE','FIXED')),
    discount_value  NUMERIC(18,2),
    special_price   NUMERIC(18,2),
    maximum_qty     NUMERIC(12,3),
    active          BOOLEAN DEFAULT TRUE,
    CONSTRAINT uq_ec_campprod UNIQUE (campaign_id, product_id, variant_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_campprod_camp ON ec_campaign_products (campaign_id);
CREATE INDEX IF NOT EXISTS idx_ec_campprod_prod ON ec_campaign_products (product_id);

-- =============================================================================
-- ABANDONED CART
-- DEFERRABLE FK on recovered_order_id
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_abandoned_cart
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id             BIGINT NOT NULL REFERENCES ec_cart(id) ON DELETE CASCADE,
    customer_id         BIGINT REFERENCES ec_customers(id),
    abandoned_at        TIMESTAMP(6),
    reminder_sent       BOOLEAN DEFAULT FALSE,
    recovered           BOOLEAN DEFAULT FALSE,
    recovered_order_id  BIGINT REFERENCES ec_orders(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_ec_abandoned_cust  ON ec_abandoned_cart (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_abandoned_order ON ec_abandoned_cart (recovered_order_id);
