-- =============================================================================
-- SPINDLE ERP — ECOMMERCE MODULE  (OPTIMISED v3)
-- FILE 04 : ORDER MANAGEMENT
-- PostgreSQL 16+
--
-- OPTIMISATIONS FROM ENTITY ANALYSIS:
--
-- ec_order_items:
--   • item_id FK → inv_items (Item): ALWAYS populated so stock deduction
--     can use Item.hasLotTracking, Item.salesUnit, Item.itemType
--   • inventory_lot_id: set only when item_id.hasLotTracking = true
--   • cost_price KEPT as snapshot (Item.costPrice at time of sale — COGS)
--   • unit_price KEPT as snapshot (price charged — may differ from Item.unitPrice)
--   • variant_id → ec_product_variants which in turn has its own item_id;
--     order_items.item_id may differ from variant.item_id (same as variant.item_id
--     in practice — service must enforce this on save)
--
-- GL bridge pattern (matches JournalEntryMaster entity exactly):
--   • journal_entry_id is Long (plain FK), not @ManyToOne — mirrors
--     JournalEntryMaster.partyId design (avoids lazy-init / circular deps)
--   • Voucher type = SALES_VOUCHER on CONFIRMED
--   • VoucherStatus starts as DRAFT, flipped to POSTED by journal service
-- =============================================================================

-- =============================================================================
-- ORDER
-- Document sequence: EcOrderService calls DocumentSequenceService
--   → nextDocumentNumber(orgId, "EC-ORDER-{orgCode}", year)
--   → format: EC-ORDER-ASG-25-000001
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_orders
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at              TIMESTAMP(6) DEFAULT NOW(),
    created_by              VARCHAR(100),
    updated_at              TIMESTAMP(6),
    updated_by              VARCHAR(100),
    organization_id         BIGINT NOT NULL REFERENCES org_organizations(id),

    customer_id             BIGINT REFERENCES ec_customers(id),
    cart_id                 BIGINT REFERENCES ec_cart(id),

    -- System-generated via DocumentSequenceService
    order_no                VARCHAR(50) NOT NULL,

    order_date              TIMESTAMP(6) DEFAULT NOW(),

    order_source            VARCHAR(30) DEFAULT 'WEB'
        CHECK (order_source IN ('WEB','ANDROID','IOS','POS','FACEBOOK','API')),

    order_status            VARCHAR(30) DEFAULT 'PENDING'
        CHECK (order_status IN
            ('PENDING','CONFIRMED','PROCESSING','PACKING','READY_TO_SHIP',
             'SHIPPED','OUT_FOR_DELIVERY','DELIVERED','COMPLETED',
             'CANCELLED','RETURNED','REFUNDED')),

    payment_status          VARCHAR(20) DEFAULT 'UNPAID'
        CHECK (payment_status IN ('UNPAID','PARTIAL','PAID','REFUNDED')),

    shipping_status         VARCHAR(20) DEFAULT 'PENDING'
        CHECK (shipping_status IN
            ('PENDING','PACKED','SHIPPED','DELIVERED','RETURNED')),

    -- Financial summary
    subtotal                NUMERIC(18,2) DEFAULT 0,
    product_discount        NUMERIC(18,2) DEFAULT 0,
    coupon_discount         NUMERIC(18,2) DEFAULT 0,
    shipping_charge         NUMERIC(18,2) DEFAULT 0,
    tax_amount              NUMERIC(18,2) DEFAULT 0,
    grand_total             NUMERIC(18,2) NOT NULL,
    paid_amount             NUMERIC(18,2) DEFAULT 0,
    due_amount              NUMERIC(18,2) DEFAULT 0,

    -- Always BDT (Bangladesh context); exchange_rate for future multi-currency
    currency_code           VARCHAR(10)   DEFAULT 'BDT',
    exchange_rate           NUMERIC(18,6) DEFAULT 1,

    customer_note           TEXT,
    admin_note              TEXT,
    expected_delivery_date  DATE,
    completed_at            TIMESTAMP(6),
    cancelled_at            TIMESTAMP(6),

    -- ── GL BRIDGE ────────────────────────────────────────────────────────────
    -- JournalEntryMaster.id — SALES_VOUCHER created on CONFIRMED transition
    -- Stored as plain Long (matches JournalEntryMaster.partyId pattern)
    -- DR  AR / ec_customers.erp_sub_account_id (CustomerAccount sub-ledger)
    -- CR  Sales Revenue account  (ec_gl_account_defaults.sales_revenue_account_id)
    -- CR  VAT Payable             (ec_gl_account_defaults.vat_payable_account_id)
    journal_entry_id        BIGINT REFERENCES acc_journal_entry_master(id),

    active                  BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_order_no UNIQUE (organization_id, order_no)
);

CREATE INDEX IF NOT EXISTS idx_ec_order_cust    ON ec_orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_order_status  ON ec_orders (order_status);
CREATE INDEX IF NOT EXISTS idx_ec_order_payment ON ec_orders (payment_status);
CREATE INDEX IF NOT EXISTS idx_ec_order_ship    ON ec_orders (shipping_status);
CREATE INDEX IF NOT EXISTS idx_ec_order_date    ON ec_orders (order_date DESC);
CREATE INDEX IF NOT EXISTS idx_ec_order_org     ON ec_orders (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_order_gl      ON ec_orders (journal_entry_id);

-- =============================================================================
-- ORDER ITEM
--
-- item_id: ALWAYS set — used for:
--   1. Stock deduction: global_inventory_transactions (SALES_ISSUE)
--   2. COGS calculation: inv_items.costPrice or inv_items.standardCost
--   3. Lot tracking check: inv_items.hasLotTracking → set inventory_lot_id
--   4. UoM: inv_items.salesUnit for quantity unit
--
-- cost_price: point-in-time snapshot of inv_items.costPrice at sale time
-- unit_price: point-in-time snapshot of what customer was charged
-- Both are kept for: returns, COGS reporting, margin analysis
--
-- inventory_lot_id: set when inv_items.hasLotTracking = true
--   Links to global_inv_lots for lot-tracked finished goods
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_order_items
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id            BIGINT NOT NULL REFERENCES ec_orders(id) ON DELETE CASCADE,
    product_id          BIGINT NOT NULL REFERENCES ec_product_catalog(id),

    -- NULL when product has no variants; set when variant_id is populated
    variant_id          BIGINT REFERENCES ec_product_variants(id),

    -- MANDATORY: direct link to ERP item master
    -- Service: if variant_id != null, item_id must = ec_product_variants.item_id
    item_id             BIGINT NOT NULL REFERENCES inv_items(id),

    -- Dispatch warehouse (set on READY_TO_SHIP / SHIPPED)
    warehouse_id        BIGINT REFERENCES org_warehouses(id),

    -- Lot reference for lot-tracked items (set only when item.hasLotTracking = true)
    inventory_lot_id    BIGINT REFERENCES global_inv_lots(id),

    quantity            NUMERIC(12,3) NOT NULL,

    -- Price snapshots — ALWAYS store; never re-derive from item master
    unit_price          NUMERIC(18,2) NOT NULL,   -- what customer paid
    cost_price          NUMERIC(18,2),             -- COGS at time of sale (Item.costPrice)
    discount_amount     NUMERIC(18,2) DEFAULT 0,
    tax_amount          NUMERIC(18,2) DEFAULT 0,
    line_total          NUMERIC(18,2) NOT NULL,

    -- Derived at order close (unit_price - cost_price) * quantity
    profit_amount       NUMERIC(18,2),

    remarks             VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_ec_orderitem_order ON ec_order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_ec_orderitem_prod  ON ec_order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_orderitem_item  ON ec_order_items (item_id);
CREATE INDEX IF NOT EXISTS idx_ec_orderitem_lot   ON ec_order_items (inventory_lot_id);
CREATE INDEX IF NOT EXISTS idx_ec_orderitem_wh    ON ec_order_items (warehouse_id);

-- =============================================================================
-- ORDER STATUS HISTORY
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_order_status_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL REFERENCES ec_orders(id) ON DELETE CASCADE,
    status      VARCHAR(30) NOT NULL,
    remarks     TEXT,
    changed_by  VARCHAR(100),
    changed_at  TIMESTAMP(6) DEFAULT NOW(),
    ip_address  VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_ec_orderhist_order ON ec_order_status_history (order_id);
CREATE INDEX IF NOT EXISTS idx_ec_orderhist_time  ON ec_order_status_history (changed_at DESC);

-- =============================================================================
-- ORDER ADDRESSES  (point-in-time snapshot — NEVER reference ec_customer_addresses)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_order_addresses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES ec_orders(id) ON DELETE CASCADE,
    address_type    VARCHAR(20) CHECK (address_type IN ('BILLING','SHIPPING')),
    full_name       VARCHAR(200),
    phone           VARCHAR(30),
    email           VARCHAR(200),
    country         VARCHAR(100),
    division        VARCHAR(100),
    district        VARCHAR(100),
    upazila         VARCHAR(100),
    postcode        VARCHAR(20),
    address_line1   VARCHAR(300),
    address_line2   VARCHAR(300),
    landmark        VARCHAR(200)
);

CREATE INDEX IF NOT EXISTS idx_ec_orderaddr_order ON ec_order_addresses (order_id);

-- =============================================================================
-- ORDER NOTES
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_order_notes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL REFERENCES ec_orders(id) ON DELETE CASCADE,
    note_type   VARCHAR(20) CHECK (note_type IN ('CUSTOMER','ADMIN','SYSTEM')),
    note        TEXT,
    created_by  VARCHAR(100),
    created_at  TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_ordernote_order ON ec_order_notes (order_id);

-- =============================================================================
-- RETURN REQUEST
-- GL bridge: CREDIT_NOTE on APPROVED (mirrors global_business_documents CREDIT_NOTE)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_returns
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id  BIGINT NOT NULL REFERENCES org_organizations(id),
    order_id         BIGINT NOT NULL REFERENCES ec_orders(id),
    customer_id      BIGINT REFERENCES ec_customers(id),
    return_no        VARCHAR(50) NOT NULL,
    return_date      TIMESTAMP(6) DEFAULT NOW(),
    return_reason    TEXT,
    return_status    VARCHAR(30) DEFAULT 'REQUESTED'
        CHECK (return_status IN
            ('REQUESTED','APPROVED','REJECTED','RECEIVED','REFUNDED','COMPLETED')),
    refund_amount    NUMERIC(18,2),
    remarks          TEXT,
    -- GL BRIDGE: CREDIT_NOTE voucher (JournalEntryMaster)
    journal_entry_id BIGINT REFERENCES acc_journal_entry_master(id),
    CONSTRAINT uq_ec_return_no UNIQUE (organization_id, return_no)
);

CREATE INDEX IF NOT EXISTS idx_ec_return_order  ON ec_returns (order_id);
CREATE INDEX IF NOT EXISTS idx_ec_return_status ON ec_returns (return_status);
CREATE INDEX IF NOT EXISTS idx_ec_return_gl     ON ec_returns (journal_entry_id);

-- =============================================================================
-- RETURN ITEM
-- order_item_id → ec_order_items → item_id → inv_items for stock-back movement
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_return_items
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id        BIGINT NOT NULL REFERENCES ec_returns(id) ON DELETE CASCADE,
    order_item_id    BIGINT NOT NULL REFERENCES ec_order_items(id),
    quantity         NUMERIC(12,3),
    reason           VARCHAR(500),
    condition_status VARCHAR(30)
        CHECK (condition_status IN ('GOOD','DAMAGED','USED','DEFECTIVE')),
    approved_qty     NUMERIC(12,3)
);

CREATE INDEX IF NOT EXISTS idx_ec_returnitem_ret ON ec_return_items (return_id);

-- =============================================================================
-- REFUND
-- GL bridge: PAYMENT_VOUCHER on disbursement
-- refund_method maps to acc_chart_of_accounts_sub (BankAccount or CashAccount)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_refunds
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id               BIGINT NOT NULL REFERENCES ec_returns(id),
    organization_id         BIGINT NOT NULL REFERENCES org_organizations(id),
    refund_no               VARCHAR(50),
    refund_date             TIMESTAMP(6) DEFAULT NOW(),
    refund_method           VARCHAR(30)
        CHECK (refund_method IN ('BKASH','NAGAD','ROCKET','CARD','BANK','WALLET','CASH')),
    refund_amount           NUMERIC(18,2),
    transaction_reference   VARCHAR(150),
    remarks                 TEXT,
    -- GL BRIDGE: PAYMENT_VOUCHER voucher
    journal_entry_id        BIGINT REFERENCES acc_journal_entry_master(id)
);

CREATE INDEX IF NOT EXISTS idx_ec_refund_return ON ec_refunds (return_id);
CREATE INDEX IF NOT EXISTS idx_ec_refund_gl     ON ec_refunds (journal_entry_id);
