-- =============================================================================
-- SPINDLE ERP — ECOMMERCE MODULE  (OPTIMISED v3)
-- FILE 05 : PAYMENT MODULE
-- PostgreSQL 16+
--
-- OPTIMISATIONS FROM ENTITY ANALYSIS:
--
-- ChartOfAccountSub STI (uploaded entities):
--   BankAccount  (@DiscriminatorValue("BANK"))  has: accountNumber, bankName,
--     accountTitle, branchName, swiftCode, routingNumber, interestRate,
--     overdraftLimit, bankAccountCode, bankAccountType
--   CashAccount  (@DiscriminatorValue("CASH"))  has: cashAccountCode,
--     cashAccountType, location, custodian, maximumLimit, minimumLimit
--
--   THEREFORE: ec_payments.bank_name and ec_payments.account_number are
--   REDUNDANT when receiving_sub_account_id is set.
--   Both columns REMOVED from ec_payments.
--   Service reads: subRepo.findById(receiving_sub_account_id) → cast to BankAccount
--   → bankName, accountNumber, bankAccountCode etc.
--
-- ec_payments.journal_entry_id → JournalEntryMaster
--   Voucher type = RECEIPT_VOUCHER
--   VoucherStatus: DRAFT → POSTED (by EcPaymentJournalService)
--   GL entry:
--     DR  BankAccount / CashAccount sub-ledger (receiving_sub_account_id)
--     CR  AccountsReceivable control account   (ec_gl_account_defaults.accounts_receivable_id)
--     OR
--     CR  ec_customers.erp_sub_account_id      (if linked to CustomerAccount)
-- =============================================================================

-- =============================================================================
-- PAYMENT
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_payments
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at              TIMESTAMP(6) DEFAULT NOW(),
    created_by              VARCHAR(100),
    updated_at              TIMESTAMP(6),
    updated_by              VARCHAR(100),
    organization_id         BIGINT NOT NULL REFERENCES org_organizations(id),

    order_id                BIGINT NOT NULL REFERENCES ec_orders(id),

    -- System-generated payment number
    payment_no              VARCHAR(50) NOT NULL,

    payment_method          VARCHAR(30)
        CHECK (payment_method IN
            ('BKASH','NAGAD','ROCKET','SSLCOMMERZ','STRIPE',
             'PAYPAL','BANK','COD','WALLET','CASH')),

    payment_status          VARCHAR(20) DEFAULT 'PENDING'
        CHECK (payment_status IN
            ('PENDING','SUCCESS','FAILED','CANCELLED','REFUNDED','PARTIAL')),

    payment_date            TIMESTAMP(6),

    -- Gateway references (stored here — not in ChartOfAccountSub)
    transaction_reference   VARCHAR(200),
    gateway_transaction_id  VARCHAR(200),

    -- REMOVED: bank_name       → read from receiving_sub_account_id (BankAccount.bankName)
    -- REMOVED: account_number  → read from receiving_sub_account_id (BankAccount.accountNumber)
    -- These are sourced from ChartOfAccountSub STI at service layer.

    currency                VARCHAR(10)   DEFAULT 'BDT',
    exchange_rate           NUMERIC(18,6) DEFAULT 1,

    paid_amount             NUMERIC(18,2) NOT NULL,
    gateway_fee             NUMERIC(18,2) DEFAULT 0,

    remarks                 TEXT,

    -- ── GL BRIDGE ────────────────────────────────────────────────────────────
    -- RECEIPT_VOUCHER created by EcPaymentJournalService.postPayment()
    -- on payment_status → SUCCESS
    journal_entry_id        BIGINT REFERENCES acc_journal_entry_master(id),

    -- Bank/Cash/MFS sub-account that received this payment
    -- Discriminator: BankAccount (method=BANK/CARD/SSLCOMMERZ) or
    --                CashAccount (method=COD/CASH) or
    --                MFS mapped to a BankAccount (method=BKASH/NAGAD/ROCKET)
    receiving_sub_account_id BIGINT REFERENCES acc_chart_of_accounts_sub(id),

    CONSTRAINT uq_ec_payment_no UNIQUE (organization_id, payment_no)
);

CREATE INDEX IF NOT EXISTS idx_ec_payment_order    ON ec_payments (order_id);
CREATE INDEX IF NOT EXISTS idx_ec_payment_status   ON ec_payments (payment_status);
CREATE INDEX IF NOT EXISTS idx_ec_payment_method   ON ec_payments (payment_method);
CREATE INDEX IF NOT EXISTS idx_ec_payment_gl       ON ec_payments (journal_entry_id);
CREATE INDEX IF NOT EXISTS idx_ec_payment_sub      ON ec_payments (receiving_sub_account_id);
CREATE INDEX IF NOT EXISTS idx_ec_payment_org      ON ec_payments (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_payment_date     ON ec_payments (payment_date DESC);

-- =============================================================================
-- PAYMENT GATEWAY TRANSACTION LOG
-- Raw request/response payloads — immutable audit record
-- JSONB aligns with ec_shipping_api_logs pattern
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_payment_transactions
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payment_id          BIGINT NOT NULL REFERENCES ec_payments(id) ON DELETE CASCADE,

    transaction_type    VARCHAR(20)
        CHECK (transaction_type IN ('AUTHORIZE','CAPTURE','REFUND','VOID')),

    gateway_name        VARCHAR(50),
    request_payload     JSONB,
    response_payload    JSONB,
    gateway_status      VARCHAR(50),
    gateway_reference   VARCHAR(200),
    transaction_time    TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_pmttx_payment ON ec_payment_transactions (payment_id);
CREATE INDEX IF NOT EXISTS idx_ec_pmttx_time    ON ec_payment_transactions (transaction_time DESC);
