-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 06 : SHIPPING & DELIVERY
-- PostgreSQL 16+   |   schema prefix: ec_
--
-- NOTE: The uploaded file 06 (06_ecommerce_shipping.sql) was a duplicate of
--       file 05 (payment+shipping combined). This file contains ONLY shipping.
--
-- ERP INTEGRATION:
--   • ec_shipping.warehouse_id → org_warehouses (existing ERP warehouse)
--   • Stock deduction for SALES_ISSUE movement triggered by EcShippingService
--     when shipping_status → SHIPPED (mirrors global_inventory_transactions)
-- =============================================================================

-- =============================================================================
-- SHIPPING METHOD MASTER  (courier / delivery method configuration)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_shipping_methods
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    method_code         VARCHAR(30),
    method_name         VARCHAR(100),
    courier_name        VARCHAR(100),

    estimated_days      INTEGER,
    base_charge         NUMERIC(18,2),
    charge_per_kg       NUMERIC(18,2),

    cash_on_delivery    BOOLEAN DEFAULT FALSE,
    api_enabled         BOOLEAN DEFAULT FALSE,
    active              BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_ship_method UNIQUE (organization_id, method_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_shipmethod_org ON ec_shipping_methods (organization_id);

-- =============================================================================
-- SHIPPING ZONE  (zone-based pricing: division/district level)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_shipping_zones
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id         BIGINT NOT NULL
        REFERENCES org_organizations(id),

    zone_code               VARCHAR(30),
    zone_name               VARCHAR(150),

    country                 VARCHAR(100) DEFAULT 'Bangladesh',
    division                VARCHAR(100),
    district                VARCHAR(100),

    shipping_charge         NUMERIC(18,2),
    minimum_order_amount    NUMERIC(18,2),
    free_shipping           BOOLEAN DEFAULT FALSE,
    active                  BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_ship_zone UNIQUE (organization_id, zone_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_shipzone_org ON ec_shipping_zones (organization_id);

-- =============================================================================
-- SHIPMENT  (one shipment per order; split-shipment creates multiple rows)
-- warehouse_id maps to the ERP dispatch warehouse
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_shipping
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    order_id            BIGINT NOT NULL
        REFERENCES ec_orders(id),

    shipping_method_id  BIGINT
        REFERENCES ec_shipping_methods(id),

    -- ERP warehouse used for SALES_ISSUE stock deduction
    warehouse_id        BIGINT
        REFERENCES org_warehouses(id),

    shipment_no         VARCHAR(50),
    courier_name        VARCHAR(100),
    tracking_number     VARCHAR(150),

    shipping_status     VARCHAR(20) DEFAULT 'PENDING'
        CHECK (shipping_status IN
            ('PENDING','PICKED','PACKED','SHIPPED','IN_TRANSIT',
             'OUT_FOR_DELIVERY','DELIVERED','FAILED','RETURNED','CANCELLED')),

    shipped_date        TIMESTAMP(6),
    expected_delivery   DATE,
    delivered_date      TIMESTAMP(6),

    shipping_charge     NUMERIC(18,2),
    package_weight      NUMERIC(12,3),
    package_length      NUMERIC(12,3),
    package_width       NUMERIC(12,3),
    package_height      NUMERIC(12,3),

    remarks             TEXT
);

CREATE INDEX IF NOT EXISTS idx_ec_shipping_order  ON ec_shipping (order_id);
CREATE INDEX IF NOT EXISTS idx_ec_shipping_status ON ec_shipping (shipping_status);
CREATE INDEX IF NOT EXISTS idx_ec_shipping_wh     ON ec_shipping (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_ec_shipping_org    ON ec_shipping (organization_id);

-- =============================================================================
-- SHIPMENT TRACKING EVENTS  (real-time courier tracking log)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_shipping_tracking
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shipping_id         BIGINT NOT NULL
        REFERENCES ec_shipping(id) ON DELETE CASCADE,

    tracking_status     VARCHAR(50),
    tracking_location   VARCHAR(200),
    event_time          TIMESTAMP(6),
    remarks             TEXT
);

CREATE INDEX IF NOT EXISTS idx_ec_tracking_ship ON ec_shipping_tracking (shipping_id);
CREATE INDEX IF NOT EXISTS idx_ec_tracking_time ON ec_shipping_tracking (event_time DESC);

-- =============================================================================
-- DELIVERY SLOT  (time-slot based delivery configuration)
-- FIX: added organization_id (was missing in original)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_delivery_slots
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    slot_name       VARCHAR(100),
    start_time      TIME,
    end_time        TIME,
    maximum_orders  INTEGER,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_slot_org ON ec_delivery_slots (organization_id);

-- =============================================================================
-- ORDER DELIVERY SLOT BOOKING
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_order_delivery_slots
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id         BIGINT NOT NULL
        REFERENCES ec_orders(id) ON DELETE CASCADE,

    delivery_slot_id BIGINT NOT NULL
        REFERENCES ec_delivery_slots(id),

    delivery_date    DATE NOT NULL,
    confirmed        BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_ec_orderslot_order ON ec_order_delivery_slots (order_id);
CREATE INDEX IF NOT EXISTS idx_ec_orderslot_date  ON ec_order_delivery_slots (delivery_date);

-- =============================================================================
-- SHIPMENT PACKAGE  (multi-package per shipment)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_shipment_packages
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shipping_id BIGINT NOT NULL
        REFERENCES ec_shipping(id) ON DELETE CASCADE,

    package_no  VARCHAR(50),
    weight      NUMERIC(12,3),
    length      NUMERIC(12,3),
    width       NUMERIC(12,3),
    height      NUMERIC(12,3),
    item_count  INTEGER,
    remarks     TEXT
);

CREATE INDEX IF NOT EXISTS idx_ec_package_ship ON ec_shipment_packages (shipping_id);

-- =============================================================================
-- SHIPPING API LOG  (courier API request/response audit)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_shipping_api_logs
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    shipping_id       BIGINT
        REFERENCES ec_shipping(id),

    api_name          VARCHAR(100),
    request_payload   JSONB,
    response_payload  JSONB,
    response_code     VARCHAR(50),
    success           BOOLEAN,
    created_at        TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_shipapi_ship ON ec_shipping_api_logs (shipping_id);
CREATE INDEX IF NOT EXISTS idx_ec_shipapi_time ON ec_shipping_api_logs (created_at DESC);
