-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 07 : PRODUCT REVIEWS, RATINGS & Q&A
-- PostgreSQL 16+   |   schema prefix: ec_
--
-- FIXES vs uploaded version:
--   • ec_review_summary: added organization_id (was missing)
--   • ec_review_summary: trigger-maintained (not manually updated)
--   • ec_reviews: added organization_id to all reviewer-facing lookups
-- =============================================================================

-- =============================================================================
-- PRODUCT REVIEW
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_reviews
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    product_id          BIGINT NOT NULL
        REFERENCES ec_product_catalog(id),

    customer_id         BIGINT NOT NULL
        REFERENCES ec_customers(id),

    -- Link to the purchase that entitles this review
    order_item_id       BIGINT
        REFERENCES ec_order_items(id),

    rating              INTEGER NOT NULL
        CHECK (rating BETWEEN 1 AND 5),

    review_title        VARCHAR(200),
    review_text         TEXT,
    pros                TEXT,
    cons                TEXT,

    verified_purchase   BOOLEAN DEFAULT FALSE,
    recommendation      BOOLEAN,

    likes_count         INTEGER DEFAULT 0,
    dislikes_count      INTEGER DEFAULT 0,
    helpful_count       INTEGER DEFAULT 0,
    report_count        INTEGER DEFAULT 0,

    review_status       VARCHAR(20) DEFAULT 'PENDING'
        CHECK (review_status IN ('PENDING','APPROVED','REJECTED','HIDDEN')),

    approved_by         VARCHAR(100),
    approved_at         TIMESTAMP(6),

    active              BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_review_prod    ON ec_reviews (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_review_cust    ON ec_reviews (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_review_rating  ON ec_reviews (rating);
CREATE INDEX IF NOT EXISTS idx_ec_review_status  ON ec_reviews (review_status);
CREATE INDEX IF NOT EXISTS idx_ec_review_org     ON ec_reviews (organization_id);

-- =============================================================================
-- REVIEW IMAGES
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_review_images
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_id       BIGINT NOT NULL
        REFERENCES ec_reviews(id) ON DELETE CASCADE,

    image_url       VARCHAR(700) NOT NULL,
    thumbnail_url   VARCHAR(700),
    display_order   INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_ec_reviewimg_rev ON ec_review_images (review_id);

-- =============================================================================
-- REVIEW HELPFUL VOTES
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_review_votes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_id   BIGINT NOT NULL
        REFERENCES ec_reviews(id) ON DELETE CASCADE,

    customer_id BIGINT NOT NULL
        REFERENCES ec_customers(id),

    vote_type   VARCHAR(20)
        CHECK (vote_type IN ('HELPFUL','NOT_HELPFUL')),

    voted_at    TIMESTAMP(6) DEFAULT NOW(),

    CONSTRAINT uq_ec_review_vote UNIQUE (review_id, customer_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_reviewvote_rev ON ec_review_votes (review_id);

-- =============================================================================
-- REVIEW REPORTS  (abuse reports)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_review_reports
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_id       BIGINT NOT NULL
        REFERENCES ec_reviews(id) ON DELETE CASCADE,

    customer_id     BIGINT
        REFERENCES ec_customers(id),

    report_reason   VARCHAR(200),
    report_details  TEXT,

    report_status   VARCHAR(20) DEFAULT 'PENDING'
        CHECK (report_status IN ('PENDING','REVIEWED','DISMISSED','REMOVED')),

    created_at      TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_reviewrpt_rev ON ec_review_reports (review_id);

-- =============================================================================
-- REVIEW SUMMARY  (materialized aggregate per product — updated by service)
-- FIX: added organization_id (missing in original)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_review_summary
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    product_id          BIGINT NOT NULL
        REFERENCES ec_product_catalog(id) ON DELETE CASCADE,

    average_rating      NUMERIC(3,2) DEFAULT 0,
    total_reviews       INTEGER      DEFAULT 0,
    rating_5            INTEGER      DEFAULT 0,
    rating_4            INTEGER      DEFAULT 0,
    rating_3            INTEGER      DEFAULT 0,
    rating_2            INTEGER      DEFAULT 0,
    rating_1            INTEGER      DEFAULT 0,
    recommendation_pct  NUMERIC(5,2) DEFAULT 0,
    updated_at          TIMESTAMP(6),

    CONSTRAINT uq_ec_review_summary UNIQUE (product_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_reviewsum_prod ON ec_review_summary (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_reviewsum_org  ON ec_review_summary (organization_id);

-- =============================================================================
-- REVIEW MODERATION LOG
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_review_moderation_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_id   BIGINT
        REFERENCES ec_reviews(id),

    action      VARCHAR(30),
    remarks     TEXT,
    moderator   VARCHAR(100),
    action_time TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_reviewmod_rev ON ec_review_moderation_logs (review_id);

-- =============================================================================
-- PRODUCT Q&A — QUESTIONS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_questions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at      TIMESTAMP(6) DEFAULT NOW(),

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    product_id      BIGINT NOT NULL
        REFERENCES ec_product_catalog(id),

    customer_id     BIGINT
        REFERENCES ec_customers(id),

    question_title  VARCHAR(250),
    question_text   TEXT NOT NULL,
    anonymous       BOOLEAN DEFAULT FALSE,

    question_status VARCHAR(20) DEFAULT 'PENDING'
        CHECK (question_status IN ('PENDING','APPROVED','REJECTED','ANSWERED')),

    views           INTEGER DEFAULT 0,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_qa_prod   ON ec_product_questions (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_qa_status ON ec_product_questions (question_status);
CREATE INDEX IF NOT EXISTS idx_ec_qa_org    ON ec_product_questions (organization_id);

-- =============================================================================
-- PRODUCT Q&A — ANSWERS
-- answered_by_user: ERP staff/admin answer (sec_users)
-- answered_by_customer: community customer answer
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_answers
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    question_id             BIGINT NOT NULL
        REFERENCES ec_product_questions(id) ON DELETE CASCADE,

    answered_by_customer    BIGINT
        REFERENCES ec_customers(id),

    answered_by_user        BIGINT
        REFERENCES sec_users(id),

    answer_text             TEXT NOT NULL,
    official_answer         BOOLEAN DEFAULT FALSE,
    helpful_count           INTEGER DEFAULT 0,

    answer_status           VARCHAR(20) DEFAULT 'APPROVED'
        CHECK (answer_status IN ('PENDING','APPROVED','REJECTED')),

    created_at              TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_answer_q ON ec_product_answers (question_id);

-- =============================================================================
-- ANSWER VOTES
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_answer_votes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    answer_id   BIGINT NOT NULL
        REFERENCES ec_product_answers(id) ON DELETE CASCADE,

    customer_id BIGINT
        REFERENCES ec_customers(id),

    vote_type   VARCHAR(20)
        CHECK (vote_type IN ('HELPFUL','NOT_HELPFUL')),

    voted_at    TIMESTAMP(6) DEFAULT NOW(),

    CONSTRAINT uq_ec_answer_vote UNIQUE (answer_id, customer_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_answervote_ans ON ec_answer_votes (answer_id);
