-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 08 : CMS & CONTENT MANAGEMENT
-- PostgreSQL 16+   |   schema prefix: ec_
--
-- FIXES vs uploaded version:
--   • ec_menus index renamed idx_ec_menu_parent (was idx_menu_parent — conflicts
--     with existing idx_menu_parent on app_menus)
--   • ec_media_library: uses sec_users for uploaded_by (existing ERP users)
-- =============================================================================

-- =============================================================================
-- BANNERS  (homepage sliders, category banners, popups)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_banners
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    banner_code         VARCHAR(50),
    banner_name         VARCHAR(200) NOT NULL,

    banner_type         VARCHAR(30)
        CHECK (banner_type IN
            ('HOME_SLIDER','HOME_TOP','HOME_MIDDLE','HOME_BOTTOM',
             'CATEGORY','PRODUCT','POPUP','SIDEBAR')),

    title               VARCHAR(250),
    sub_title           VARCHAR(500),
    description         TEXT,

    image_url           VARCHAR(700),
    mobile_image_url    VARCHAR(700),
    button_text         VARCHAR(100),
    button_url          VARCHAR(500),
    open_in_new_tab     BOOLEAN DEFAULT FALSE,

    display_order       INTEGER DEFAULT 0,
    start_date          TIMESTAMP(6),
    end_date            TIMESTAMP(6),
    active              BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_banner_org  ON ec_banners (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_banner_type ON ec_banners (banner_type);
CREATE INDEX IF NOT EXISTS idx_ec_banner_active ON ec_banners (active);

-- =============================================================================
-- HOME SECTIONS  (featured/trending/new-arrival sections on homepage)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_home_sections
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    section_code    VARCHAR(50),
    section_name    VARCHAR(200),
    section_title   VARCHAR(300),
    section_subtitle VARCHAR(500),

    section_type    VARCHAR(30)
        CHECK (section_type IN
            ('FEATURED','NEW_ARRIVAL','BEST_SELLER','TOP_RATED',
             'FLASH_SALE','TRENDING','CUSTOM')),

    display_order   INTEGER DEFAULT 0,
    max_products    INTEGER DEFAULT 12,
    active          BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_home_section UNIQUE (organization_id, section_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_homesec_org ON ec_home_sections (organization_id);

-- =============================================================================
-- HOME SECTION PRODUCTS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_home_section_products
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    section_id      BIGINT NOT NULL
        REFERENCES ec_home_sections(id) ON DELETE CASCADE,

    product_id      BIGINT NOT NULL
        REFERENCES ec_product_catalog(id),

    display_order   INTEGER DEFAULT 0,

    CONSTRAINT uq_ec_home_prod UNIQUE (section_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_homeprod_sec ON ec_home_section_products (section_id);

-- =============================================================================
-- BLOG CATEGORY
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_blog_categories
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    parent_category_id  BIGINT
        REFERENCES ec_blog_categories(id),

    category_name       VARCHAR(200),
    slug                VARCHAR(250),
    description         TEXT,
    display_order       INTEGER DEFAULT 0,
    active              BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_blog_cat UNIQUE (organization_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_ec_blogcat_parent ON ec_blog_categories (parent_category_id);
CREATE INDEX IF NOT EXISTS idx_ec_blogcat_org    ON ec_blog_categories (organization_id);

-- =============================================================================
-- BLOG TAG
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_blog_tags
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    tag_name        VARCHAR(100),
    slug            VARCHAR(150),

    CONSTRAINT uq_ec_blog_tag UNIQUE (organization_id, slug)
);

-- =============================================================================
-- BLOG POST
-- author_user_id → sec_users (ERP staff who write blog content)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_blog_posts
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    category_id         BIGINT
        REFERENCES ec_blog_categories(id),

    author_user_id      BIGINT
        REFERENCES sec_users(id),

    title               VARCHAR(300),
    slug                VARCHAR(300),
    short_description   TEXT,
    content             TEXT,
    featured_image      VARCHAR(700),

    seo_title           VARCHAR(255),
    seo_keywords        VARCHAR(500),
    seo_description     VARCHAR(1000),

    publish_date        TIMESTAMP(6),
    total_views         BIGINT DEFAULT 0,
    published           BOOLEAN DEFAULT FALSE,
    active              BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_blog_slug UNIQUE (organization_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_ec_blog_cat ON ec_blog_posts (category_id);
CREATE INDEX IF NOT EXISTS idx_ec_blog_pub ON ec_blog_posts (published);
CREATE INDEX IF NOT EXISTS idx_ec_blog_org ON ec_blog_posts (organization_id);

-- =============================================================================
-- BLOG POST TAGS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_blog_post_tags
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_post_id BIGINT NOT NULL REFERENCES ec_blog_posts(id)  ON DELETE CASCADE,
    tag_id       BIGINT NOT NULL REFERENCES ec_blog_tags(id)   ON DELETE CASCADE,
    CONSTRAINT uq_ec_blog_post_tag UNIQUE (blog_post_id, tag_id)
);

-- =============================================================================
-- BLOG COMMENTS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_blog_comments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    blog_post_id        BIGINT NOT NULL
        REFERENCES ec_blog_posts(id) ON DELETE CASCADE,

    customer_id         BIGINT
        REFERENCES ec_customers(id),

    parent_comment_id   BIGINT
        REFERENCES ec_blog_comments(id),

    commenter_name      VARCHAR(200),
    commenter_email     VARCHAR(200),
    comment_text        TEXT,
    approved            BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_blogcomment_post ON ec_blog_comments (blog_post_id);

-- =============================================================================
-- STATIC PAGES  (About, Privacy Policy, T&C etc.)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_pages
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    page_title      VARCHAR(250),
    slug            VARCHAR(250),
    page_content    TEXT,

    seo_title       VARCHAR(255),
    seo_keywords    VARCHAR(500),
    seo_description VARCHAR(1000),

    published       BOOLEAN DEFAULT TRUE,
    display_order   INTEGER DEFAULT 0,

    CONSTRAINT uq_ec_page_slug UNIQUE (organization_id, slug)
);

-- =============================================================================
-- WEBSITE NAVIGATION MENU
-- FIX: index renamed idx_ec_menu_parent (collided with idx_menu_parent on app_menus)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_menus
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    parent_menu_id  BIGINT
        REFERENCES ec_menus(id),

    menu_name       VARCHAR(200),
    menu_url        VARCHAR(500),
    menu_icon       VARCHAR(100),
    target          VARCHAR(30) DEFAULT '_self',
    display_order   INTEGER DEFAULT 0,
    active          BOOLEAN DEFAULT TRUE
);

-- FIX: renamed to avoid collision with app_menus index
CREATE INDEX IF NOT EXISTS idx_ec_menu_parent ON ec_menus (parent_menu_id);
CREATE INDEX IF NOT EXISTS idx_ec_menu_org    ON ec_menus (organization_id);

-- =============================================================================
-- MEDIA LIBRARY  (file/image asset management)
-- Uses sec_users for uploaded_by (ERP staff upload product images)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_media_library
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    uploaded_by     BIGINT
        REFERENCES sec_users(id),

    file_name       VARCHAR(300),
    original_name   VARCHAR(300),
    file_url        VARCHAR(700),
    thumbnail_url   VARCHAR(700),
    mime_type       VARCHAR(100),
    file_size       BIGINT,
    image_width     INTEGER,
    image_height    INTEGER,
    alt_text        VARCHAR(300),
    uploaded_at     TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_media_org ON ec_media_library (organization_id);
