-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 10 : SEO, ANALYTICS & AUDIT
-- PostgreSQL 16+   |   schema prefix: ec_
--
-- FIXES vs uploaded version:
--   • ec_sitemap: added organization_id (was missing)
--   • ec_visitors: organization_id index added
--   • ec_dashboard_kpis: already correct (organization_id present)
-- =============================================================================

-- =============================================================================
-- SEO METADATA  (per entity — product/category/blog/page/brand)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_seo_metadata
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    entity_type         VARCHAR(30) NOT NULL
        CHECK (entity_type IN ('PRODUCT','CATEGORY','BLOG','PAGE','BRAND')),

    entity_id           BIGINT NOT NULL,

    meta_title          VARCHAR(255),
    meta_keywords       VARCHAR(1000),
    meta_description    VARCHAR(2000),
    canonical_url       VARCHAR(500),
    robots              VARCHAR(100),

    schema_json         JSONB,   -- JSON-LD structured data

    og_title            VARCHAR(255),
    og_description      VARCHAR(1000),
    og_image            VARCHAR(700),

    twitter_title       VARCHAR(255),
    twitter_description VARCHAR(1000),
    twitter_image       VARCHAR(700),

    created_at          TIMESTAMP(6) DEFAULT NOW(),
    updated_at          TIMESTAMP(6),

    CONSTRAINT uq_ec_seo UNIQUE (organization_id, entity_type, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_seo_entity ON ec_seo_metadata (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_ec_seo_org    ON ec_seo_metadata (organization_id);

-- =============================================================================
-- URL REDIRECTS  (301/302 redirects for SEO after slug changes)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_url_redirects
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    source_url      VARCHAR(700) NOT NULL,
    destination_url VARCHAR(700) NOT NULL,

    redirect_type   INTEGER NOT NULL
        CHECK (redirect_type IN (301,302,307,308)),

    active          BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP(6) DEFAULT NOW(),

    CONSTRAINT uq_ec_redirect UNIQUE (organization_id, source_url)
);

CREATE INDEX IF NOT EXISTS idx_ec_redirect_src ON ec_url_redirects (source_url);

-- =============================================================================
-- VISITOR SESSIONS  (anonymous + authenticated visitor tracking)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_visitors
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id  BIGINT NOT NULL
        REFERENCES org_organizations(id),

    customer_id      BIGINT
        REFERENCES ec_customers(id),

    session_id       VARCHAR(200),
    ip_address       VARCHAR(50),
    browser          VARCHAR(150),
    operating_system VARCHAR(150),
    device_type      VARCHAR(50),
    country          VARCHAR(100),
    city             VARCHAR(100),
    referrer         VARCHAR(700),
    landing_page     VARCHAR(700),
    first_visit      TIMESTAMP(6),
    last_visit       TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_ec_visitor_cust ON ec_visitors (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_visitor_org  ON ec_visitors (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_visitor_sess ON ec_visitors (session_id);

-- =============================================================================
-- PAGE ANALYTICS  (daily aggregated page view counts per entity)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_page_analytics
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id  BIGINT NOT NULL
        REFERENCES org_organizations(id),

    page_type        VARCHAR(30),
    entity_id        BIGINT,
    visit_date       DATE,
    page_views       INTEGER DEFAULT 0,
    unique_visitors  INTEGER DEFAULT 0,
    average_duration INTEGER DEFAULT 0,   -- seconds
    bounce_rate      NUMERIC(5,2) DEFAULT 0,

    CONSTRAINT uq_ec_page_analytics UNIQUE (organization_id, page_type, entity_id, visit_date)
);

CREATE INDEX IF NOT EXISTS idx_ec_pageana_entity ON ec_page_analytics (page_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_ec_pageana_date   ON ec_page_analytics (visit_date DESC);
CREATE INDEX IF NOT EXISTS idx_ec_pageana_org    ON ec_page_analytics (organization_id);

-- =============================================================================
-- PRODUCT ANALYTICS  (daily conversion funnel per product)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_analytics
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id      BIGINT NOT NULL
        REFERENCES ec_product_catalog(id),

    analytics_date  DATE,
    product_views   INTEGER DEFAULT 0,
    wishlist_count  INTEGER DEFAULT 0,
    cart_additions  INTEGER DEFAULT 0,
    purchases       INTEGER DEFAULT 0,
    returns         INTEGER DEFAULT 0,
    conversion_rate NUMERIC(8,2) DEFAULT 0,
    revenue         NUMERIC(18,2) DEFAULT 0,

    CONSTRAINT uq_ec_prodana UNIQUE (product_id, analytics_date)
);

CREATE INDEX IF NOT EXISTS idx_ec_prodana_prod ON ec_product_analytics (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_prodana_date ON ec_product_analytics (analytics_date DESC);

-- =============================================================================
-- SEARCH ANALYTICS  (daily search term performance)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_search_analytics
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    keyword         VARCHAR(300),
    search_date     DATE,
    total_searches  INTEGER DEFAULT 0,
    result_count    INTEGER DEFAULT 0,
    no_result       BOOLEAN DEFAULT FALSE,

    CONSTRAINT uq_ec_searchana UNIQUE (organization_id, keyword, search_date)
);

CREATE INDEX IF NOT EXISTS idx_ec_searchana_kw  ON ec_search_analytics (keyword);
CREATE INDEX IF NOT EXISTS idx_ec_searchana_org ON ec_search_analytics (organization_id);

-- =============================================================================
-- CUSTOMER BEHAVIORAL EVENTS  (e.g. product_view, add_to_cart, checkout_start)
-- event_data JSONB: arbitrary event properties
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    customer_id BIGINT
        REFERENCES ec_customers(id),

    session_id  VARCHAR(200),
    event_name  VARCHAR(100),
    entity_type VARCHAR(50),
    entity_id   BIGINT,
    event_data  JSONB,
    created_at  TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_event_cust ON ec_customer_events (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_event_org  ON ec_customer_events (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_event_name ON ec_customer_events (event_name);
CREATE INDEX IF NOT EXISTS idx_ec_event_time ON ec_customer_events (created_at DESC);

-- =============================================================================
-- AUDIT LOG  (ecommerce admin action audit)
-- Separate from ERP's sys_audit_log — ecommerce-specific entity audit
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_audit_logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT
        REFERENCES org_organizations(id),

    -- Can be ERP user (admin) or null for automated system actions
    user_id         BIGINT
        REFERENCES sec_users(id),

    entity_name     VARCHAR(100),
    entity_id       BIGINT,

    action          VARCHAR(30)
        CHECK (action IN
            ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT','EXPORT','IMPORT')),

    old_data        JSONB,
    new_data        JSONB,
    ip_address      VARCHAR(50),
    user_agent      TEXT,
    created_at      TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_audit_entity ON ec_audit_logs (entity_name, entity_id);
CREATE INDEX IF NOT EXISTS idx_ec_audit_user   ON ec_audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_ec_audit_org    ON ec_audit_logs (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_audit_time   ON ec_audit_logs (created_at DESC);

-- =============================================================================
-- API REQUEST/RESPONSE LOG  (storefront API and integration gateway log)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_api_logs
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id     BIGINT
        REFERENCES org_organizations(id),

    api_name            VARCHAR(200),
    request_method      VARCHAR(20),
    request_url         TEXT,
    request_payload     JSONB,
    response_payload    JSONB,
    status_code         INTEGER,
    execution_time_ms   INTEGER,
    created_at          TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_apilog_org  ON ec_api_logs (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_apilog_time ON ec_api_logs (created_at DESC);

-- =============================================================================
-- SYSTEM EVENTS  (background job errors, sync failures, alerts)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_system_events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT
        REFERENCES org_organizations(id),

    event_name      VARCHAR(150),
    event_level     VARCHAR(20)
        CHECK (event_level IN ('INFO','WARNING','ERROR','CRITICAL')),

    message         TEXT,
    stack_trace     TEXT,
    created_at      TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_sysevent_org   ON ec_system_events (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_sysevent_level ON ec_system_events (event_level);
CREATE INDEX IF NOT EXISTS idx_ec_sysevent_time  ON ec_system_events (created_at DESC);

-- =============================================================================
-- DASHBOARD KPIs  (daily snapshot — pre-computed for fast dashboard loading)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_dashboard_kpis
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id         BIGINT
        REFERENCES org_organizations(id),

    kpi_date                DATE,
    total_sales             NUMERIC(18,2),
    total_orders            INTEGER,
    total_customers         INTEGER,
    new_customers           INTEGER,
    average_order_value     NUMERIC(18,2),
    conversion_rate         NUMERIC(8,2),
    abandoned_cart_rate     NUMERIC(8,2),
    return_rate             NUMERIC(8,2),
    created_at              TIMESTAMP(6) DEFAULT NOW(),

    CONSTRAINT uq_ec_kpi UNIQUE (organization_id, kpi_date)
);

CREATE INDEX IF NOT EXISTS idx_ec_kpi_org  ON ec_dashboard_kpis (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_kpi_date ON ec_dashboard_kpis (kpi_date DESC);

-- =============================================================================
-- SITEMAP ENTRIES
-- FIX: organization_id added (was missing in original)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_sitemap
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id   BIGINT NOT NULL
        REFERENCES org_organizations(id),

    entity_type       VARCHAR(30),
    entity_id         BIGINT,
    url               VARCHAR(700),
    priority          NUMERIC(3,2),
    change_frequency  VARCHAR(20),
    last_modified     TIMESTAMP(6),
    active            BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_sitemap UNIQUE (organization_id, entity_type, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_sitemap_entity ON ec_sitemap (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_ec_sitemap_org    ON ec_sitemap (organization_id);
