-- =============================================================================
-- SPINDLE ERP — ECOMMERCE MODULE  (OPTIMISED v3)
-- FILE 11 : GLOBAL SETTINGS, TAX, LOCALIZATION & ERP INTEGRATION
-- PostgreSQL 16+
--
-- OPTIMISATIONS FROM ENTITY ANALYSIS:
--
-- ec_gl_account_defaults:
--   • All account FKs reference acc_chart_of_accounts (ChartOfAccount entity)
--     via account_id (Long) — consistent with how JournalEntryLine stores
--     account references (acc_journal_entry_lines.account_id)
--   • default_bank_sub_account_id references acc_chart_of_accounts_sub
--     (ChartOfAccountSub entity, BankAccount discriminator) — same pattern
--     as JournalEntryMaster.bankAccountId (Long)
--
-- ec_document_mapping now correctly maps to DocumentType enum values
--   (matching global_business_documents.document_type CHECK constraint)
--
-- Languages: Bengali ('bn') set as default_language = TRUE
-- =============================================================================

-- =============================================================================
-- ECOMMERCE SETTINGS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_settings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    setting_group   VARCHAR(100),
    setting_key     VARCHAR(150),
    setting_value   TEXT,
    data_type       VARCHAR(30)
        CHECK (data_type IN ('STRING','NUMBER','BOOLEAN','JSON')),
    description     TEXT,
    editable        BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP(6) DEFAULT NOW(),
    updated_at      TIMESTAMP(6),
    CONSTRAINT uq_ec_setting UNIQUE (organization_id, setting_group, setting_key)
);

CREATE INDEX IF NOT EXISTS idx_ec_setting_group ON ec_settings (organization_id, setting_group);

-- =============================================================================
-- TAX CLASS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_tax_classes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    class_code      VARCHAR(30),
    class_name      VARCHAR(150),
    description     TEXT,
    active          BOOLEAN DEFAULT TRUE,
    CONSTRAINT uq_ec_taxclass UNIQUE (organization_id, class_code)
);

-- =============================================================================
-- TAX RULES  (Bangladesh: standard VAT = 15%)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_tax_rules
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    tax_class_id    BIGINT REFERENCES ec_tax_classes(id),
    country         VARCHAR(100) DEFAULT 'Bangladesh',
    division        VARCHAR(100),
    district        VARCHAR(100),
    tax_name        VARCHAR(100),
    tax_percent     NUMERIC(8,2),
    effective_from  DATE,
    effective_to    DATE,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_taxrule_class ON ec_tax_rules (tax_class_id);
CREATE INDEX IF NOT EXISTS idx_ec_taxrule_org   ON ec_tax_rules (organization_id);

-- =============================================================================
-- LANGUAGE
-- Note: Bengali is default for Bangladesh context
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_languages
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code    VARCHAR(20) NOT NULL,
    language_name    VARCHAR(100),
    native_name      VARCHAR(100),
    rtl              BOOLEAN DEFAULT FALSE,
    default_language BOOLEAN DEFAULT FALSE,
    active           BOOLEAN DEFAULT TRUE,
    CONSTRAINT uq_ec_language UNIQUE (language_code)
);

INSERT INTO ec_languages (language_code, language_name, native_name, rtl, default_language, active)
VALUES
    ('en', 'English', 'English', FALSE, FALSE, TRUE),
    ('bn', 'Bengali', 'বাংলা',  FALSE, TRUE,  TRUE)
ON CONFLICT (language_code) DO NOTHING;

-- =============================================================================
-- TRANSLATIONS  (i18n content for storefront entities)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_translations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT NOT NULL REFERENCES org_organizations(id),
    language_id       BIGINT REFERENCES ec_languages(id),
    entity_type       VARCHAR(30),
    entity_id         BIGINT,
    field_name        VARCHAR(100),
    translated_value  TEXT,
    CONSTRAINT uq_ec_translation
        UNIQUE (organization_id, language_id, entity_type, entity_id, field_name)
);

CREATE INDEX IF NOT EXISTS idx_ec_trans_entity ON ec_translations (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_ec_trans_org    ON ec_translations (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_trans_lang   ON ec_translations (language_id);

-- =============================================================================
-- API CONFIGURATIONS  (payment gateways: bKash, SSLCommerz; courier: Pathao, Redx)
-- SECURITY: api_key / api_secret / password → encrypt at rest in production
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_api_configurations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    api_name        VARCHAR(100),
    api_url         VARCHAR(700),
    api_key         TEXT,           -- ENCRYPT IN PRODUCTION (AES-256)
    api_secret      TEXT,           -- ENCRYPT IN PRODUCTION
    username        VARCHAR(200),
    password        TEXT,           -- ENCRYPT IN PRODUCTION
    webhook_url     VARCHAR(700),
    sandbox_mode    BOOLEAN DEFAULT TRUE,
    active          BOOLEAN DEFAULT TRUE,
    CONSTRAINT uq_ec_api_config UNIQUE (organization_id, api_name)
);

CREATE INDEX IF NOT EXISTS idx_ec_apiconfig_org ON ec_api_configurations (organization_id);

-- =============================================================================
-- ERP GL ACCOUNT DEFAULTS
--
-- Mirrors hrm_payroll_account_mappings pattern exactly:
--   • One row per organization
--   • All account IDs reference acc_chart_of_accounts (ChartOfAccount entity)
--   • Sub-account reference uses acc_chart_of_accounts_sub (ChartOfAccountSub)
--
-- EcErpBridgeService lookup priority:
--   1. Check ec_gl_account_defaults for org
--   2. Fall back to acc_mapping (existing ERP mapping if ECOMMERCE module_type exists)
--   3. Fall back to first matching account_type (ASSET/REVENUE/LIABILITY)
--
-- Aligns with JournalEntryLine.account (ChartOfAccount) and
-- JournalEntryLine.subAccount (ChartOfAccountSub)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_gl_account_defaults
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at                      TIMESTAMP(6) DEFAULT NOW(),
    updated_at                      TIMESTAMP(6),
    created_by                      VARCHAR(100),
    updated_by                      VARCHAR(100),

    organization_id                 BIGINT NOT NULL
        REFERENCES org_organizations(id),

    -- ── Revenue accounts (ChartOfAccount.accountType = REVENUE) ──────────────
    sales_revenue_account_id        BIGINT REFERENCES acc_chart_of_accounts(id),
    sales_returns_account_id        BIGINT REFERENCES acc_chart_of_accounts(id),

    -- ── Cost of Goods Sold (ChartOfAccount.accountType = EXPENSE) ────────────
    cogs_account_id                 BIGINT REFERENCES acc_chart_of_accounts(id),

    -- ── Accounts Receivable control (ChartOfAccount.accountType = ASSET) ─────
    -- Used when ec_customers.erp_sub_account_id IS NULL (no AR sub-account yet)
    accounts_receivable_id          BIGINT REFERENCES acc_chart_of_accounts(id),

    -- ── Tax (ChartOfAccount.accountType = LIABILITY) ──────────────────────────
    vat_payable_account_id          BIGINT REFERENCES acc_chart_of_accounts(id),

    -- ── Discount expense (ChartOfAccount.accountType = EXPENSE) ──────────────
    discount_expense_account_id     BIGINT REFERENCES acc_chart_of_accounts(id),

    -- ── Shipping income (ChartOfAccount.accountType = REVENUE) ───────────────
    shipping_income_account_id      BIGINT REFERENCES acc_chart_of_accounts(id),

    -- ── Default receiving bank/cash sub-account (ChartOfAccountSub STI) ──────
    -- BankAccount or CashAccount discriminator
    -- Overridden per-payment by ec_payments.receiving_sub_account_id
    default_bank_sub_account_id     BIGINT REFERENCES acc_chart_of_accounts_sub(id),

    CONSTRAINT uq_ec_gl_defaults UNIQUE (organization_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_gl_defaults_org ON ec_gl_account_defaults (organization_id);

-- =============================================================================
-- ERP DOCUMENT MAPPING
-- Maps ecommerce lifecycle events to ERP DocumentType enum values
-- (matches global_business_documents.document_type CHECK constraint)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_document_mapping
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id     BIGINT NOT NULL REFERENCES org_organizations(id),

    -- Ecommerce event name (internal EC lifecycle event)
    ec_document_type    VARCHAR(100),

    -- ERP DocumentType enum value (must match DocumentType enum exactly)
    -- e.g. 'SALES_INVOICE', 'DELIVERY_CHALLAN', 'CREDIT_NOTE', 'RECEIPT_VOUCHER'
    erp_document_type   VARCHAR(100),

    auto_create         BOOLEAN DEFAULT TRUE,

    -- Optional GL account overrides for this specific mapping
    debit_account_id    BIGINT REFERENCES acc_chart_of_accounts(id),
    credit_account_id   BIGINT REFERENCES acc_chart_of_accounts(id),

    CONSTRAINT uq_ec_docmap UNIQUE (organization_id, ec_document_type)
);

CREATE INDEX IF NOT EXISTS idx_ec_docmap_org ON ec_document_mapping (organization_id);

-- Seed canonical EC → ERP document type mappings
INSERT INTO ec_document_mapping (organization_id, ec_document_type, erp_document_type, auto_create)
SELECT
    o.id,
    e.ec_doc,
    e.erp_doc,
    TRUE
FROM org_organizations o
CROSS JOIN (VALUES
    ('ORDER_CONFIRMED',   'SALES_INVOICE'),
    ('PAYMENT_SUCCESS',   'RECEIPT_VOUCHER'),
    ('ORDER_SHIPPED',     'DELIVERY_CHALLAN'),
    ('RETURN_APPROVED',   'CREDIT_NOTE'),
    ('REFUND_ISSUED',     'PAYMENT_VOUCHER')
) AS e(ec_doc, erp_doc)
ON CONFLICT (organization_id, ec_document_type) DO NOTHING;

-- =============================================================================
-- SCHEDULED JOBS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_scheduled_jobs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES org_organizations(id),
    job_name        VARCHAR(200),
    cron_expression VARCHAR(100),
    last_run        TIMESTAMP(6),
    next_run        TIMESTAMP(6),
    last_result     VARCHAR(20) DEFAULT 'PENDING',
    error_message   TEXT,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_job_org ON ec_scheduled_jobs (organization_id);

-- =============================================================================
-- FEATURE FLAGS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_feature_flags
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    feature_name    VARCHAR(200),
    enabled         BOOLEAN DEFAULT FALSE,
    notes           VARCHAR(500),
    CONSTRAINT uq_ec_feature UNIQUE (organization_id, feature_name)
);

CREATE INDEX IF NOT EXISTS idx_ec_feature_org ON ec_feature_flags (organization_id);

-- =============================================================================
-- WEBHOOKS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_webhooks
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT NOT NULL REFERENCES org_organizations(id),
    webhook_name      VARCHAR(200),
    event_name        VARCHAR(100),
    target_url        VARCHAR(700),
    secret_key        VARCHAR(500),
    last_triggered_at TIMESTAMP(6),
    failure_count     INTEGER DEFAULT 0,
    active            BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_webhook_org ON ec_webhooks (organization_id);

-- =============================================================================
-- MODULE REGISTRATION — sec_org_modules
-- =============================================================================

INSERT INTO sec_org_modules (organization_id, module_key, active, granted_by, granted_at, notes)
SELECT id, 'ECOMMERCE', FALSE, 'SYSTEM', NOW(),
       'Ecommerce module — disabled by default, enable per org via super-admin'
FROM org_organizations
ON CONFLICT (organization_id, module_key) DO NOTHING;
