-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 01 : MASTER TABLES (Category, Product Catalog, Variants, Images)
-- PostgreSQL 16+   |   schema prefix: ec_
-- ERP integration  : org_organizations, inv_items, sec_users (all existing)
--
-- FIXES vs uploaded version:
--   • All idempotent ON CONFLICT DO NOTHING guards
--   • organization_id FK on every table
--   • Canonical audit columns (created_at/by, updated_at/by)
--   • ec_product_catalog linked to inv_items (existing ERP item master)
--   • ec_product_catalog.average_rating removed (derived from ec_review_summary)
--   • Index names prefixed to avoid collision with existing ERP indexes
-- =============================================================================

-- =============================================================================
-- ECOMMERCE PRODUCT CATEGORY
-- Hierarchical: level_no tracked; parent_category_id is self-referencing
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_categories
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    parent_category_id  BIGINT
        REFERENCES ec_categories(id),

    category_code       VARCHAR(50)  NOT NULL,
    category_name       VARCHAR(200) NOT NULL,
    slug                VARCHAR(250) NOT NULL,

    short_description   VARCHAR(500),
    description         TEXT,

    image_url           VARCHAR(700),
    banner_url          VARCHAR(700),
    icon                VARCHAR(100),

    meta_title          VARCHAR(255),
    meta_keywords       VARCHAR(500),
    meta_description    VARCHAR(1000),

    display_order       INTEGER  DEFAULT 0,
    level_no            INTEGER  DEFAULT 1,

    is_menu             BOOLEAN  DEFAULT TRUE,
    is_featured         BOOLEAN  DEFAULT FALSE,

    active              BOOLEAN  DEFAULT TRUE,
    deleted             BOOLEAN  DEFAULT FALSE,

    CONSTRAINT uq_ec_category_code  UNIQUE (organization_id, category_code),
    CONSTRAINT uq_ec_category_slug  UNIQUE (organization_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_ec_cat_org      ON ec_categories (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_cat_parent   ON ec_categories (parent_category_id);
CREATE INDEX IF NOT EXISTS idx_ec_cat_slug     ON ec_categories (slug);
CREATE INDEX IF NOT EXISTS idx_ec_cat_active   ON ec_categories (active);
CREATE INDEX IF NOT EXISTS idx_ec_cat_featured ON ec_categories (is_featured);

-- =============================================================================
-- CATEGORY ATTRIBUTE DEFINITION
-- Defines filterable/searchable attribute schema per category
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_category_attributes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at      TIMESTAMP(6),
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(100),

    category_id     BIGINT NOT NULL
        REFERENCES ec_categories(id) ON DELETE CASCADE,

    attribute_name  VARCHAR(150) NOT NULL,
    attribute_label VARCHAR(150),

    data_type       VARCHAR(30) NOT NULL
        CHECK (data_type IN ('TEXT','NUMBER','BOOLEAN','DATE','LIST','COLOR')),

    is_required     BOOLEAN DEFAULT FALSE,
    searchable      BOOLEAN DEFAULT TRUE,
    filterable      BOOLEAN DEFAULT TRUE,
    sortable        BOOLEAN DEFAULT FALSE,

    display_order   INTEGER DEFAULT 0,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_catattr_cat ON ec_category_attributes (category_id);

-- =============================================================================
-- PRODUCT CATALOG
-- One ec_product_catalog row per inv_items row.
-- The inv_items record is the authoritative source for item_code, costing,
-- stock, UoM. ec_product_catalog adds the storefront layer.
--
-- REMOVED: average_rating (now live-computed from ec_review_summary)
--          total_reviews  (same)
-- ADDED  : erp_sub_account_id → optional link to acc_chart_of_accounts_sub
--          (CUSTOMER sub-account for AR posting when the product is a service)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_catalog
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at              TIMESTAMP(6),
    created_by              VARCHAR(100),
    updated_at              TIMESTAMP(6),
    updated_by              VARCHAR(100),

    organization_id         BIGINT NOT NULL
        REFERENCES org_organizations(id),

    -- Link to ERP item master (FINISHED_GOOD or SERVICE items)
    item_id                 BIGINT NOT NULL
        REFERENCES inv_items(id),

    category_id             BIGINT
        REFERENCES ec_categories(id),

    slug                    VARCHAR(250) NOT NULL,

    product_title           VARCHAR(300) NOT NULL,
    short_description       VARCHAR(1000),
    description             TEXT,
    specification           TEXT,

    -- SEO
    seo_title               VARCHAR(255),
    seo_keywords            VARCHAR(500),
    seo_description         VARCHAR(1000),

    -- Rich content
    youtube_video           VARCHAR(500),
    warranty_information    VARCHAR(500),
    return_policy           TEXT,
    shipping_information    TEXT,

    -- Order constraints
    minimum_order_qty       NUMERIC(12,2) DEFAULT 1,
    maximum_order_qty       NUMERIC(12,2),

    -- Merchandising flags
    featured                BOOLEAN DEFAULT FALSE,
    best_seller             BOOLEAN DEFAULT FALSE,
    trending                BOOLEAN DEFAULT FALSE,
    new_arrival             BOOLEAN DEFAULT FALSE,
    recommended             BOOLEAN DEFAULT FALSE,

    -- Publishing
    published               BOOLEAN DEFAULT FALSE,
    publish_date            TIMESTAMP,

    -- Counters (updated by triggers/service, NOT stored with reviews)
    total_sales             BIGINT  DEFAULT 0,
    total_views             BIGINT  DEFAULT 0,

    active                  BOOLEAN DEFAULT TRUE,
    deleted                 BOOLEAN DEFAULT FALSE,

    CONSTRAINT uq_ec_product_slug UNIQUE (organization_id, slug),
    CONSTRAINT uq_ec_product_item UNIQUE (organization_id, item_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_prod_org      ON ec_product_catalog (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_prod_item     ON ec_product_catalog (item_id);
CREATE INDEX IF NOT EXISTS idx_ec_prod_cat      ON ec_product_catalog (category_id);
CREATE INDEX IF NOT EXISTS idx_ec_prod_slug     ON ec_product_catalog (slug);
CREATE INDEX IF NOT EXISTS idx_ec_prod_featured ON ec_product_catalog (featured);
CREATE INDEX IF NOT EXISTS idx_ec_prod_best     ON ec_product_catalog (best_seller);
CREATE INDEX IF NOT EXISTS idx_ec_prod_trending ON ec_product_catalog (trending);
CREATE INDEX IF NOT EXISTS idx_ec_prod_pub      ON ec_product_catalog (published);
CREATE INDEX IF NOT EXISTS idx_ec_prod_active   ON ec_product_catalog (active, deleted);

-- =============================================================================
-- PRODUCT IMAGE
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_images
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at      TIMESTAMP(6),
    created_by      VARCHAR(100),

    product_id      BIGINT NOT NULL
        REFERENCES ec_product_catalog(id) ON DELETE CASCADE,

    image_url       VARCHAR(700) NOT NULL,
    thumbnail_url   VARCHAR(700),
    alt_text        VARCHAR(255),
    display_order   INTEGER DEFAULT 0,
    is_primary      BOOLEAN DEFAULT FALSE,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_prodimg_prod ON ec_product_images (product_id);

-- =============================================================================
-- PRODUCT VARIANT
-- A variant is tied to a SEPARATE inv_items row (different SKU/barcode).
-- Dimensions/weight kept here for shipping-rate calculations.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_variants
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at      TIMESTAMP(6),
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP(6),
    updated_by      VARCHAR(100),

    product_id      BIGINT NOT NULL
        REFERENCES ec_product_catalog(id) ON DELETE CASCADE,

    -- Optional separate inv_items row for this variant
    item_id         BIGINT
        REFERENCES inv_items(id),

    variant_code    VARCHAR(50),
    sku             VARCHAR(100),
    barcode         VARCHAR(100),
    variant_name    VARCHAR(200),

    color           VARCHAR(100),
    size_name       VARCHAR(100),

    weight          NUMERIC(12,3),
    length          NUMERIC(12,3),
    width           NUMERIC(12,3),
    height          NUMERIC(12,3),

    selling_price   NUMERIC(18,2),
    compare_price   NUMERIC(18,2),
    cost_price      NUMERIC(18,2),

    active          BOOLEAN DEFAULT TRUE,
    deleted         BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_ec_variant_prod ON ec_product_variants (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_variant_item ON ec_product_variants (item_id);

-- =============================================================================
-- PRODUCT ATTRIBUTE VALUES  (instance values for a specific product)
-- Ties a category attribute definition to a product with its value
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_attribute_values
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id            BIGINT NOT NULL
        REFERENCES ec_product_catalog(id) ON DELETE CASCADE,

    category_attribute_id BIGINT NOT NULL
        REFERENCES ec_category_attributes(id) ON DELETE CASCADE,

    attribute_value       TEXT,

    CONSTRAINT uq_ec_prodattr UNIQUE (product_id, category_attribute_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_prodattr_prod ON ec_product_attribute_values (product_id);

-- =============================================================================
-- PRODUCT TAGS  (free-form searchable tags)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_product_tags
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    tag_name    VARCHAR(100) NOT NULL,
    slug        VARCHAR(120) NOT NULL,

    CONSTRAINT uq_ec_tag UNIQUE (organization_id, slug)
);

CREATE TABLE IF NOT EXISTS ec_product_tag_map
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id) ON DELETE CASCADE,
    tag_id     BIGINT NOT NULL REFERENCES ec_product_tags(id)    ON DELETE CASCADE,
    CONSTRAINT uq_ec_prod_tag UNIQUE (product_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_prodtag_prod ON ec_product_tag_map (product_id);
