-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 02 : CUSTOMER MODULE
-- PostgreSQL 16+   |   schema prefix: ec_
--
-- FIXES vs uploaded version:
--   • ec_customers.erp_sub_account_id → FK to acc_chart_of_accounts_sub
--     (sub_account_type = 'CUSTOMER').  When a B2C customer registers, the
--     ERP service creates/links their AR sub-account here so GL posting works.
--   • Removed duplicate UNIQUE constraints that conflicted when email = NULL
--     (use partial index instead)
--   • ec_customer_otp — removed bare customer_id FK without cascade guard
--   • All tables get organization_id or inherit it via customer_id
-- =============================================================================

-- =============================================================================
-- CUSTOMER
-- ec_customers are B2C / portal customers.
-- erp_sub_account_id bridges to the ERP Accounts Receivable sub-ledger.
-- user_id bridges to sec_users if the customer also has ERP portal access.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customers
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    -- Optional bridge to ERP user (for B2B portal login)
    user_id             BIGINT
        REFERENCES sec_users(id),

    -- Bridge to ERP AR sub-ledger (acc_chart_of_accounts_sub sub_account_type='CUSTOMER')
    -- Populated by service when customer is confirmed/converted
    erp_sub_account_id  BIGINT
        REFERENCES acc_chart_of_accounts_sub(id),

    customer_code       VARCHAR(50)  NOT NULL,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100),
    full_name           VARCHAR(200),

    email               VARCHAR(200),
    phone               VARCHAR(30)  NOT NULL,

    password_hash       VARCHAR(255),

    gender              VARCHAR(20)
        CHECK (gender IN ('MALE','FEMALE','OTHER')),

    date_of_birth       DATE,
    profile_image       VARCHAR(500),

    company_name        VARCHAR(200),
    tax_number          VARCHAR(100),
    national_id         VARCHAR(100),

    email_verified      BOOLEAN DEFAULT FALSE,
    phone_verified      BOOLEAN DEFAULT FALSE,

    account_status      VARCHAR(20) DEFAULT 'ACTIVE'
        CHECK (account_status IN ('ACTIVE','BLOCKED','PENDING','DELETED')),

    customer_group      VARCHAR(50),

    total_orders        INTEGER        DEFAULT 0,
    total_purchase      NUMERIC(18,2)  DEFAULT 0,
    reward_points       INTEGER        DEFAULT 0,
    wallet_balance      NUMERIC(18,2)  DEFAULT 0,

    last_login_at       TIMESTAMP,

    active              BOOLEAN DEFAULT TRUE,
    deleted             BOOLEAN DEFAULT FALSE,

    CONSTRAINT uq_ec_customer_code  UNIQUE (organization_id, customer_code)
);

-- Partial unique indexes (handle nullable email safely)
CREATE UNIQUE INDEX IF NOT EXISTS uq_ec_customer_email
    ON ec_customers (organization_id, email)
    WHERE email IS NOT NULL AND deleted = FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_ec_customer_phone
    ON ec_customers (organization_id, phone)
    WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_ec_cust_org    ON ec_customers (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_cust_email  ON ec_customers (email);
CREATE INDEX IF NOT EXISTS idx_ec_cust_phone  ON ec_customers (phone);
CREATE INDEX IF NOT EXISTS idx_ec_cust_status ON ec_customers (account_status);
CREATE INDEX IF NOT EXISTS idx_ec_cust_sub    ON ec_customers (erp_sub_account_id);

-- =============================================================================
-- CUSTOMER ADDRESS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_addresses
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6),
    created_by          VARCHAR(100),
    updated_at          TIMESTAMP(6),
    updated_by          VARCHAR(100),

    customer_id         BIGINT NOT NULL
        REFERENCES ec_customers(id) ON DELETE CASCADE,

    address_type        VARCHAR(20)
        CHECK (address_type IN ('HOME','OFFICE','BILLING','SHIPPING','OTHER')),

    contact_person      VARCHAR(200),
    contact_phone       VARCHAR(30),

    country             VARCHAR(100) DEFAULT 'Bangladesh',
    division            VARCHAR(100),
    district            VARCHAR(100),
    upazila             VARCHAR(100),
    post_code           VARCHAR(20),
    area                VARCHAR(150),
    address_line1       VARCHAR(300),
    address_line2       VARCHAR(300),
    landmark            VARCHAR(200),

    latitude            NUMERIC(12,8),
    longitude           NUMERIC(12,8),

    default_shipping    BOOLEAN DEFAULT FALSE,
    default_billing     BOOLEAN DEFAULT FALSE,

    active              BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_custaddr_cust ON ec_customer_addresses (customer_id);

-- =============================================================================
-- CUSTOMER WALLET LEDGER
-- Records every credit/debit to the customer's in-app wallet balance.
-- balance_after is a snapshot for fast balance retrieval without summing.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_wallet
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),

    customer_id         BIGINT NOT NULL
        REFERENCES ec_customers(id) ON DELETE CASCADE,

    transaction_type    VARCHAR(20)
        CHECK (transaction_type IN ('CREDIT','DEBIT')),

    reference_type      VARCHAR(50),   -- 'ORDER' | 'REFUND' | 'TOPUP' | 'ADJUSTMENT'
    reference_id        BIGINT,        -- order_id / refund_id

    narration           VARCHAR(500),
    amount              NUMERIC(18,2) NOT NULL,
    balance_after       NUMERIC(18,2) NOT NULL,

    created_by          VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_ec_wallet_cust ON ec_customer_wallet (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_wallet_ref  ON ec_customer_wallet (reference_type, reference_id);

-- =============================================================================
-- REWARD POINTS LEDGER
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_reward_points
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),

    customer_id         BIGINT NOT NULL
        REFERENCES ec_customers(id) ON DELETE CASCADE,

    reference_type      VARCHAR(50),
    reference_id        BIGINT,

    points              INTEGER NOT NULL,

    transaction_type    VARCHAR(20)
        CHECK (transaction_type IN ('EARN','REDEEM','ADJUST')),

    remarks             VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_ec_reward_cust ON ec_reward_points (customer_id);

-- =============================================================================
-- WISHLIST
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_wishlist
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) DEFAULT NOW(),

    customer_id BIGINT NOT NULL
        REFERENCES ec_customers(id) ON DELETE CASCADE,

    product_id  BIGINT NOT NULL
        REFERENCES ec_product_catalog(id) ON DELETE CASCADE,

    CONSTRAINT uq_ec_wishlist UNIQUE (customer_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_ec_wishlist_cust ON ec_wishlist (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_wishlist_prod ON ec_wishlist (product_id);

-- =============================================================================
-- RECENTLY VIEWED PRODUCTS
-- customer_id nullable — supports anonymous browsing tracking via session
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_recently_viewed
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id BIGINT
        REFERENCES ec_customers(id) ON DELETE CASCADE,

    product_id  BIGINT NOT NULL
        REFERENCES ec_product_catalog(id) ON DELETE CASCADE,

    viewed_at   TIMESTAMP(6) DEFAULT NOW(),
    ip_address  VARCHAR(50),
    device_info VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_ec_recent_cust ON ec_recently_viewed (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_recent_prod ON ec_recently_viewed (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_recent_time ON ec_recently_viewed (viewed_at DESC);

-- =============================================================================
-- CUSTOMER LOGIN HISTORY
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_login_history
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id     BIGINT NOT NULL
        REFERENCES ec_customers(id) ON DELETE CASCADE,

    login_time      TIMESTAMP(6),
    logout_time     TIMESTAMP(6),
    ip_address      VARCHAR(50),
    browser         VARCHAR(150),
    operating_system VARCHAR(150),
    device          VARCHAR(150),
    login_status    VARCHAR(20),    -- SUCCESS | FAILED
    login_source    VARCHAR(50)     -- WEB | ANDROID | IOS
);

CREATE INDEX IF NOT EXISTS idx_ec_login_cust ON ec_customer_login_history (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_login_time ON ec_customer_login_history (login_time DESC);

-- =============================================================================
-- CUSTOMER OTP
-- customer_id nullable — OTP can be pre-registration (no customer row yet)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_otp
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id BIGINT
        REFERENCES ec_customers(id) ON DELETE CASCADE,

    phone       VARCHAR(30),
    email       VARCHAR(200),
    otp_code    VARCHAR(10),

    otp_type    VARCHAR(30)
        CHECK (otp_type IN ('LOGIN','REGISTER','FORGOT_PASSWORD','VERIFY_PHONE','VERIFY_EMAIL')),

    expiry_time TIMESTAMP(6),
    verified    BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_otp_cust  ON ec_customer_otp (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_otp_phone ON ec_customer_otp (phone);
CREATE INDEX IF NOT EXISTS idx_ec_otp_email ON ec_customer_otp (email);

-- =============================================================================
-- CUSTOMER DEVICE  (for push notifications)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_devices
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id BIGINT NOT NULL
        REFERENCES ec_customers(id) ON DELETE CASCADE,

    device_uuid  VARCHAR(200),
    device_name  VARCHAR(200),
    device_type  VARCHAR(50),    -- MOBILE | TABLET | DESKTOP
    os_name      VARCHAR(100),
    app_version  VARCHAR(50),
    push_token   TEXT,
    last_active  TIMESTAMP(6),
    active       BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_device_cust ON ec_customer_devices (customer_id);
