-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 04 : ORDER MANAGEMENT
-- PostgreSQL 16+   |   schema prefix: ec_
--
-- FIXES vs uploaded version:
--   • ec_orders.journal_entry_id → FK to acc_journal_entry_master
--     (SALES_VOUCHER created on order CONFIRMED; same bridge pattern as
--      prd_productions.journal_entry_id and hrm_payroll_runs.journal_entry_id)
--   • ec_orders.document_no added (document sequence pattern:
--     DocumentSequenceService.nextDocumentNumber → EC-ORG-YY-NNNNNN)
--   • ec_order_items: added inventory_lot_id FK → global_inv_lots
--     (needed for lot-tracked finished goods)
--   • ec_orders.order_no renamed to order_no for API compatibility but
--     document_no also stored (auto-generated)
--   • ec_orders.currency_code DEFAULT 'BDT' (Bangladesh context)
--   • Return/Refund tables: journal_entry_id added for CREDIT_NOTE voucher
-- =============================================================================

-- =============================================================================
-- ORDER
-- Lifecycle: DRAFT → CONFIRMED → (PROCESSING … DELIVERED) → COMPLETED
--            or → CANCELLED / RETURNED / REFUNDED
-- GL bridge: on CONFIRMED → SALES_VOUCHER JournalEntryMaster created
--   DR  Accounts Receivable (ec_customers.erp_sub_account_id or generic AR)
--   CR  Sales Revenue (per product category or default sales account)
--   CR  Tax Payable  (if VAT applicable)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_orders
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at              TIMESTAMP(6) DEFAULT NOW(),
    created_by              VARCHAR(100),
    updated_at              TIMESTAMP(6),
    updated_by              VARCHAR(100),

    organization_id         BIGINT NOT NULL
        REFERENCES org_organizations(id),

    customer_id             BIGINT
        REFERENCES ec_customers(id),

    cart_id                 BIGINT
        REFERENCES ec_cart(id),

    -- Storefront order number (human-visible, from DocumentSequenceService)
    order_no                VARCHAR(50) NOT NULL,

    order_date              TIMESTAMP(6) DEFAULT NOW(),

    order_source            VARCHAR(30) DEFAULT 'WEB'
        CHECK (order_source IN ('WEB','ANDROID','IOS','POS','FACEBOOK','API')),

    order_status            VARCHAR(30) DEFAULT 'PENDING'
        CHECK (order_status IN
            ('PENDING','CONFIRMED','PROCESSING','PACKING',
             'READY_TO_SHIP','SHIPPED','OUT_FOR_DELIVERY',
             'DELIVERED','COMPLETED','CANCELLED','RETURNED','REFUNDED')),

    payment_status          VARCHAR(20) DEFAULT 'UNPAID'
        CHECK (payment_status IN ('UNPAID','PARTIAL','PAID','REFUNDED')),

    shipping_status         VARCHAR(20) DEFAULT 'PENDING'
        CHECK (shipping_status IN
            ('PENDING','PACKED','SHIPPED','DELIVERED','RETURNED')),

    -- Amounts
    subtotal                NUMERIC(18,2) DEFAULT 0,
    product_discount        NUMERIC(18,2) DEFAULT 0,
    coupon_discount         NUMERIC(18,2) DEFAULT 0,
    shipping_charge         NUMERIC(18,2) DEFAULT 0,
    tax_amount              NUMERIC(18,2) DEFAULT 0,
    grand_total             NUMERIC(18,2) NOT NULL,
    paid_amount             NUMERIC(18,2) DEFAULT 0,
    due_amount              NUMERIC(18,2) DEFAULT 0,

    currency_code           VARCHAR(10)   DEFAULT 'BDT',
    exchange_rate           NUMERIC(18,6) DEFAULT 1,

    customer_note           TEXT,
    admin_note              TEXT,

    expected_delivery_date  DATE,
    completed_at            TIMESTAMP(6),
    cancelled_at            TIMESTAMP(6),

    -- ── GL BRIDGE (ERP integration) ──────────────────────────────────────────
    -- Populated on CONFIRMED transition by EcOrderService.confirmOrder()
    -- voucher_type = SALES_VOUCHER
    journal_entry_id        BIGINT
        REFERENCES acc_journal_entry_master(id),

    active                  BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_order_no UNIQUE (organization_id, order_no)
);

CREATE INDEX IF NOT EXISTS idx_ec_order_cust    ON ec_orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_order_status  ON ec_orders (order_status);
CREATE INDEX IF NOT EXISTS idx_ec_order_payment ON ec_orders (payment_status);
CREATE INDEX IF NOT EXISTS idx_ec_order_ship    ON ec_orders (shipping_status);
CREATE INDEX IF NOT EXISTS idx_ec_order_date    ON ec_orders (order_date DESC);
CREATE INDEX IF NOT EXISTS idx_ec_order_org     ON ec_orders (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_order_gl      ON ec_orders (journal_entry_id);

-- =============================================================================
-- ORDER ITEM
-- FIX: inventory_lot_id added for lot-tracked items (mirrors global_business_document_lines)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_order_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id        BIGINT NOT NULL
        REFERENCES ec_orders(id) ON DELETE CASCADE,

    product_id      BIGINT NOT NULL
        REFERENCES ec_product_catalog(id),

    variant_id      BIGINT
        REFERENCES ec_product_variants(id),

    -- Links to ERP item master and warehouse (for stock deduction on CONFIRMED)
    item_id         BIGINT
        REFERENCES inv_items(id),

    warehouse_id    BIGINT
        REFERENCES org_warehouses(id),

    -- FIX: lot tracking for finished goods
    inventory_lot_id BIGINT
        REFERENCES global_inv_lots(id),

    quantity        NUMERIC(12,3) NOT NULL,
    unit_price      NUMERIC(18,2) NOT NULL,
    discount_amount NUMERIC(18,2) DEFAULT 0,
    tax_amount      NUMERIC(18,2) DEFAULT 0,
    line_total      NUMERIC(18,2) NOT NULL,

    cost_price      NUMERIC(18,2),   -- COGS at time of sale
    profit_amount   NUMERIC(18,2),

    remarks         VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_ec_orderitem_order ON ec_order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_ec_orderitem_prod  ON ec_order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_ec_orderitem_item  ON ec_order_items (item_id);
CREATE INDEX IF NOT EXISTS idx_ec_orderitem_lot   ON ec_order_items (inventory_lot_id);

-- =============================================================================
-- ORDER STATUS HISTORY  (audit trail of every status change)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_order_status_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id    BIGINT NOT NULL
        REFERENCES ec_orders(id) ON DELETE CASCADE,

    status      VARCHAR(30) NOT NULL,
    remarks     TEXT,
    changed_by  VARCHAR(100),
    changed_at  TIMESTAMP(6) DEFAULT NOW(),
    ip_address  VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_ec_orderhist_order ON ec_order_status_history (order_id);

-- =============================================================================
-- ORDER ADDRESSES  (snapshot at time of order — never use live customer address)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_order_addresses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id        BIGINT NOT NULL
        REFERENCES ec_orders(id) ON DELETE CASCADE,

    address_type    VARCHAR(20)
        CHECK (address_type IN ('BILLING','SHIPPING')),

    full_name       VARCHAR(200),
    phone           VARCHAR(30),
    email           VARCHAR(200),

    country         VARCHAR(100),
    division        VARCHAR(100),
    district        VARCHAR(100),
    upazila         VARCHAR(100),
    postcode        VARCHAR(20),
    address_line1   VARCHAR(300),
    address_line2   VARCHAR(300),
    landmark        VARCHAR(200)
);

CREATE INDEX IF NOT EXISTS idx_ec_orderaddr_order ON ec_order_addresses (order_id);

-- =============================================================================
-- ORDER NOTES
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_order_notes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id    BIGINT NOT NULL
        REFERENCES ec_orders(id) ON DELETE CASCADE,

    note_type   VARCHAR(20)
        CHECK (note_type IN ('CUSTOMER','ADMIN','SYSTEM')),

    note        TEXT,
    created_by  VARCHAR(100),
    created_at  TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_ordernote_order ON ec_order_notes (order_id);

-- =============================================================================
-- RETURN REQUEST
-- GL bridge: on APPROVED → CREDIT_NOTE JournalEntryMaster created
--   DR  Sales Returns (revenue reversal)
--   CR  Accounts Receivable  (reduces customer liability)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_returns
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    order_id        BIGINT NOT NULL
        REFERENCES ec_orders(id),

    customer_id     BIGINT
        REFERENCES ec_customers(id),

    return_no       VARCHAR(50) NOT NULL,
    return_date     TIMESTAMP(6) DEFAULT NOW(),
    return_reason   TEXT,

    return_status   VARCHAR(30) DEFAULT 'REQUESTED'
        CHECK (return_status IN
            ('REQUESTED','APPROVED','REJECTED','RECEIVED','REFUNDED','COMPLETED')),

    refund_amount   NUMERIC(18,2),
    remarks         TEXT,

    -- GL BRIDGE: CREDIT_NOTE voucher on APPROVED
    journal_entry_id BIGINT
        REFERENCES acc_journal_entry_master(id),

    CONSTRAINT uq_ec_return_no UNIQUE (organization_id, return_no)
);

CREATE INDEX IF NOT EXISTS idx_ec_return_order  ON ec_returns (order_id);
CREATE INDEX IF NOT EXISTS idx_ec_return_status ON ec_returns (return_status);
CREATE INDEX IF NOT EXISTS idx_ec_return_gl     ON ec_returns (journal_entry_id);

-- =============================================================================
-- RETURN ITEM
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_return_items
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    return_id           BIGINT NOT NULL
        REFERENCES ec_returns(id) ON DELETE CASCADE,

    order_item_id       BIGINT NOT NULL
        REFERENCES ec_order_items(id),

    quantity            NUMERIC(12,3),
    reason              VARCHAR(500),

    condition_status    VARCHAR(30)
        CHECK (condition_status IN ('GOOD','DAMAGED','USED','DEFECTIVE')),

    approved_qty        NUMERIC(12,3)
);

CREATE INDEX IF NOT EXISTS idx_ec_returnitem_ret ON ec_return_items (return_id);

-- =============================================================================
-- REFUND
-- GL bridge: on REFUNDED → PAYMENT_VOUCHER or wallet credit in ERP
-- refund_method maps to ERP payment methods
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_refunds
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    return_id               BIGINT NOT NULL
        REFERENCES ec_returns(id),

    organization_id         BIGINT NOT NULL
        REFERENCES org_organizations(id),

    refund_no               VARCHAR(50),
    refund_date             TIMESTAMP(6) DEFAULT NOW(),

    refund_method           VARCHAR(30)
        CHECK (refund_method IN
            ('BKASH','NAGAD','ROCKET','CARD','BANK','WALLET','CASH')),

    refund_amount           NUMERIC(18,2),
    transaction_reference   VARCHAR(150),
    remarks                 TEXT,

    -- GL BRIDGE: PAYMENT_VOUCHER on refund disbursement
    journal_entry_id        BIGINT
        REFERENCES acc_journal_entry_master(id)
);

CREATE INDEX IF NOT EXISTS idx_ec_refund_return ON ec_refunds (return_id);
CREATE INDEX IF NOT EXISTS idx_ec_refund_gl     ON ec_refunds (journal_entry_id);
