-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 05 : PAYMENT MODULE
-- PostgreSQL 16+   |   schema prefix: ec_
--
-- FIXES vs uploaded version:
--   • Files 05 and 06 in the original upload were IDENTICAL (both payment+shipping).
--     Payments are separated here; Shipping is FILE 06.
--   • ec_payments.journal_entry_id → FK to acc_journal_entry_master
--     (RECEIPT_VOUCHER created on SUCCESS payment; same bridge pattern as ERP)
--     GL posting: DR Bank/Cash/MFS account  CR Accounts Receivable
--   • ec_payments.sub_account_id → FK to acc_chart_of_accounts_sub
--     (links to the bank/MFS sub-account for the receiving account)
-- =============================================================================

-- =============================================================================
-- PAYMENT
-- Each successful payment attempt creates/updates one row.
-- Multiple partial payments on the same order are allowed.
-- GL bridge: on payment_status = 'SUCCESS'
--   voucher_type = RECEIPT_VOUCHER
--   DR  Bank / MFS sub-account  (acc_chart_of_accounts_sub)
--   CR  Accounts Receivable     (customer sub-account)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_payments
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at              TIMESTAMP(6) DEFAULT NOW(),
    created_by              VARCHAR(100),
    updated_at              TIMESTAMP(6),
    updated_by              VARCHAR(100),

    organization_id         BIGINT NOT NULL
        REFERENCES org_organizations(id),

    order_id                BIGINT NOT NULL
        REFERENCES ec_orders(id),

    payment_no              VARCHAR(50) NOT NULL,

    payment_method          VARCHAR(30)
        CHECK (payment_method IN
            ('BKASH','NAGAD','ROCKET','SSLCOMMERZ','STRIPE',
             'PAYPAL','BANK','COD','WALLET','CASH')),

    payment_status          VARCHAR(20) DEFAULT 'PENDING'
        CHECK (payment_status IN
            ('PENDING','SUCCESS','FAILED','CANCELLED','REFUNDED','PARTIAL')),

    payment_date            TIMESTAMP(6),
    transaction_reference   VARCHAR(200),
    gateway_transaction_id  VARCHAR(200),
    bank_name               VARCHAR(200),
    account_number          VARCHAR(100),

    currency                VARCHAR(10)   DEFAULT 'BDT',
    exchange_rate           NUMERIC(18,6) DEFAULT 1,

    paid_amount             NUMERIC(18,2) NOT NULL,
    gateway_fee             NUMERIC(18,2) DEFAULT 0,

    remarks                 TEXT,

    -- ── GL BRIDGE ────────────────────────────────────────────────────────────
    -- RECEIPT_VOUCHER created by EcPaymentService.markSuccess()
    journal_entry_id        BIGINT
        REFERENCES acc_journal_entry_master(id),

    -- Bank/MFS sub-account receiving the payment
    -- (acc_chart_of_accounts_sub sub_account_type IN ('BANK','CASH'))
    receiving_sub_account_id BIGINT
        REFERENCES acc_chart_of_accounts_sub(id),

    CONSTRAINT uq_ec_payment_no UNIQUE (organization_id, payment_no)
);

CREATE INDEX IF NOT EXISTS idx_ec_payment_order  ON ec_payments (order_id);
CREATE INDEX IF NOT EXISTS idx_ec_payment_status ON ec_payments (payment_status);
CREATE INDEX IF NOT EXISTS idx_ec_payment_method ON ec_payments (payment_method);
CREATE INDEX IF NOT EXISTS idx_ec_payment_gl     ON ec_payments (journal_entry_id);
CREATE INDEX IF NOT EXISTS idx_ec_payment_org    ON ec_payments (organization_id);

-- =============================================================================
-- PAYMENT GATEWAY TRANSACTION LOG
-- Raw request/response payloads from payment gateway (bKash, SSLCommerz etc.)
-- Stored as JSONB for full auditability — never modify after insert
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_payment_transactions
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payment_id          BIGINT NOT NULL
        REFERENCES ec_payments(id) ON DELETE CASCADE,

    transaction_type    VARCHAR(20)
        CHECK (transaction_type IN ('AUTHORIZE','CAPTURE','REFUND','VOID')),

    gateway_name        VARCHAR(50),
    request_payload     JSONB,
    response_payload    JSONB,
    gateway_status      VARCHAR(50),
    gateway_reference   VARCHAR(200),
    transaction_time    TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_pmttx_payment ON ec_payment_transactions (payment_id);
