-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 09 : MARKETING & PROMOTIONS
-- PostgreSQL 16+   |   schema prefix: ec_
--
-- FIXES vs uploaded version:
--   • ec_wishlist_campaigns: added organization_id (was missing)
--   • ec_push_notifications: added created_at, created_by
--   • ec_customer_segments: aligned with ec_customers.customer_group
--   • ec_loyalty_programs: added organization_id (was missing)
-- =============================================================================

-- =============================================================================
-- NEWSLETTER SUBSCRIBERS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_newsletter
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at          TIMESTAMP(6) DEFAULT NOW(),

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    email               VARCHAR(200) NOT NULL,
    full_name           VARCHAR(200),

    subscription_status VARCHAR(20) DEFAULT 'SUBSCRIBED'
        CHECK (subscription_status IN ('SUBSCRIBED','UNSUBSCRIBED','BOUNCED')),

    verification_token  VARCHAR(255),
    verified            BOOLEAN DEFAULT FALSE,
    subscribed_at       TIMESTAMP(6) DEFAULT NOW(),
    unsubscribed_at     TIMESTAMP(6),

    CONSTRAINT uq_ec_newsletter UNIQUE (organization_id, email)
);

CREATE INDEX IF NOT EXISTS idx_ec_newsletter_status ON ec_newsletter (subscription_status);
CREATE INDEX IF NOT EXISTS idx_ec_newsletter_org    ON ec_newsletter (organization_id);

-- =============================================================================
-- EMAIL MARKETING CAMPAIGNS
-- Distinct from ec_campaigns (price promotions).
-- These are email blast campaigns to newsletter subscribers.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_email_campaigns
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at      TIMESTAMP(6) DEFAULT NOW(),
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP(6),

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    campaign_code   VARCHAR(50),
    campaign_name   VARCHAR(200),
    subject         VARCHAR(300),
    email_template  TEXT,

    scheduled_at    TIMESTAMP(6),
    sent_at         TIMESTAMP(6),
    total_sent      INTEGER DEFAULT 0,
    total_opened    INTEGER DEFAULT 0,
    total_clicked   INTEGER DEFAULT 0,

    campaign_status VARCHAR(20) DEFAULT 'DRAFT'
        CHECK (campaign_status IN
            ('DRAFT','SCHEDULED','RUNNING','COMPLETED','CANCELLED')),

    CONSTRAINT uq_ec_email_camp UNIQUE (organization_id, campaign_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_emailcamp_status ON ec_email_campaigns (campaign_status);
CREATE INDEX IF NOT EXISTS idx_ec_emailcamp_org    ON ec_email_campaigns (organization_id);

-- =============================================================================
-- PUSH NOTIFICATIONS  (mobile app / PWA push)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_push_notifications
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at      TIMESTAMP(6) DEFAULT NOW(),
    created_by      VARCHAR(100),

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    title           VARCHAR(300),
    message         TEXT,
    image_url       VARCHAR(500),
    target_url      VARCHAR(500),

    send_to         VARCHAR(30)
        CHECK (send_to IN
            ('ALL','CUSTOMERS','VIP','NEW_CUSTOMERS','SEGMENT')),

    scheduled_at    TIMESTAMP(6),
    sent_at         TIMESTAMP(6),
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_push_org ON ec_push_notifications (organization_id);

-- =============================================================================
-- CUSTOMER SEGMENTS  (for targeted marketing)
-- FIX: aligned with ec_customers.customer_group
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_segments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id  BIGINT NOT NULL
        REFERENCES org_organizations(id),

    segment_code     VARCHAR(50),
    segment_name     VARCHAR(200),
    description      TEXT,

    minimum_purchase NUMERIC(18,2),
    minimum_orders   INTEGER,
    active           BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_segment UNIQUE (organization_id, segment_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_segment_org ON ec_customer_segments (organization_id);

-- =============================================================================
-- LOYALTY PROGRAM CONFIGURATION
-- FIX: organization_id added (was missing in original)
-- earn_rate: BDT spent per point earned
-- redeem_rate: points per BDT discount
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_loyalty_programs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    program_name    VARCHAR(200),
    earn_rate       NUMERIC(12,4),    -- points earned per BDT spent
    redeem_rate     NUMERIC(12,4),    -- BDT discount per point redeemed
    minimum_points  INTEGER,
    expiry_days     INTEGER,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_loyalty_org ON ec_loyalty_programs (organization_id);

-- =============================================================================
-- GIFT CARDS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_gift_cards
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    gift_card_code  VARCHAR(100),
    initial_amount  NUMERIC(18,2),
    balance_amount  NUMERIC(18,2),
    expiry_date     DATE,

    customer_id     BIGINT
        REFERENCES ec_customers(id),

    active          BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_gift_card UNIQUE (organization_id, gift_card_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_giftcard_cust ON ec_gift_cards (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_giftcard_org  ON ec_gift_cards (organization_id);

-- =============================================================================
-- AFFILIATE PROGRAM
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_affiliates
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    customer_id         BIGINT
        REFERENCES ec_customers(id),

    affiliate_code      VARCHAR(100),
    commission_rate     NUMERIC(8,2),

    total_sales         NUMERIC(18,2) DEFAULT 0,
    total_commission    NUMERIC(18,2) DEFAULT 0,
    payable_amount      NUMERIC(18,2) DEFAULT 0,

    status              VARCHAR(20) DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE','BLOCKED','SUSPENDED')),

    CONSTRAINT uq_ec_affiliate UNIQUE (organization_id, affiliate_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_affiliate_cust ON ec_affiliates (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_affiliate_org  ON ec_affiliates (organization_id);

-- =============================================================================
-- REFERRAL TRACKING
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_referrals
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    affiliate_id        BIGINT
        REFERENCES ec_affiliates(id),

    referred_customer   BIGINT
        REFERENCES ec_customers(id),

    referral_bonus      NUMERIC(18,2),
    referral_date       TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_referral_aff ON ec_referrals (affiliate_id);

-- =============================================================================
-- PROMO CODES  (simpler than coupons — single-use disposable codes)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_promo_codes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    promo_code      VARCHAR(50),
    description     TEXT,

    discount_type   VARCHAR(20)
        CHECK (discount_type IN ('PERCENTAGE','FIXED')),

    discount_value  NUMERIC(18,2),
    valid_from      TIMESTAMP(6),
    valid_to        TIMESTAMP(6),
    usage_limit     INTEGER,
    active          BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_promo UNIQUE (organization_id, promo_code)
);

CREATE INDEX IF NOT EXISTS idx_ec_promo_org ON ec_promo_codes (organization_id);

-- =============================================================================
-- IN-APP CUSTOMER NOTIFICATIONS
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_notifications
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    customer_id         BIGINT
        REFERENCES ec_customers(id),

    notification_type   VARCHAR(30)
        CHECK (notification_type IN ('EMAIL','SMS','PUSH','IN_APP')),

    title               VARCHAR(300),
    message             TEXT,
    read_flag           BOOLEAN DEFAULT FALSE,
    sent_at             TIMESTAMP(6),
    created_at          TIMESTAMP(6) DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ec_notif_cust ON ec_notifications (customer_id);
CREATE INDEX IF NOT EXISTS idx_ec_notif_org  ON ec_notifications (organization_id);

-- =============================================================================
-- MARKETING AUTOMATION RULES
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_marketing_automation
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id  BIGINT NOT NULL
        REFERENCES org_organizations(id),

    automation_name  VARCHAR(200),
    trigger_event    VARCHAR(100),   -- 'CART_ABANDONED' | 'ORDER_COMPLETED' etc.
    action_type      VARCHAR(100),   -- 'SEND_EMAIL' | 'PUSH_NOTIFICATION' etc.
    delay_hours      INTEGER DEFAULT 0,
    active           BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_mktauto_org ON ec_marketing_automation (organization_id);

-- =============================================================================
-- WISHLIST CAMPAIGNS
-- FIX: organization_id added (was missing in original)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_wishlist_campaigns
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id  BIGINT NOT NULL
        REFERENCES org_organizations(id),

    campaign_name    VARCHAR(200),
    discount_percent NUMERIC(5,2),
    start_date       TIMESTAMP(6),
    end_date         TIMESTAMP(6),
    active           BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_wishcamp_org ON ec_wishlist_campaigns (organization_id);

-- =============================================================================
-- CUSTOMER COUPON ASSIGNMENTS  (pre-assigned coupons to specific customers)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_customer_coupons
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id   BIGINT
        REFERENCES ec_customers(id),

    coupon_id     BIGINT
        REFERENCES ec_coupon(id),

    assigned_date TIMESTAMP(6) DEFAULT NOW(),
    used          BOOLEAN DEFAULT FALSE,
    used_date     TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_ec_custcoupon_cust ON ec_customer_coupons (customer_id);

-- =============================================================================
-- SEARCH KEYWORDS  (popular search terms — for autocomplete and analytics)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_search_keywords
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    keyword      VARCHAR(200),
    search_count INTEGER DEFAULT 0,
    last_search  TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_ec_keyword     ON ec_search_keywords (keyword);
CREATE INDEX IF NOT EXISTS idx_ec_keyword_org ON ec_search_keywords (organization_id);
