-- =============================================================================
-- SPINDLE ERP — ENTERPRISE ECOMMERCE MODULE
-- FILE 11 : GLOBAL SETTINGS, TAX, LOCALIZATION & ERP INTEGRATION
-- PostgreSQL 16+   |   schema prefix: ec_
--
-- FIXES vs uploaded version:
--
--   REMOVED TABLES (already exist in the ERP, no duplication):
--     • ec_currencies     → use stp_currencies (ERP already has this)
--     • ec_exchange_rates → use stp_currencies + exchange rate service
--     • ec_erp_integrations → sync is service-layer concern, not a config table
--     • ec_system_parameters → use ec_settings (consolidated)
--
--   FIXED TABLES:
--     • ec_tax_classes: renamed tax class to match ERP naming patterns
--     • ec_languages: UNIQUE on language_code only (was missing org scope)
--     • ec_translations: org-scoped for multi-tenant i18n
--     • ec_api_configurations: sensitive fields (api_key, api_secret, password)
--       stored as TEXT — in production these should be encrypted at-rest
--     • ec_scheduled_jobs: added last_result + error_message columns
--     • ec_feature_flags: org-scoped (was missing constraints)
--     • ec_webhooks: added last_triggered_at, failure_count
--     • ec_document_mapping: renamed ecommerce_document → ec_document_type
--       and erp_document → erp_document_type for clarity
--
--   REUSES ERP TABLES (no new tables needed):
--     • Currency         → stp_currencies
--     • Exchange rate    → ec_settings or external rate service
--     • Organization     → org_organizations
--     • Warehouse        → org_warehouses
--     • GL Accounts      → acc_chart_of_accounts + acc_chart_of_accounts_sub
--     • Document Seq     → stp_document_sequences (via DocumentSequenceService)
-- =============================================================================

-- =============================================================================
-- ECOMMERCE SETTINGS  (key-value store for store configuration)
-- Examples: store_name, currency_symbol, low_stock_threshold, timezone
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_settings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    setting_group   VARCHAR(100),   -- 'GENERAL' | 'PAYMENT' | 'SHIPPING' | 'SEO' | 'NOTIFICATION'
    setting_key     VARCHAR(150),
    setting_value   TEXT,

    data_type       VARCHAR(30)
        CHECK (data_type IN ('STRING','NUMBER','BOOLEAN','JSON')),

    description     TEXT,
    editable        BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP(6) DEFAULT NOW(),
    updated_at      TIMESTAMP(6),

    CONSTRAINT uq_ec_setting UNIQUE (organization_id, setting_group, setting_key)
);

CREATE INDEX IF NOT EXISTS idx_ec_setting_group ON ec_settings (organization_id, setting_group);

-- =============================================================================
-- TAX CLASS  (e.g. 'STANDARD_VAT_15', 'ZERO_RATED', 'EXEMPT')
-- Referenced from ec_product_catalog via tax_class_id (add column if needed)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_tax_classes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    class_code      VARCHAR(30),
    class_name      VARCHAR(150),
    description     TEXT,
    active          BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_taxclass UNIQUE (organization_id, class_code)
);

-- =============================================================================
-- TAX RULES  (zone + class → rate matrix; Bangladesh has national 15% VAT)
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_tax_rules
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    tax_class_id    BIGINT
        REFERENCES ec_tax_classes(id),

    country         VARCHAR(100) DEFAULT 'Bangladesh',
    division        VARCHAR(100),
    district        VARCHAR(100),

    tax_name        VARCHAR(100),
    tax_percent     NUMERIC(8,2),

    effective_from  DATE,
    effective_to    DATE,

    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_taxrule_class ON ec_tax_rules (tax_class_id);
CREATE INDEX IF NOT EXISTS idx_ec_taxrule_org   ON ec_tax_rules (organization_id);

-- =============================================================================
-- LANGUAGE  (multi-language store support)
-- language_code: BCP-47 codes — 'en', 'bn', 'ar' etc.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_languages
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    language_code     VARCHAR(20) NOT NULL,
    language_name     VARCHAR(100),
    native_name       VARCHAR(100),
    rtl               BOOLEAN DEFAULT FALSE,
    default_language  BOOLEAN DEFAULT FALSE,
    active            BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_language UNIQUE (language_code)
);

-- Insert default languages
INSERT INTO ec_languages (language_code, language_name, native_name, rtl, default_language, active)
VALUES
    ('en', 'English',  'English', FALSE, FALSE, TRUE),
    ('bn', 'Bengali',  'বাংলা',  FALSE, TRUE,  TRUE)
ON CONFLICT (language_code) DO NOTHING;

-- =============================================================================
-- TRANSLATIONS  (content translation per entity field)
-- entity_type: 'PRODUCT' | 'CATEGORY' | 'BLOG' | 'PAGE' | 'BANNER'
-- field_name:  'product_title' | 'description' | 'slug' etc.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_translations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id   BIGINT NOT NULL
        REFERENCES org_organizations(id),

    language_id       BIGINT
        REFERENCES ec_languages(id),

    entity_type       VARCHAR(30),
    entity_id         BIGINT,
    field_name        VARCHAR(100),
    translated_value  TEXT,

    CONSTRAINT uq_ec_translation UNIQUE (organization_id, language_id, entity_type, entity_id, field_name)
);

CREATE INDEX IF NOT EXISTS idx_ec_trans_entity ON ec_translations (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_ec_trans_org    ON ec_translations (organization_id);
CREATE INDEX IF NOT EXISTS idx_ec_trans_lang   ON ec_translations (language_id);

-- =============================================================================
-- API CONFIGURATIONS  (payment gateways, courier APIs, SMS providers)
-- SECURITY NOTE: api_key, api_secret, password should be encrypted at rest
-- using database-level encryption or application-level AES-256 before storage
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_api_configurations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    api_name        VARCHAR(100),   -- 'BKASH' | 'SSLCOMMERZ' | 'PATHAO' | 'REDX'
    api_url         VARCHAR(700),
    api_key         TEXT,           -- ENCRYPT IN PRODUCTION
    api_secret      TEXT,           -- ENCRYPT IN PRODUCTION
    username        VARCHAR(200),
    password        TEXT,           -- ENCRYPT IN PRODUCTION
    webhook_url     VARCHAR(700),
    sandbox_mode    BOOLEAN DEFAULT TRUE,
    active          BOOLEAN DEFAULT TRUE,

    CONSTRAINT uq_ec_api_config UNIQUE (organization_id, api_name)
);

CREATE INDEX IF NOT EXISTS idx_ec_apiconfig_org ON ec_api_configurations (organization_id);

-- =============================================================================
-- ERP DOCUMENT MAPPING  (maps ecommerce events to ERP document types)
-- Used by EcErpBridgeService to know which ERP doc type to create on each event
-- Examples:
--   ec_document_type='ORDER_CONFIRMED'  erp_document_type='SALES_INVOICE'
--   ec_document_type='PAYMENT_SUCCESS'  erp_document_type='RECEIPT_VOUCHER'
--   ec_document_type='ORDER_SHIPPED'    erp_document_type='DELIVERY_CHALLAN'
--   ec_document_type='RETURN_APPROVED'  erp_document_type='CREDIT_NOTE'
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_document_mapping
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id     BIGINT NOT NULL
        REFERENCES org_organizations(id),

    ec_document_type    VARCHAR(100),   -- renamed from ecommerce_document
    erp_document_type   VARCHAR(100),   -- renamed from erp_document (matches DocumentType enum)
    auto_create         BOOLEAN DEFAULT TRUE,

    -- Optional: GL accounts override for this mapping
    debit_account_id    BIGINT
        REFERENCES acc_chart_of_accounts(id),
    credit_account_id   BIGINT
        REFERENCES acc_chart_of_accounts(id),

    CONSTRAINT uq_ec_docmap UNIQUE (organization_id, ec_document_type)
);

CREATE INDEX IF NOT EXISTS idx_ec_docmap_org ON ec_document_mapping (organization_id);

-- Seed canonical document mapping (idempotent)
-- These tell EcErpBridgeService what ERP document to create for each ecommerce event
INSERT INTO ec_document_mapping (organization_id, ec_document_type, erp_document_type, auto_create)
SELECT
    o.id,
    event.ec_doc,
    event.erp_doc,
    TRUE
FROM org_organizations o
CROSS JOIN (VALUES
    ('ORDER_CONFIRMED',   'SALES_INVOICE'),
    ('PAYMENT_SUCCESS',   'RECEIPT_VOUCHER'),
    ('ORDER_SHIPPED',     'DELIVERY_CHALLAN'),
    ('RETURN_APPROVED',   'CREDIT_NOTE'),
    ('REFUND_ISSUED',     'PAYMENT_VOUCHER')
) AS event(ec_doc, erp_doc)
ON CONFLICT (organization_id, ec_document_type) DO NOTHING;

-- =============================================================================
-- SCHEDULED JOBS  (cron-style background tasks: daily KPI snapshot, email digest etc.)
-- FIX: added last_result and error_message
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_scheduled_jobs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT
        REFERENCES org_organizations(id),

    job_name        VARCHAR(200),
    cron_expression VARCHAR(100),
    last_run        TIMESTAMP(6),
    next_run        TIMESTAMP(6),
    last_result     VARCHAR(20)     DEFAULT 'PENDING',  -- SUCCESS | FAILED | RUNNING
    error_message   TEXT,
    active          BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_job_org ON ec_scheduled_jobs (organization_id);

-- =============================================================================
-- FEATURE FLAGS  (per-org toggle for storefront features)
-- Examples: 'REVIEWS_ENABLED', 'COD_ENABLED', 'WALLET_ENABLED', 'AFFILIATE_ENABLED'
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_feature_flags
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id BIGINT NOT NULL
        REFERENCES org_organizations(id),

    feature_name    VARCHAR(200),
    enabled         BOOLEAN DEFAULT FALSE,
    notes           VARCHAR(500),

    CONSTRAINT uq_ec_feature UNIQUE (organization_id, feature_name)
);

CREATE INDEX IF NOT EXISTS idx_ec_feature_org ON ec_feature_flags (organization_id);

-- Seed default feature flags (all disabled — must be explicitly enabled per org)
-- Run after organizations are seeded
-- INSERT INTO ec_feature_flags (organization_id, feature_name, enabled)
-- SELECT id, f, FALSE FROM org_organizations
-- CROSS JOIN (VALUES
--     ('REVIEWS_ENABLED'),('COD_ENABLED'),('WALLET_ENABLED'),
--     ('AFFILIATE_ENABLED'),('GIFT_CARD_ENABLED'),('LOYALTY_ENABLED'),
--     ('WISHLIST_CAMPAIGNS_ENABLED'),('MULTI_LANGUAGE_ENABLED')
-- ) AS flags(f)
-- ON CONFLICT (organization_id, feature_name) DO NOTHING;

-- =============================================================================
-- WEBHOOKS  (outbound event webhooks to third-party systems)
-- FIX: added last_triggered_at, failure_count for monitoring
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_webhooks
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    organization_id   BIGINT NOT NULL
        REFERENCES org_organizations(id),

    webhook_name      VARCHAR(200),
    event_name        VARCHAR(100),   -- 'ORDER_PLACED' | 'PAYMENT_SUCCESS' etc.
    target_url        VARCHAR(700),
    secret_key        VARCHAR(500),   -- HMAC signing secret

    last_triggered_at TIMESTAMP(6),
    failure_count     INTEGER DEFAULT 0,
    active            BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_ec_webhook_org ON ec_webhooks (organization_id);

-- =============================================================================
-- ECOMMERCE GL ACCOUNT DEFAULTS
-- Per-organization default GL accounts for ecommerce postings.
-- These are looked up by EcErpBridgeService when no specific mapping override exists.
-- Pattern mirrors hrm_payroll_account_mappings.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ec_gl_account_defaults
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at                  TIMESTAMP(6) DEFAULT NOW(),
    updated_at                  TIMESTAMP(6),
    created_by                  VARCHAR(100),
    updated_by                  VARCHAR(100),

    organization_id             BIGINT NOT NULL
        REFERENCES org_organizations(id)
        CONSTRAINT uq_ec_gl_defaults UNIQUE,

    -- Revenue
    sales_revenue_account_id    BIGINT
        REFERENCES acc_chart_of_accounts(id),

    sales_returns_account_id    BIGINT
        REFERENCES acc_chart_of_accounts(id),

    -- COGS
    cogs_account_id             BIGINT
        REFERENCES acc_chart_of_accounts(id),

    -- Receivable (default AR — overridden by customer erp_sub_account_id)
    accounts_receivable_id      BIGINT
        REFERENCES acc_chart_of_accounts(id),

    -- Tax
    vat_payable_account_id      BIGINT
        REFERENCES acc_chart_of_accounts(id),

    -- Discount expense
    discount_expense_account_id BIGINT
        REFERENCES acc_chart_of_accounts(id),

    -- Shipping income
    shipping_income_account_id  BIGINT
        REFERENCES acc_chart_of_accounts(id),

    -- Default receiving bank/cash (overridden by ec_payments.receiving_sub_account_id)
    default_bank_sub_account_id BIGINT
        REFERENCES acc_chart_of_accounts_sub(id)
);

CREATE INDEX IF NOT EXISTS idx_ec_gl_defaults_org ON ec_gl_account_defaults (organization_id);

-- =============================================================================
-- MODULE REGISTRATION  (register ecommerce module key in sec_org_modules)
-- Allows DynamicAuthorizationManager to check ECOMMERCE module access per org.
-- Run once after organizations are created.
-- =============================================================================

-- INSERT INTO sec_org_modules (organization_id, module_key, active, granted_by, granted_at, notes)
-- SELECT id, 'ECOMMERCE', FALSE, 'SYSTEM', NOW(), 'Ecommerce module — enable per org'
-- FROM org_organizations
-- ON CONFLICT (organization_id, module_key) DO NOTHING;
