-- ============================================================================
-- Spindle ERP — Travel Module (Phase 1: Booking Core + Hotel + Basic Air)
-- Package: com.asg.spindleserp.travel
-- RENUMBER this file to your next available Flyway version before running.
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────
-- MASTER DATA
-- ─────────────────────────────────────────────────────────────────────────

create table trv_hotel_categories
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6),
    created_by    varchar(100),
    updated_at    timestamp(6),
    updated_by    varchar(100),
    category_name varchar(100) not null,
    description   varchar(500)
);

create table trv_hotels
(
    id               bigint generated by default as identity primary key,
    created_at       timestamp(6),
    created_by       varchar(100),
    updated_at       timestamp(6),
    updated_by       varchar(100),
    hotel_code       varchar(30)  not null,
    hotel_name       varchar(200) not null,
    city             varchar(100),
    country          varchar(100),
    address          varchar(500),
    star_rating      integer,
    contact_person   varchar(150),
    contact_phone    varchar(30),
    contact_email    varchar(150),
    is_active        boolean      not null default true,
    organization_id  bigint       not null
        constraint fk_trv_hotel_org references org_organizations,
    category_id      bigint
        constraint fk_trv_hotel_category references trv_hotel_categories,
    constraint uq_trv_hotel_org_code unique (organization_id, hotel_code)
);

create index idx_trv_hotel_org on trv_hotels (organization_id);
create index idx_trv_hotel_category on trv_hotels (category_id);
create index idx_trv_hotel_city on trv_hotels (city);

create table trv_room_types
(
    id             bigint generated by default as identity primary key,
    created_at     timestamp(6),
    created_by     varchar(100),
    updated_at     timestamp(6),
    updated_by     varchar(100),
    room_type_name varchar(150) not null,
    max_occupancy  integer,
    base_price     numeric(18, 2),
    currency       varchar(3),
    is_active      boolean      not null default true,
    hotel_id       bigint       not null
        constraint fk_trv_roomtype_hotel references trv_hotels
);

create index idx_trv_roomtype_hotel on trv_room_types (hotel_id);

create table trv_room_facilities
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6),
    facility_name varchar(150) not null,
    room_type_id  bigint       not null
        constraint fk_trv_facility_roomtype references trv_room_types
);

create index idx_trv_facility_roomtype on trv_room_facilities (room_type_id);

create table trv_meal_plans
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp(6),
    plan_code   varchar(10)  not null unique,
    plan_name   varchar(100) not null,
    description varchar(300)
);

create table trv_airlines
(
    id           bigint generated by default as identity primary key,
    created_at   timestamp(6),
    airline_code varchar(3)   not null unique,
    airline_name varchar(150) not null,
    is_active    boolean      not null default true
);

create table trv_airports
(
    id           bigint generated by default as identity primary key,
    created_at   timestamp(6),
    airport_code varchar(3)   not null unique,
    airport_name varchar(200) not null,
    city         varchar(100),
    country      varchar(100)
);

create table trv_cabin_classes
(
    id         bigint generated by default as identity primary key,
    class_code varchar(10)  not null unique,
    class_name varchar(100) not null
);

-- ─────────────────────────────────────────────────────────────────────────
-- BOOKING CORE
-- ─────────────────────────────────────────────────────────────────────────

create table trv_bookings
(
    id                  bigint generated by default as identity primary key,
    created_at          timestamp(6),
    created_by          varchar(100),
    updated_at          timestamp(6),
    updated_by          varchar(100),
    booking_no          varchar(50)    not null,
    booking_type        varchar(20)    not null
        constraint trv_bookings_type_check
            check (booking_type in ('PACKAGE', 'HOTEL', 'AIR', 'COMBINED')),
    booking_date        date           not null,
    travel_start_date   date,
    travel_end_date     date,
    status              varchar(20)    not null default 'DRAFT'
        constraint trv_bookings_status_check
            check (status in ('DRAFT', 'CONFIRMED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', 'COMPLETED')),
    currency            varchar(3)     not null default 'BDT',
    exchange_rate       numeric(18, 4) not null default 1,
    subtotal_amount     numeric(18, 2) not null default 0,
    discount_amount     numeric(18, 2) not null default 0,
    tax_amount          numeric(18, 2) not null default 0,
    total_amount        numeric(18, 2) not null default 0,
    paid_amount         numeric(18, 2) not null default 0,
    due_amount          numeric(18, 2) not null default 0,
    remarks             varchar(1000),
    organization_id     bigint         not null
        constraint fk_trv_booking_org references org_organizations,
    party_id            bigint
        constraint fk_trv_booking_party references acc_chart_of_accounts_sub,
    lead_id             bigint
        constraint fk_trv_booking_lead references crm_leads,
    opportunity_id      bigint
        constraint fk_trv_booking_opp references crm_opportunities,
    sales_agent_id      bigint
        constraint fk_trv_booking_agent references sec_users,
    approval_request_id bigint
        constraint fk_trv_booking_apr references apr_requests,
    journal_entry_id    bigint
        constraint fk_trv_booking_je references acc_journal_entry_master,
    constraint uq_trv_booking_org_no unique (organization_id, booking_no)
);

create index idx_trv_booking_org on trv_bookings (organization_id);
create index idx_trv_booking_status on trv_bookings (status);
create index idx_trv_booking_party on trv_bookings (party_id);
create index idx_trv_booking_date on trv_bookings (booking_date);
create index idx_trv_booking_agent on trv_bookings (sales_agent_id);

create table trv_booking_services
(
    id              bigint generated by default as identity primary key,
    created_at      timestamp(6),
    created_by      varchar(100),
    updated_at      timestamp(6),
    updated_by      varchar(100),
    service_type    varchar(20)    not null
        constraint trv_bookingsvc_type_check
            check (service_type in ('HOTEL', 'AIR', 'PACKAGE')),
    reference_id    bigint,
    description     varchar(500),
    quantity        numeric(12, 3) not null default 1,
    unit_cost       numeric(18, 2) not null default 0,
    unit_price      numeric(18, 2) not null default 0,
    discount_amount numeric(18, 2) not null default 0,
    tax_amount      numeric(18, 2) not null default 0,
    line_total      numeric(18, 2) not null default 0,
    booking_id      bigint         not null
        constraint fk_trv_bsvc_booking references trv_bookings on delete cascade,
    cost_center_id  bigint
        constraint fk_trv_bsvc_cc references org_cost_centers
);

create index idx_trv_bsvc_booking on trv_booking_services (booking_id);
create index idx_trv_bsvc_type on trv_booking_services (service_type);

create table trv_passengers
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp(6),
    created_by        varchar(100),
    updated_at        timestamp(6),
    updated_by        varchar(100),
    title             varchar(10),
    first_name        varchar(100) not null,
    last_name         varchar(100),
    date_of_birth     date,
    gender            varchar(10)
        constraint trv_passenger_gender_check check (gender in ('MALE', 'FEMALE', 'OTHER')),
    passport_number   varchar(50),
    passport_expiry   date,
    nationality       varchar(100),
    passenger_type    varchar(10)  not null default 'ADULT'
        constraint trv_passenger_type_check check (passenger_type in ('ADULT', 'CHILD', 'INFANT')),
    is_lead_passenger boolean      not null default false,
    phone             varchar(30),
    email             varchar(150),
    remarks           varchar(500),
    booking_id        bigint       not null
        constraint fk_trv_pax_booking references trv_bookings on delete cascade
);

create index idx_trv_pax_booking on trv_passengers (booking_id);

create table trv_passenger_preferences
(
    id                  bigint generated by default as identity primary key,
    meal_preference     varchar(100),
    seat_preference     varchar(100),
    special_assistance  varchar(300),
    dietary_restriction varchar(300),
    remarks             varchar(500),
    passenger_id        bigint not null unique
        constraint fk_trv_paxpref_pax references trv_passengers on delete cascade
);

-- ─────────────────────────────────────────────────────────────────────────
-- HOTEL BOOKINGS
-- ─────────────────────────────────────────────────────────────────────────

create table trv_hotel_bookings
(
    id                  bigint generated by default as identity primary key,
    created_at          timestamp(6),
    created_by          varchar(100),
    updated_at          timestamp(6),
    updated_by          varchar(100),
    check_in_date       date           not null,
    check_out_date      date           not null,
    nights              integer,
    rooms_count         integer        not null default 1,
    adults              integer        not null default 1,
    children            integer        not null default 0,
    rate_per_night      numeric(18, 2),
    total_amount        numeric(18, 2) not null default 0,
    confirmation_number varchar(100),
    supplier_reference  varchar(100),
    status              varchar(20)    not null default 'PENDING'
        constraint trv_hotelbooking_status_check
            check (status in ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    booking_service_id  bigint         not null
        constraint fk_trv_hb_bsvc references trv_booking_services on delete cascade,
    hotel_id            bigint         not null
        constraint fk_trv_hb_hotel references trv_hotels,
    room_type_id         bigint
        constraint fk_trv_hb_roomtype references trv_room_types,
    meal_plan_id        bigint
        constraint fk_trv_hb_mealplan references trv_meal_plans
);

create index idx_trv_hb_bsvc on trv_hotel_bookings (booking_service_id);
create index idx_trv_hb_hotel on trv_hotel_bookings (hotel_id);
create index idx_trv_hb_status on trv_hotel_bookings (status);
create index idx_trv_hb_dates on trv_hotel_bookings (check_in_date, check_out_date);

create table trv_hotel_rooms
(
    id                bigint generated by default as identity primary key,
    room_number        varchar(30),
    room_type_snapshot varchar(150),
    hotel_booking_id  bigint not null
        constraint fk_trv_hr_hb references trv_hotel_bookings on delete cascade
);

create index idx_trv_hr_hb on trv_hotel_rooms (hotel_booking_id);

create table trv_hotel_guests
(
    id               bigint generated by default as identity primary key,
    hotel_booking_id bigint not null
        constraint fk_trv_hg_hb references trv_hotel_bookings on delete cascade,
    passenger_id     bigint not null
        constraint fk_trv_hg_pax references trv_passengers,
    room_id          bigint
        constraint fk_trv_hg_room references trv_hotel_rooms
);

create index idx_trv_hg_hb on trv_hotel_guests (hotel_booking_id);
create index idx_trv_hg_pax on trv_hotel_guests (passenger_id);

create table trv_hotel_cancellations
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp(6),
    created_by        varchar(100),
    cancellation_date date           not null,
    reason            varchar(500),
    penalty_amount    numeric(18, 2) not null default 0,
    refund_amount     numeric(18, 2) not null default 0,
    status            varchar(20)    not null default 'REQUESTED'
        constraint trv_hotelcxl_status_check
            check (status in ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED')),
    hotel_booking_id  bigint         not null
        constraint fk_trv_hc_hb references trv_hotel_bookings
);

create index idx_trv_hc_hb on trv_hotel_cancellations (hotel_booking_id);

-- ─────────────────────────────────────────────────────────────────────────
-- AIR TICKETING (manual/offline — no GDS integration in Phase 1)
-- ─────────────────────────────────────────────────────────────────────────

create table trv_air_tickets
(
    id                     bigint generated by default as identity primary key,
    created_at             timestamp(6),
    created_by             varchar(100),
    updated_at             timestamp(6),
    updated_by             varchar(100),
    pnr                    varchar(20),
    departure_date         date,
    departure_time         time(0),
    arrival_date           date,
    arrival_time           time(0),
    fare_amount            numeric(18, 2) not null default 0,
    tax_amount             numeric(18, 2) not null default 0,
    total_amount           numeric(18, 2) not null default 0,
    supplier_reference     varchar(100),
    status                 varchar(20)    not null default 'ISSUED'
        constraint trv_airticket_status_check
            check (status in ('ISSUED', 'CANCELLED', 'REFUNDED')),
    booking_service_id     bigint         not null
        constraint fk_trv_at_bsvc references trv_booking_services on delete cascade,
    airline_id             bigint
        constraint fk_trv_at_airline references trv_airlines,
    origin_airport_id      bigint
        constraint fk_trv_at_origin references trv_airports,
    destination_airport_id bigint
        constraint fk_trv_at_dest references trv_airports,
    cabin_class_id         bigint
        constraint fk_trv_at_cabin references trv_cabin_classes
);

create index idx_trv_at_bsvc on trv_air_tickets (booking_service_id);
create index idx_trv_at_status on trv_air_tickets (status);
create index idx_trv_at_departure on trv_air_tickets (departure_date);

create table trv_passenger_tickets
(
    id                bigint generated by default as identity primary key,
    ticket_number     varchar(50),
    seat_number       varchar(20),
    baggage_allowance varchar(100),
    status            varchar(20) not null default 'ISSUED'
        constraint trv_paxticket_status_check
            check (status in ('ISSUED', 'CANCELLED', 'REFUNDED')),
    air_ticket_id     bigint      not null
        constraint fk_trv_pt_at references trv_air_tickets on delete cascade,
    passenger_id      bigint      not null
        constraint fk_trv_pt_pax references trv_passengers
);

create index idx_trv_pt_at on trv_passenger_tickets (air_ticket_id);
create index idx_trv_pt_pax on trv_passenger_tickets (passenger_id);

-- ─────────────────────────────────────────────────────────────────────────
-- OPERATIONS
-- ─────────────────────────────────────────────────────────────────────────

create table trv_booking_notes
(
    id         bigint generated by default as identity primary key,
    created_at timestamp(6),
    created_by varchar(100),
    note_text  text        not null,
    note_type  varchar(20) not null default 'INTERNAL'
        constraint trv_note_type_check check (note_type in ('INTERNAL', 'CUSTOMER')),
    booking_id bigint      not null
        constraint fk_trv_note_booking references trv_bookings on delete cascade
);

create index idx_trv_note_booking on trv_booking_notes (booking_id);

create table trv_booking_status_history
(
    id         bigint generated by default as identity primary key,
    status     varchar(20) not null,
    changed_by varchar(100),
    changed_at timestamp(6),
    remarks    varchar(500),
    booking_id bigint      not null
        constraint fk_trv_hist_booking references trv_bookings on delete cascade
);

create index idx_trv_hist_booking on trv_booking_status_history (booking_id);

create table trv_supplier_costs
(
    id                  bigint generated by default as identity primary key,
    created_at          timestamp(6),
    created_by          varchar(100),
    updated_at          timestamp(6),
    updated_by          varchar(100),
    cost_amount         numeric(18, 2) not null default 0,
    currency            varchar(3)     not null default 'BDT',
    payment_status      varchar(20)    not null default 'UNPAID'
        constraint trv_suppliercost_status_check
            check (payment_status in ('UNPAID', 'PARTIAL', 'PAID')),
    invoice_reference   varchar(100),
    booking_service_id  bigint         not null
        constraint fk_trv_sc_bsvc references trv_booking_services on delete cascade,
    supplier_id         bigint
        constraint fk_trv_sc_supplier references acc_chart_of_accounts_sub
);

create index idx_trv_sc_bsvc on trv_supplier_costs (booking_service_id);
create index idx_trv_sc_supplier on trv_supplier_costs (supplier_id);
create index idx_trv_sc_status on trv_supplier_costs (payment_status);

-- ─────────────────────────────────────────────────────────────────────────
-- GL BRIDGE / INTEGRATION CONFIG (singleton-per-org, no DataTable — mirrors ec_gl_account_defaults)
-- ─────────────────────────────────────────────────────────────────────────

create table trv_gl_account_defaults
(
    id                        bigint generated by default as identity primary key,
    created_at                timestamp(6),
    created_by                varchar(100),
    updated_at                timestamp(6),
    updated_by                varchar(100),
    organization_id           bigint not null
        constraint fk_trv_gldef_org references org_organizations,
    accounts_receivable_id    bigint
        constraint fk_trv_gldef_ar references acc_chart_of_accounts,
    travel_revenue_account_id bigint
        constraint fk_trv_gldef_rev references acc_chart_of_accounts,
    cost_of_service_account_id bigint
        constraint fk_trv_gldef_cos references acc_chart_of_accounts,
    supplier_payable_default_id bigint
        constraint fk_trv_gldef_payable references acc_chart_of_accounts,
    constraint uq_trv_gldef_org unique (organization_id)
);

create table trv_document_mapping
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp(6),
    created_by        varchar(100),
    updated_at        timestamp(6),
    updated_by        varchar(100),
    auto_create       boolean     not null default false,
    trv_document_type varchar(50) not null,
    erp_document_type varchar(50),
    organization_id   bigint      not null
        constraint fk_trv_docmap_org references org_organizations,
    debit_account_id  bigint
        constraint fk_trv_docmap_debit references acc_chart_of_accounts,
    credit_account_id bigint
        constraint fk_trv_docmap_credit references acc_chart_of_accounts,
    constraint uq_trv_docmap unique (organization_id, trv_document_type)
);
