-- ============================================================================
-- Spindle ERP — Travel Module Phase 2: Packages, Visa, Tours
-- RENUMBER this file to run immediately after your Phase 1 travel migrations.
-- ============================================================================

-- Extend trv_booking_services.service_type to accept PACKAGE bookings' new
-- siblings TOUR and VISA (PACKAGE itself already existed in Phase 1).
alter table trv_booking_services drop constraint trv_bookingsvc_type_check;
alter table trv_booking_services add constraint trv_bookingsvc_type_check
    check (service_type in ('HOTEL', 'AIR', 'PACKAGE', 'TOUR', 'VISA'));

-- ─────────────────────────────────────────────────────────────────────────
-- PACKAGES  (pre-built bundled itineraries — hotel + air + tours priced as one)
-- ─────────────────────────────────────────────────────────────────────────

create table trv_packages
(
    id               bigint generated by default as identity primary key,
    created_at       timestamp(6),
    created_by       varchar(100),
    updated_at       timestamp(6),
    updated_by       varchar(100),
    package_code     varchar(30)    not null,
    package_name     varchar(200)   not null,
    destination      varchar(150),
    category         varchar(50),
    duration_days    integer,
    duration_nights  integer,
    base_price       numeric(18, 2) not null default 0,
    currency         varchar(3)     not null default 'BDT',
    description      varchar(2000),
    is_active        boolean        not null default true,
    organization_id  bigint         not null
        constraint fk_trv_pkg_org references org_organizations,
    constraint uq_trv_pkg_org_code unique (organization_id, package_code)
);

create index idx_trv_pkg_org on trv_packages (organization_id);
create index idx_trv_pkg_destination on trv_packages (destination);

create table trv_package_itinerary_days
(
    id          bigint generated by default as identity primary key,
    day_number  integer      not null,
    title       varchar(200),
    description varchar(1000),
    package_id  bigint       not null
        constraint fk_trv_pkgday_pkg references trv_packages on delete cascade
);

create index idx_trv_pkgday_pkg on trv_package_itinerary_days (package_id);

create table trv_package_inclusions
(
    id              bigint generated by default as identity primary key,
    inclusion_type  varchar(10)  not null default 'INCLUDED'
        constraint trv_pkgincl_type_check check (inclusion_type in ('INCLUDED', 'EXCLUDED')),
    description     varchar(300) not null,
    package_id      bigint       not null
        constraint fk_trv_pkgincl_pkg references trv_packages on delete cascade
);

create index idx_trv_pkgincl_pkg on trv_package_inclusions (package_id);

create table trv_package_bookings
(
    id                  bigint generated by default as identity primary key,
    created_at          timestamp(6),
    created_by          varchar(100),
    updated_at          timestamp(6),
    updated_by          varchar(100),
    travel_date         date,
    pax_count           integer        not null default 1,
    total_amount        numeric(18, 2) not null default 0,
    confirmation_number varchar(100),
    supplier_reference  varchar(100),
    status              varchar(20)    not null default 'PENDING'
        constraint trv_pkgbooking_status_check
            check (status in ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    booking_service_id  bigint         not null
        constraint fk_trv_pkgbk_bsvc references trv_booking_services on delete cascade,
    package_id          bigint         not null
        constraint fk_trv_pkgbk_pkg references trv_packages
);

create index idx_trv_pkgbk_bsvc on trv_package_bookings (booking_service_id);
create index idx_trv_pkgbk_pkg on trv_package_bookings (package_id);

-- ─────────────────────────────────────────────────────────────────────────
-- VISA
-- ─────────────────────────────────────────────────────────────────────────

create table trv_visa_types
(
    id               bigint generated by default as identity primary key,
    country          varchar(100)   not null,
    visa_category    varchar(100)   not null,
    processing_days  integer,
    fee_amount       numeric(18, 2) not null default 0,
    currency         varchar(3)     not null default 'BDT',
    description      varchar(500)
);

create index idx_trv_visatype_country on trv_visa_types (country);

create table trv_visa_applications
(
    id                   bigint generated by default as identity primary key,
    created_at           timestamp(6),
    created_by           varchar(100),
    updated_at           timestamp(6),
    updated_by           varchar(100),
    application_number   varchar(100),
    submission_date      date,
    expected_date        date,
    approval_date        date,
    status               varchar(20)    not null default 'PENDING'
        constraint trv_visaapp_status_check
            check (status in ('PENDING', 'SUBMITTED', 'APPROVED', 'REJECTED', 'COLLECTED')),
    fee_amount           numeric(18, 2) not null default 0,
    remarks              varchar(1000),
    booking_service_id   bigint         not null
        constraint fk_trv_visaapp_bsvc references trv_booking_services on delete cascade,
    passenger_id         bigint         not null
        constraint fk_trv_visaapp_pax references trv_passengers,
    visa_type_id         bigint         not null
        constraint fk_trv_visaapp_type references trv_visa_types
);

create index idx_trv_visaapp_bsvc on trv_visa_applications (booking_service_id);
create index idx_trv_visaapp_pax on trv_visa_applications (passenger_id);
create index idx_trv_visaapp_status on trv_visa_applications (status);

create table trv_visa_documents
(
    id                   bigint generated by default as identity primary key,
    document_name        varchar(150) not null,
    is_received          boolean      not null default false,
    remarks              varchar(300),
    visa_application_id  bigint       not null
        constraint fk_trv_visadoc_app references trv_visa_applications on delete cascade
);

create index idx_trv_visadoc_app on trv_visa_documents (visa_application_id);

-- ─────────────────────────────────────────────────────────────────────────
-- TOURS  (day-trips / excursions, distinct from multi-day Packages)
-- ─────────────────────────────────────────────────────────────────────────

create table trv_tour_guides
(
    id          bigint generated by default as identity primary key,
    guide_name  varchar(150) not null,
    phone       varchar(30),
    email       varchar(150),
    languages   varchar(200),
    is_active   boolean      not null default true
);

create table trv_tours
(
    id               bigint generated by default as identity primary key,
    created_at       timestamp(6),
    created_by       varchar(100),
    updated_at       timestamp(6),
    updated_by       varchar(100),
    tour_code        varchar(30)    not null,
    tour_name        varchar(200)   not null,
    destination      varchar(150),
    duration_hours   numeric(6, 2),
    base_price       numeric(18, 2) not null default 0,
    currency         varchar(3)     not null default 'BDT',
    description      varchar(1000),
    is_active        boolean        not null default true,
    organization_id  bigint         not null
        constraint fk_trv_tour_org references org_organizations,
    constraint uq_trv_tour_org_code unique (organization_id, tour_code)
);

create index idx_trv_tour_org on trv_tours (organization_id);

create table trv_tour_bookings
(
    id                   bigint generated by default as identity primary key,
    created_at           timestamp(6),
    created_by           varchar(100),
    updated_at           timestamp(6),
    updated_by           varchar(100),
    tour_date            date,
    pax_count            integer        not null default 1,
    total_amount         numeric(18, 2) not null default 0,
    confirmation_number  varchar(100),
    status               varchar(20)    not null default 'PENDING'
        constraint trv_tourbooking_status_check
            check (status in ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    booking_service_id   bigint         not null
        constraint fk_trv_tourbk_bsvc references trv_booking_services on delete cascade,
    tour_id              bigint         not null
        constraint fk_trv_tourbk_tour references trv_tours,
    guide_id             bigint
        constraint fk_trv_tourbk_guide references trv_tour_guides
);

create index idx_trv_tourbk_bsvc on trv_tour_bookings (booking_service_id);
create index idx_trv_tourbk_tour on trv_tour_bookings (tour_id);
