-- =============================================================================
--  Spindle ERP  —  Booking Receipts Table
--  File   : V21__add_booking_receipts.sql
--  Target : PostgreSQL 15+
--  Depends on: V20__seed_travel_transactions.sql (trv_bookings exists)
--
--  Stores receipt/payment lines directly on a booking so the system can
--  auto-create RECEIPT_VOUCHER entries on confirm and track payment status
--  (PARTIALLY_PAID / PAID / DUE) without a separate voucher screen.
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS trv_booking_receipts
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6),
    created_by          varchar(100),
    updated_at          timestamp(6),
    updated_by          varchar(100),

    booking_id          bigint       not null
        constraint fk_rcpt_booking
            references trv_bookings
            on delete cascade,

    payment_mode        varchar(20)  not null  -- CASH | BANK | BKASH | NAGAD | CARD
        constraint trv_booking_receipts_payment_mode_check
            check (payment_mode IN ('CASH','BANK','BKASH','NAGAD','CARD')),

    sub_account_id      bigint
        constraint fk_rcpt_sub_account
            references acc_chart_of_accounts_sub,

    reference           varchar(100),          -- transaction ID / cheque no / ref

    amount              numeric(18, 2) not null
        constraint trv_booking_receipts_amount_check
            check (amount > 0),

    organization_id     bigint       not null
        constraint fk_rcpt_org
            references org_organizations
);

CREATE INDEX IF NOT EXISTS idx_rcpt_booking    ON trv_booking_receipts (booking_id);
CREATE INDEX IF NOT EXISTS idx_rcpt_org        ON trv_booking_receipts (organization_id);

ALTER TABLE trv_booking_receipts OWNER TO postgres;

COMMIT;
