-- Payment mode → GL account mapping.
-- Auto-created by Hibernate ddl-auto=update via @Entity.
-- Run manually only if needed.
CREATE TABLE IF NOT EXISTS trv_payment_mode_accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT      NOT NULL,
    payment_mode    VARCHAR(20) NOT NULL,   -- CASH | BANK | BKASH | NAGAD | CARD
    sub_account_id  BIGINT,                 -- FK → acc_chart_of_accounts_sub.id
    CONSTRAINT uq_trv_paymode_org UNIQUE (organization_id, payment_mode)
);
