-- ============================================================
-- E-Commerce Schema (ec_*) - Complete PostgreSQL Schema
-- ============================================================
-- Pattern: bigint generated by default as identity for PKs
-- Pattern: timestamp(6) for timestamps
-- Pattern: CHECK ((column)::text = ANY (ARRAY['VAL1'::character varying, ...]))
-- Pattern: Named constraint syntax for FKs
-- Pattern: ALTER TABLE ... OWNER TO postgres after each table
-- Pattern: CREATE INDEX after each table
-- ============================================================

-- ============================================================
-- GROUP 1: Language & Tags (No FK Dependencies)
-- ============================================================

CREATE TABLE ec_languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    default_language BOOLEAN NOT NULL,
    language_code VARCHAR(20) NOT NULL,
    language_name VARCHAR(100),
    native_name VARCHAR(100),
    rtl BOOLEAN NOT NULL,
    CONSTRAINT uq_ec_language UNIQUE (language_code)
);
ALTER TABLE ec_languages OWNER TO postgres;

CREATE TABLE ec_product_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    slug VARCHAR(120) NOT NULL,
    tag_name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_ec_tag UNIQUE (organization_id, slug)
);
ALTER TABLE ec_product_tags OWNER TO postgres;

CREATE TABLE ec_scheduled_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    cron_expression VARCHAR(100),
    error_message TEXT,
    job_name VARCHAR(200),
    last_result VARCHAR(20),
    last_run TIMESTAMP(6),
    next_run TIMESTAMP(6),
    organization_id BIGINT
);
ALTER TABLE ec_scheduled_jobs OWNER TO postgres;
CREATE INDEX idx_ec_job_org ON ec_scheduled_jobs(organization_id);

-- ============================================================
-- GROUP 2: Categories
-- ============================================================

CREATE TABLE ec_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    banner_url VARCHAR(700),
    category_code VARCHAR(50) NOT NULL,
    category_name VARCHAR(200) NOT NULL,
    deleted BOOLEAN NOT NULL,
    description TEXT,
    display_order INTEGER,
    icon VARCHAR(100),
    image_url VARCHAR(700),
    is_featured BOOLEAN NOT NULL,
    is_menu BOOLEAN NOT NULL,
    level_no INTEGER,
    meta_description VARCHAR(1000),
    meta_keywords VARCHAR(500),
    meta_title VARCHAR(255),
    short_description VARCHAR(500),
    slug VARCHAR(250) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    parent_category_id BIGINT REFERENCES ec_categories(id),
    CONSTRAINT uq_ec_cat_code UNIQUE (organization_id, category_code),
    CONSTRAINT uq_ec_cat_slug UNIQUE (organization_id, slug)
);
ALTER TABLE ec_categories OWNER TO postgres;
CREATE INDEX idx_ec_cat_org ON ec_categories(organization_id);
CREATE INDEX idx_ec_cat_parent ON ec_categories(parent_category_id);
CREATE INDEX idx_ec_cat_slug ON ec_categories(slug);
CREATE INDEX idx_ec_cat_active ON ec_categories(active);
CREATE INDEX idx_ec_cat_featured ON ec_categories(is_featured);

CREATE TABLE ec_category_attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    attribute_label VARCHAR(150),
    attribute_name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP(6),
    data_type VARCHAR(30) NOT NULL,
    display_order INTEGER,
    filterable BOOLEAN NOT NULL,
    is_required BOOLEAN NOT NULL,
    searchable BOOLEAN NOT NULL,
    sortable BOOLEAN NOT NULL,
    updated_at TIMESTAMP(6),
    category_id BIGINT NOT NULL REFERENCES ec_categories(id),
    CONSTRAINT chk_ec_catattr_datatype CHECK ((data_type)::text = ANY (ARRAY['TEXT'::character varying, 'NUMBER'::character varying, 'BOOLEAN'::character varying, 'DATE'::character varying, 'LIST'::character varying, 'COLOR'::character varying]))
);
ALTER TABLE ec_category_attributes OWNER TO postgres;
CREATE INDEX idx_ec_catattr_cat ON ec_category_attributes(category_id);

-- ============================================================
-- GROUP 3: Product Catalog
-- ============================================================

CREATE TABLE ec_product_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    best_seller BOOLEAN NOT NULL,
    deleted BOOLEAN NOT NULL,
    description TEXT,
    featured BOOLEAN NOT NULL,
    maximum_order_qty NUMERIC(12,2),
    minimum_order_qty NUMERIC(12,2),
    new_arrival BOOLEAN NOT NULL,
    product_title VARCHAR(300) NOT NULL,
    publish_date TIMESTAMP(6),
    published BOOLEAN NOT NULL,
    recommended BOOLEAN NOT NULL,
    return_policy TEXT,
    seo_description VARCHAR(1000),
    seo_keywords VARCHAR(500),
    seo_title VARCHAR(255),
    shipping_information TEXT,
    short_description VARCHAR(1000),
    slug VARCHAR(250) NOT NULL,
    trending BOOLEAN NOT NULL,
    warranty_information VARCHAR(500),
    youtube_video VARCHAR(500),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    category_id BIGINT REFERENCES ec_categories(id),
    item_id BIGINT NOT NULL REFERENCES inv_items(id),
    CONSTRAINT uq_ec_prod_slug UNIQUE (organization_id, slug),
    CONSTRAINT uq_ec_prod_item UNIQUE (organization_id, item_id)
);
ALTER TABLE ec_product_catalog OWNER TO postgres;
CREATE INDEX idx_ec_prod_org ON ec_product_catalog(organization_id);
CREATE INDEX idx_ec_prod_item ON ec_product_catalog(item_id);
CREATE INDEX idx_ec_prod_cat ON ec_product_catalog(category_id);
CREATE INDEX idx_ec_prod_slug ON ec_product_catalog(slug);
CREATE INDEX idx_ec_prod_featured ON ec_product_catalog(featured);
CREATE INDEX idx_ec_prod_best ON ec_product_catalog(best_seller);
CREATE INDEX idx_ec_prod_trending ON ec_product_catalog(trending);
CREATE INDEX idx_ec_prod_pub ON ec_product_catalog(published, publish_date);
CREATE INDEX idx_ec_prod_active ON ec_product_catalog(active, deleted);

CREATE TABLE ec_product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN,
    alt_text VARCHAR(500),
    created_at TIMESTAMP(6),
    created_by BIGINT,
    display_order INTEGER,
    image_url VARCHAR(700) NOT NULL,
    is_primary BOOLEAN NOT NULL,
    thumbnail_url VARCHAR(700),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id)
);
ALTER TABLE ec_product_images OWNER TO postgres;
CREATE INDEX idx_ec_prodimg_prod ON ec_product_images(product_id);

CREATE TABLE ec_product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    color VARCHAR(100),
    compare_price NUMERIC(18,2),
    created_at TIMESTAMP(6),
    created_by BIGINT,
    deleted BOOLEAN NOT NULL,
    height_override NUMERIC(12,3),
    length_override NUMERIC(12,3),
    selling_price NUMERIC(18,2),
    size_name VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    variant_code VARCHAR(50),
    variant_name VARCHAR(200),
    weight_override NUMERIC(12,3),
    width_override NUMERIC(12,3),
    item_id BIGINT NOT NULL REFERENCES inv_items(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    CONSTRAINT uq_ec_variant_item UNIQUE (product_id, item_id)
);
ALTER TABLE ec_product_variants OWNER TO postgres;
CREATE INDEX idx_ec_variant_prod ON ec_product_variants(product_id);
CREATE INDEX idx_ec_variant_item ON ec_product_variants(item_id);
CREATE INDEX idx_ec_variant_active ON ec_product_variants(active);

CREATE TABLE ec_product_attribute_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_value TEXT,
    category_attribute_id BIGINT NOT NULL REFERENCES ec_category_attributes(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    CONSTRAINT uq_ec_prodattr UNIQUE (product_id, category_attribute_id)
);
ALTER TABLE ec_product_attribute_values OWNER TO postgres;
CREATE INDEX idx_ec_prodattr_prod ON ec_product_attribute_values(product_id);

CREATE TABLE ec_product_tag_map (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    tag_id BIGINT NOT NULL REFERENCES ec_product_tags(id),
    CONSTRAINT uq_ec_prod_tag UNIQUE (product_id, tag_id)
);
ALTER TABLE ec_product_tag_map OWNER TO postgres;
CREATE INDEX idx_ec_prodtag_prod ON ec_product_tag_map(product_id);

CREATE TABLE ec_product_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analytics_date DATE NOT NULL,
    cart_additions INTEGER NOT NULL,
    conversion_rate NUMERIC(8,2),
    product_views INTEGER NOT NULL,
    purchases INTEGER NOT NULL,
    returns INTEGER NOT NULL,
    revenue NUMERIC(18,2),
    wishlist_count INTEGER NOT NULL,
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    CONSTRAINT uq_ec_prodana UNIQUE (product_id, analytics_date)
);
ALTER TABLE ec_product_analytics OWNER TO postgres;
CREATE INDEX idx_ec_prodana_prod ON ec_product_analytics(product_id);
CREATE INDEX idx_ec_prodana_date ON ec_product_analytics(analytics_date);

CREATE TABLE ec_review_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    average_rating NUMERIC(3,2),
    rating1 INTEGER NOT NULL,
    rating2 INTEGER NOT NULL,
    rating3 INTEGER NOT NULL,
    rating4 INTEGER NOT NULL,
    rating5 INTEGER NOT NULL,
    recommendation_pct NUMERIC(5,2),
    total_reviews INTEGER NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    product_id BIGINT NOT NULL UNIQUE REFERENCES ec_product_catalog(id)
);
ALTER TABLE ec_review_summary OWNER TO postgres;
CREATE INDEX idx_ec_reviewsum_prod ON ec_review_summary(product_id);
CREATE INDEX idx_ec_reviewsum_org ON ec_review_summary(organization_id);

-- ============================================================
-- GROUP 4: Customers & Customer Sub-Entities
-- ============================================================

CREATE TABLE ec_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT REFERENCES sec_users(id),
    updated_at TIMESTAMP(6),
    updated_by BIGINT REFERENCES sec_users(id),
    active BOOLEAN NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    email VARCHAR(200),
    phone VARCHAR(50),
    mobile VARCHAR(50),
    gstin VARCHAR(50),
    pan VARCHAR(50),
    credit_limit NUMERIC(18,2),
    opening_balance NUMERIC(18,2),
    currency_code VARCHAR(10),
    exchange_rate NUMERIC(12,6),
    loyalty_points INTEGER DEFAULT 0,
    notes TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    account_id BIGINT REFERENCES acc_chart_of_accounts_sub(id),
    user_id BIGINT REFERENCES sec_users(id),
    CONSTRAINT uq_ec_cust_code UNIQUE (organization_id, customer_code),
    CONSTRAINT uq_ec_cust_email UNIQUE (organization_id, email)
);
ALTER TABLE ec_customers OWNER TO postgres;
CREATE INDEX idx_ec_cust_org ON ec_customers(organization_id);
CREATE INDEX idx_ec_cust_email ON ec_customers(email);
CREATE INDEX idx_ec_cust_account ON ec_customers(account_id);
CREATE INDEX idx_ec_cust_user ON ec_customers(user_id);

CREATE TABLE ec_customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    address_type VARCHAR(20) NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    is_default BOOLEAN NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    CONSTRAINT chk_ec_custaddr_type CHECK ((address_type)::text = ANY (ARRAY['BILLING'::character varying, 'SHIPPING'::character varying, 'BOTH'::character varying]))
);
ALTER TABLE ec_customer_addresses OWNER TO postgres;
CREATE INDEX idx_ec_custaddr_cust ON ec_customer_addresses(customer_id);
CREATE INDEX idx_ec_custaddr_type ON ec_customer_addresses(address_type);

CREATE TABLE ec_customer_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    device_token VARCHAR(500),
    device_type VARCHAR(50),
    last_login TIMESTAMP(6),
    platform VARCHAR(50),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id)
);
ALTER TABLE ec_customer_devices OWNER TO postgres;
CREATE INDEX idx_ec_custdev_cust ON ec_customer_devices(customer_id);

CREATE TABLE ec_customer_login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_time TIMESTAMP(6),
    ip_address VARCHAR(50),
    user_agent TEXT,
    device_info VARCHAR(255),
    login_status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(255),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    CONSTRAINT chk_ec_custlog_status CHECK ((login_status)::text = ANY (ARRAY['SUCCESS'::character varying, 'FAILURE'::character varying, 'LOCKED'::character varying]))
);
ALTER TABLE ec_customer_login_history OWNER TO postgres;
CREATE INDEX idx_ec_custlog_cust ON ec_customer_login_history(customer_id);

CREATE TABLE ec_customer_otp (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    expires_at TIMESTAMP(6) NOT NULL,
    otp_code VARCHAR(10) NOT NULL,
    otp_type VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP(6),
    verified BOOLEAN NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    CONSTRAINT chk_ec_custotp_type CHECK ((otp_type)::text = ANY (ARRAY['LOGIN'::character varying, 'REGISTRATION'::character varying, 'PASSWORD_RESET'::character varying, 'ORDER_CONFIRMATION'::character varying]))
);
ALTER TABLE ec_customer_otp OWNER TO postgres;
CREATE INDEX idx_ec_custotp_cust ON ec_customer_otp(customer_id);

CREATE TABLE ec_customer_wallet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance NUMERIC(18,2) NOT NULL,
    created_at TIMESTAMP(6),
    currency_code VARCHAR(10),
    last_transaction_date TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    customer_id BIGINT NOT NULL UNIQUE REFERENCES ec_customers(id)
);
ALTER TABLE ec_customer_wallet OWNER TO postgres;
CREATE INDEX idx_ec_custwal_cust ON ec_customer_wallet(customer_id);

-- ============================================================
-- GROUP 5: Cart
-- ============================================================

CREATE TABLE ec_cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    session_id VARCHAR(200),
    subtotal NUMERIC(18,2),
    tax_amount NUMERIC(18,2),
    discount_amount NUMERIC(18,2),
    total_amount NUMERIC(18,2),
    coupon_code VARCHAR(50),
    notes TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT REFERENCES ec_customers(id)
);
ALTER TABLE ec_cart OWNER TO postgres;
CREATE INDEX idx_ec_cart_org ON ec_cart(organization_id);
CREATE INDEX idx_ec_cart_cust ON ec_cart(customer_id);
CREATE INDEX idx_ec_cart_session ON ec_cart(session_id);

CREATE TABLE ec_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    discount_amount NUMERIC(18,2),
    quantity INTEGER NOT NULL,
    tax_amount NUMERIC(18,2),
    total_price NUMERIC(18,2),
    unit_price NUMERIC(18,2) NOT NULL,
    cart_id BIGINT NOT NULL REFERENCES ec_cart(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    variant_id BIGINT REFERENCES ec_product_variants(id)
);
ALTER TABLE ec_cart_items OWNER TO postgres;
CREATE INDEX idx_ec_cartitem_cart ON ec_cart_items(cart_id);
CREATE INDEX idx_ec_cartitem_prod ON ec_cart_items(product_id);
CREATE INDEX idx_ec_cartitem_var ON ec_cart_items(variant_id);

-- ============================================================
-- GROUP 6: Orders
-- ============================================================

CREATE TABLE ec_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    order_number VARCHAR(50) NOT NULL,
    order_date TIMESTAMP(6) NOT NULL,
    subtotal NUMERIC(18,2) NOT NULL,
    tax_amount NUMERIC(18,2),
    discount_amount NUMERIC(18,2),
    shipping_charge NUMERIC(18,2),
    total_amount NUMERIC(18,2) NOT NULL,
    paid_amount NUMERIC(18,2),
    balance_amount NUMERIC(18,2),
    order_status VARCHAR(30) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    shipping_status VARCHAR(30),
    currency_code VARCHAR(10),
    exchange_rate NUMERIC(12,6),
    notes TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    journal_entry_id BIGINT REFERENCES acc_journal_entry_master(id),
    coupon_id BIGINT REFERENCES ec_coupon(id),
    shipping_method_id BIGINT REFERENCES ec_shipping_methods(id),
    CONSTRAINT uq_ec_order_number UNIQUE (organization_id, order_number),
    CONSTRAINT chk_ec_orders_status CHECK ((order_status)::text = ANY (ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'RETURNED'::character varying, 'REFUNDED'::character varying])),
    CONSTRAINT chk_ec_orders_paystatus CHECK ((payment_status)::text = ANY (ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'PARTIALLY_REFUNDED'::character varying])),
    CONSTRAINT chk_ec_orders_shpstatus CHECK ((shipping_status)::text = ANY (ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'FAILED'::character varying, 'RETURNED'::character varying]))
);
ALTER TABLE ec_orders OWNER TO postgres;
CREATE INDEX idx_ec_orders_org ON ec_orders(organization_id);
CREATE INDEX idx_ec_orders_cust ON ec_orders(customer_id);
CREATE INDEX idx_ec_orders_date ON ec_orders(order_date);
CREATE INDEX idx_ec_orders_status ON ec_orders(order_status);
CREATE INDEX idx_ec_orders_paystatus ON ec_orders(payment_status);
CREATE INDEX idx_ec_orders_je ON ec_orders(journal_entry_id);

CREATE TABLE ec_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    discount_amount NUMERIC(18,2),
    item_name VARCHAR(300) NOT NULL,
    quantity INTEGER NOT NULL,
    tax_amount NUMERIC(18,2),
    total_price NUMERIC(18,2) NOT NULL,
    unit_price NUMERIC(18,2) NOT NULL,
    order_id BIGINT NOT NULL REFERENCES ec_orders(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    variant_id BIGINT REFERENCES ec_product_variants(id)
);
ALTER TABLE ec_order_items OWNER TO postgres;
CREATE INDEX idx_ec_orderitem_order ON ec_order_items(order_id);
CREATE INDEX idx_ec_orderitem_prod ON ec_order_items(product_id);
CREATE INDEX idx_ec_orderitem_var ON ec_order_items(variant_id);

CREATE TABLE ec_order_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    address_type VARCHAR(20) NOT NULL,
    city VARCHAR(100) NOT NULL,
    contact_number VARCHAR(50),
    contact_person VARCHAR(200),
    country VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    state VARCHAR(100) NOT NULL,
    order_id BIGINT NOT NULL REFERENCES ec_orders(id),
    CONSTRAINT chk_ec_ordaddr_type CHECK ((address_type)::text = ANY (ARRAY['BILLING'::character varying, 'SHIPPING'::character varying]))
);
ALTER TABLE ec_order_addresses OWNER TO postgres;
CREATE INDEX idx_ec_ordaddr_order ON ec_order_addresses(order_id);

CREATE TABLE ec_order_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    note TEXT NOT NULL,
    note_type VARCHAR(30),
    created_by BIGINT,
    order_id BIGINT NOT NULL REFERENCES ec_orders(id),
    CONSTRAINT chk_ec_ordnote_type CHECK ((note_type)::text = ANY (ARRAY['INTERNAL'::character varying, 'CUSTOMER'::character varying, 'VENDOR'::character varying]))
);
ALTER TABLE ec_order_notes OWNER TO postgres;
CREATE INDEX idx_ec_ordnote_order ON ec_order_notes(order_id);

CREATE TABLE ec_order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at TIMESTAMP(6),
    remarks TEXT,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    changed_by BIGINT,
    order_id BIGINT NOT NULL REFERENCES ec_orders(id)
);
ALTER TABLE ec_order_status_history OWNER TO postgres;
CREATE INDEX idx_ec_ordhist_order ON ec_order_status_history(order_id);

CREATE TABLE ec_order_delivery_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    delivery_charge NUMERIC(18,2),
    delivery_notes TEXT,
    slot_date DATE NOT NULL,
    slot_time_from TIME NOT NULL,
    slot_time_to TIME NOT NULL,
    order_id BIGINT NOT NULL REFERENCES ec_orders(id)
);
ALTER TABLE ec_order_delivery_slots OWNER TO postgres;
CREATE INDEX idx_ec_ordslot_order ON ec_order_delivery_slots(order_id);

-- ============================================================
-- GROUP 7: Payments
-- ============================================================

CREATE TABLE ec_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    payment_number VARCHAR(50) NOT NULL,
    payment_date TIMESTAMP(6) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    payment_reference VARCHAR(200),
    amount NUMERIC(18,2) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    notes TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    order_id BIGINT NOT NULL REFERENCES ec_orders(id),
    CONSTRAINT uq_ec_pay_number UNIQUE (organization_id, payment_number),
    CONSTRAINT chk_ec_pay_method CHECK ((payment_method)::text = ANY (ARRAY['CASH'::character varying, 'CARD'::character varying, 'BANK_TRANSFER'::character varying, 'CHEQUE'::character varying, 'ONLINE'::character varying, 'WALLET'::character varying, 'COD'::character varying])),
    CONSTRAINT chk_ec_pay_status CHECK ((payment_status)::text = ANY (ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'CANCELLED'::character varying]))
);
ALTER TABLE ec_payments OWNER TO postgres;
CREATE INDEX idx_ec_pay_org ON ec_payments(organization_id);
CREATE INDEX idx_ec_pay_order ON ec_payments(order_id);
CREATE INDEX idx_ec_pay_status ON ec_payments(payment_status);

CREATE TABLE ec_payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    amount NUMERIC(18,2) NOT NULL,
    gateway_response TEXT,
    transaction_date TIMESTAMP(6),
    transaction_id VARCHAR(200),
    transaction_status VARCHAR(30),
    transaction_type VARCHAR(30),
    payment_id BIGINT NOT NULL REFERENCES ec_payments(id),
    CONSTRAINT chk_ec_paytxn_type CHECK ((transaction_type)::text = ANY (ARRAY['CAPTURE'::character varying, 'AUTHORIZE'::character varying, 'VOID'::character varying, 'REFUND'::character varying]))
);
ALTER TABLE ec_payment_transactions OWNER TO postgres;
CREATE INDEX idx_ec_paytxn_pay ON ec_payment_transactions(payment_id);
CREATE INDEX idx_ec_paytxn_txnid ON ec_payment_transactions(transaction_id);

-- ============================================================
-- GROUP 8: Shipping
-- ============================================================

CREATE TABLE ec_shipping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    shipping_number VARCHAR(50) NOT NULL,
    shipping_date TIMESTAMP(6),
    estimated_delivery TIMESTAMP(6),
    delivered_date TIMESTAMP(6),
    carrier VARCHAR(100),
    tracking_number VARCHAR(200),
    shipping_status VARCHAR(30) NOT NULL,
    notes TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    order_id BIGINT NOT NULL REFERENCES ec_orders(id),
    CONSTRAINT uq_ec_ship_number UNIQUE (organization_id, shipping_number),
    CONSTRAINT chk_ec_ship_status CHECK ((shipping_status)::text = ANY (ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'FAILED'::character varying, 'RETURNED'::character varying]))
);
ALTER TABLE ec_shipping OWNER TO postgres;
CREATE INDEX idx_ec_ship_org ON ec_shipping(organization_id);
CREATE INDEX idx_ec_ship_order ON ec_shipping(order_id);
CREATE INDEX idx_ec_ship_track ON ec_shipping(tracking_number);

CREATE TABLE ec_shipment_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    height NUMERIC(12,3),
    length NUMERIC(12,3),
    package_name VARCHAR(200),
    tracking_number VARCHAR(200),
    weight NUMERIC(12,3),
    width NUMERIC(12,3),
    shipping_id BIGINT NOT NULL REFERENCES ec_shipping(id)
);
ALTER TABLE ec_shipment_packages OWNER TO postgres;
CREATE INDEX idx_ec_shipack_ship ON ec_shipment_packages(shipping_id);

CREATE TABLE ec_shipping_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    event_date TIMESTAMP(6),
    event_location VARCHAR(255),
    remarks TEXT,
    tracking_event VARCHAR(200),
    shipping_id BIGINT NOT NULL REFERENCES ec_shipping(id)
);
ALTER TABLE ec_shipping_tracking OWNER TO postgres;
CREATE INDEX idx_ec_shiptrack_ship ON ec_shipping_tracking(shipping_id);

CREATE TABLE ec_shipping_api_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    api_endpoint VARCHAR(500),
    request_payload TEXT,
    response_payload TEXT,
    status_code VARCHAR(10),
    shipping_id BIGINT NOT NULL REFERENCES ec_shipping(id)
);
ALTER TABLE ec_shipping_api_logs OWNER TO postgres;
CREATE INDEX idx_ec_shiplog_ship ON ec_shipping_api_logs(shipping_id);

-- ============================================================
-- GROUP 9: Shipping Methods & Zones
-- ============================================================

CREATE TABLE ec_shipping_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    active BOOLEAN NOT NULL,
    additional_cost NUMERIC(18,2),
    base_cost NUMERIC(18,2) NOT NULL,
    carrier VARCHAR(100),
    code VARCHAR(50) NOT NULL,
    description TEXT,
    estimated_days VARCHAR(50),
    name VARCHAR(200) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_shipmthd_code UNIQUE (organization_id, code)
);
ALTER TABLE ec_shipping_methods OWNER TO postgres;
CREATE INDEX idx_ec_shipmthd_org ON ec_shipping_methods(organization_id);

CREATE TABLE ec_shipping_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    active BOOLEAN NOT NULL,
    cities TEXT,
    code VARCHAR(50) NOT NULL,
    countries TEXT,
    name VARCHAR(200) NOT NULL,
    states TEXT,
    zip_codes TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    shipping_method_id BIGINT REFERENCES ec_shipping_methods(id),
    CONSTRAINT uq_ec_shipzone_code UNIQUE (organization_id, code)
);
ALTER TABLE ec_shipping_zones OWNER TO postgres;
CREATE INDEX idx_ec_shipzone_org ON ec_shipping_zones(organization_id);
CREATE INDEX idx_ec_shipzone_method ON ec_shipping_zones(shipping_method_id);

-- ============================================================
-- GROUP 10: Tax Classes & Rules
-- ============================================================

CREATE TABLE ec_tax_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    active BOOLEAN NOT NULL,
    code VARCHAR(50) NOT NULL,
    description TEXT,
    name VARCHAR(200) NOT NULL,
    rate NUMERIC(8,4) NOT NULL,
    tax_type VARCHAR(30),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_taxcls_code UNIQUE (organization_id, code),
    CONSTRAINT chk_ec_taxcls_type CHECK ((tax_type)::text = ANY (ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying]))
);
ALTER TABLE ec_tax_classes OWNER TO postgres;
CREATE INDEX idx_ec_taxcls_org ON ec_tax_classes(organization_id);

CREATE TABLE ec_tax_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    active BOOLEAN NOT NULL,
    apply_on VARCHAR(50),
    name VARCHAR(200) NOT NULL,
    priority INTEGER,
    rate NUMERIC(8,4) NOT NULL,
    tax_type VARCHAR(30),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    tax_class_id BIGINT NOT NULL REFERENCES ec_tax_classes(id),
    CONSTRAINT chk_ec_taxrule_type CHECK ((tax_type)::text = ANY (ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying])),
    CONSTRAINT chk_ec_taxrule_apply CHECK ((apply_on)::text = ANY (ARRAY['PRODUCT'::character varying, 'SHIPPING'::character varying, 'TOTAL'::character varying]))
);
ALTER TABLE ec_tax_rules OWNER TO postgres;
CREATE INDEX idx_ec_taxrule_org ON ec_tax_rules(organization_id);
CREATE INDEX idx_ec_taxrule_class ON ec_tax_rules(tax_class_id);

-- ============================================================
-- GROUP 11: Coupons
-- ============================================================

CREATE TABLE ec_coupon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    coupon_code VARCHAR(50) NOT NULL,
    coupon_name VARCHAR(200) NOT NULL,
    description TEXT,
    discount_type VARCHAR(20) NOT NULL,
    discount_value NUMERIC(18,2) NOT NULL,
    maximum_discount NUMERIC(18,2),
    minimum_order_amount NUMERIC(18,2),
    start_date TIMESTAMP(6) NOT NULL,
    end_date TIMESTAMP(6) NOT NULL,
    usage_limit INTEGER,
    usage_per_customer INTEGER,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_coupon_code UNIQUE (organization_id, coupon_code),
    CONSTRAINT chk_ec_coupon_type CHECK ((discount_type)::text = ANY (ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying, 'FREE_SHIPPING'::character varying]))
);
ALTER TABLE ec_coupon OWNER TO postgres;
CREATE INDEX idx_ec_coupon_org ON ec_coupon(organization_id);
CREATE INDEX idx_ec_coupon_code ON ec_coupon(coupon_code);

CREATE TABLE ec_coupon_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    used_at TIMESTAMP(6),
    discount_amount NUMERIC(18,2) NOT NULL,
    coupon_id BIGINT NOT NULL REFERENCES ec_coupon(id),
    order_id BIGINT NOT NULL REFERENCES ec_orders(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id)
);
ALTER TABLE ec_coupon_usage OWNER TO postgres;
CREATE INDEX idx_ec_coupusage_coupon ON ec_coupon_usage(coupon_id);
CREATE INDEX idx_ec_coupusage_cust ON ec_coupon_usage(customer_id);
CREATE INDEX idx_ec_coupusage_order ON ec_coupon_usage(order_id);

-- ============================================================
-- GROUP 12: Campaigns
-- ============================================================

CREATE TABLE ec_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    campaign_name VARCHAR(200) NOT NULL,
    campaign_type VARCHAR(30) NOT NULL,
    description TEXT,
    start_date TIMESTAMP(6) NOT NULL,
    end_date TIMESTAMP(6) NOT NULL,
    budget NUMERIC(18,2),
    spent_amount NUMERIC(18,2),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_camp_name UNIQUE (organization_id, campaign_name),
    CONSTRAINT chk_ec_camp_type CHECK ((campaign_type)::text = ANY (ARRAY['SEASONAL'::character varying, 'PROMOTIONAL'::character varying, 'NEW_ARRIVAL'::character varying, 'CLEARANCE'::character varying, 'FESTIVAL'::character varying]))
);
ALTER TABLE ec_campaigns OWNER TO postgres;
CREATE INDEX idx_ec_camp_org ON ec_campaigns(organization_id);
CREATE INDEX idx_ec_camp_dates ON ec_campaigns(start_date, end_date);

CREATE TABLE ec_campaign_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    discount_type VARCHAR(20) NOT NULL,
    discount_value NUMERIC(18,2) NOT NULL,
    end_date TIMESTAMP(6),
    start_date TIMESTAMP(6),
    campaign_id BIGINT NOT NULL REFERENCES ec_campaigns(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    variant_id BIGINT REFERENCES ec_product_variants(id),
    CONSTRAINT chk_ec_campprod_dtype CHECK ((discount_type)::text = ANY (ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying]))
);
ALTER TABLE ec_campaign_products OWNER TO postgres;
CREATE INDEX idx_ec_campprod_camp ON ec_campaign_products(campaign_id);
CREATE INDEX idx_ec_campprod_prod ON ec_campaign_products(product_id);

-- ============================================================
-- GROUP 13: Banners
-- ============================================================

CREATE TABLE ec_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    banner_name VARCHAR(200) NOT NULL,
    banner_type VARCHAR(30) NOT NULL,
    banner_url VARCHAR(700),
    image_url VARCHAR(700) NOT NULL,
    link_type VARCHAR(30),
    link_url VARCHAR(700),
    sort_order INTEGER,
    start_date TIMESTAMP(6),
    end_date TIMESTAMP(6),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT chk_ec_banner_type CHECK ((banner_type)::text = ANY (ARRAY['SLIDER'::character varying, 'PROMO'::character varying, 'SIDEBAR'::character varying, 'POPUP'::character varying])),
    CONSTRAINT chk_ec_banner_linktype CHECK ((link_type)::text = ANY (ARRAY['PRODUCT'::character varying, 'CATEGORY'::character varying, 'URL'::character varying, 'NONE'::character varying]))
);
ALTER TABLE ec_banners OWNER TO postgres;
CREATE INDEX idx_ec_banner_org ON ec_banners(organization_id);
CREATE INDEX idx_ec_banner_active ON ec_banners(active);
CREATE INDEX idx_ec_banner_type ON ec_banners(banner_type);

-- ============================================================
-- GROUP 14: Home Sections
-- ============================================================

CREATE TABLE ec_home_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    display_order INTEGER,
    section_name VARCHAR(200) NOT NULL,
    section_type VARCHAR(50) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT chk_ec_homesec_type CHECK ((section_type)::text = ANY (ARRAY['FEATURED'::character varying, 'BEST_SELLER'::character varying, 'NEW_ARRIVAL'::character varying, 'TRENDING'::character varying, 'RECOMMENDED'::character varying, 'CUSTOM'::character varying]))
);
ALTER TABLE ec_home_sections OWNER TO postgres;
CREATE INDEX idx_ec_homesec_org ON ec_home_sections(organization_id);
CREATE INDEX idx_ec_homesec_order ON ec_home_sections(display_order);

CREATE TABLE ec_home_section_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    display_order INTEGER,
    section_id BIGINT NOT NULL REFERENCES ec_home_sections(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id)
);
ALTER TABLE ec_home_section_products OWNER TO postgres;
CREATE INDEX idx_ec_homesecprod_sec ON ec_home_section_products(section_id);
CREATE INDEX idx_ec_homesecprod_prod ON ec_home_section_products(product_id);

-- ============================================================
-- GROUP 15: Returns & Refunds
-- ============================================================

CREATE TABLE ec_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    return_number VARCHAR(50) NOT NULL,
    return_date TIMESTAMP(6) NOT NULL,
    return_type VARCHAR(30) NOT NULL,
    return_reason TEXT,
    total_amount NUMERIC(18,2) NOT NULL,
    refund_amount NUMERIC(18,2),
    return_status VARCHAR(20) NOT NULL,
    notes TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    order_id BIGINT NOT NULL REFERENCES ec_orders(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    journal_entry_id BIGINT REFERENCES acc_journal_entry_master(id),
    CONSTRAINT uq_ec_ret_number UNIQUE (organization_id, return_number),
    CONSTRAINT chk_ec_ret_type CHECK ((return_type)::text = ANY (ARRAY['FULL'::character varying, 'PARTIAL'::character varying])),
    CONSTRAINT chk_ec_ret_status CHECK ((return_status)::text = ANY (ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'PENDING_REFUND'::character varying, 'REFUNDED'::character varying, 'CLOSED'::character varying]))
);
ALTER TABLE ec_returns OWNER TO postgres;
CREATE INDEX idx_ec_ret_org ON ec_returns(organization_id);
CREATE INDEX idx_ec_ret_order ON ec_returns(order_id);
CREATE INDEX idx_ec_ret_cust ON ec_returns(customer_id);

CREATE TABLE ec_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    quantity INTEGER NOT NULL,
    return_reason TEXT,
    total_price NUMERIC(18,2) NOT NULL,
    unit_price NUMERIC(18,2) NOT NULL,
    order_item_id BIGINT NOT NULL REFERENCES ec_order_items(id),
    return_id BIGINT NOT NULL REFERENCES ec_returns(id)
);
ALTER TABLE ec_return_items OWNER TO postgres;
CREATE INDEX idx_ec_retitem_ret ON ec_return_items(return_id);
CREATE INDEX idx_ec_retitem_orditem ON ec_return_items(order_item_id);

CREATE TABLE ec_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    refund_number VARCHAR(50) NOT NULL,
    refund_date TIMESTAMP(6) NOT NULL,
    refund_method VARCHAR(30) NOT NULL,
    refund_amount NUMERIC(18,2) NOT NULL,
    refund_status VARCHAR(20) NOT NULL,
    notes TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    return_id BIGINT NOT NULL REFERENCES ec_returns(id),
    journal_entry_id BIGINT REFERENCES acc_journal_entry_master(id),
    CONSTRAINT uq_ec_ref_number UNIQUE (organization_id, refund_number),
    CONSTRAINT chk_ec_ref_method CHECK ((refund_method)::text = ANY (ARRAY['ORIGINAL_PAYMENT'::character varying, 'BANK_TRANSFER'::character varying, 'WALLET'::character varying, 'CASH'::character varying])),
    CONSTRAINT chk_ec_ref_status CHECK ((refund_status)::text = ANY (ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying]))
);
ALTER TABLE ec_refunds OWNER TO postgres;
CREATE INDEX idx_ec_ref_org ON ec_refunds(organization_id);
CREATE INDEX idx_ec_ref_return ON ec_refunds(return_id);

-- ============================================================
-- GROUP 16: Wishlist, Recently Viewed, Saved for Later
-- ============================================================

CREATE TABLE ec_wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    CONSTRAINT uq_ec_wishlist UNIQUE (customer_id, product_id)
);
ALTER TABLE ec_wishlist OWNER TO postgres;
CREATE INDEX idx_ec_wish_cust ON ec_wishlist(customer_id);
CREATE INDEX idx_ec_wish_prod ON ec_wishlist(product_id);

CREATE TABLE ec_recently_viewed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewed_at TIMESTAMP(6),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id)
);
ALTER TABLE ec_recently_viewed OWNER TO postgres;
CREATE INDEX idx_ec_recview_cust ON ec_recently_viewed(customer_id);
CREATE INDEX idx_ec_recview_prod ON ec_recently_viewed(product_id);
CREATE INDEX idx_ec_recview_time ON ec_recently_viewed(viewed_at);

CREATE TABLE ec_saved_for_later (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saved_at TIMESTAMP(6),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    CONSTRAINT uq_ec_saved UNIQUE (customer_id, product_id)
);
ALTER TABLE ec_saved_for_later OWNER TO postgres;
CREATE INDEX idx_ec_saved_cust ON ec_saved_for_later(customer_id);
CREATE INDEX idx_ec_saved_prod ON ec_saved_for_later(product_id);

-- ============================================================
-- GROUP 17: Affiliates & Referrals
-- ============================================================

CREATE TABLE ec_affiliates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    affiliate_code VARCHAR(50) NOT NULL,
    affiliate_name VARCHAR(200) NOT NULL,
    commission_rate NUMERIC(8,4) NOT NULL,
    commission_type VARCHAR(20) NOT NULL,
    contact_person VARCHAR(200),
    email VARCHAR(200),
    payment_details TEXT,
    payment_method VARCHAR(50),
    phone VARCHAR(50),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT REFERENCES ec_customers(id),
    CONSTRAINT uq_ec_aff_code UNIQUE (organization_id, affiliate_code),
    CONSTRAINT chk_ec_aff_comtype CHECK ((commission_type)::text = ANY (ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying]))
);
ALTER TABLE ec_affiliates OWNER TO postgres;
CREATE INDEX idx_ec_aff_org ON ec_affiliates(organization_id);
CREATE INDEX idx_ec_aff_cust ON ec_affiliates(customer_id);

CREATE TABLE ec_referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    commission_amount NUMERIC(18,2),
    conversion_date TIMESTAMP(6),
    referral_code VARCHAR(50),
    referral_date TIMESTAMP(6),
    status VARCHAR(20) NOT NULL,
    affiliate_id BIGINT NOT NULL REFERENCES ec_affiliates(id),
    referred_customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    CONSTRAINT chk_ec_ref_status CHECK ((status)::text = ANY (ARRAY['PENDING'::character varying, 'CONVERTED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying]))
);
ALTER TABLE ec_referrals OWNER TO postgres;
CREATE INDEX idx_ec_ref_aff ON ec_referrals(affiliate_id);
CREATE INDEX idx_ec_ref_cust ON ec_referrals(referred_customer_id);

-- ============================================================
-- GROUP 18: Reward Points & Loyalty Programs
-- ============================================================

CREATE TABLE ec_reward_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    description TEXT,
    expiry_date TIMESTAMP(6),
    points INTEGER NOT NULL,
    transaction_reference VARCHAR(200),
    transaction_type VARCHAR(30) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    CONSTRAINT chk_ec_rwrd_type CHECK ((transaction_type)::text = ANY (ARRAY['EARNED'::character varying, 'REDEEMED'::character varying, 'EXPIRED'::character varying, 'ADJUSTED'::character varying]))
);
ALTER TABLE ec_reward_points OWNER TO postgres;
CREATE INDEX idx_ec_rwrd_cust ON ec_reward_points(customer_id);
CREATE INDEX idx_ec_rwrd_org ON ec_reward_points(organization_id);

CREATE TABLE ec_loyalty_programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    expiry_date TIMESTAMP(6),
    join_date TIMESTAMP(6),
    tier VARCHAR(50),
    total_points INTEGER NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT NOT NULL UNIQUE REFERENCES ec_customers(id),
    CONSTRAINT chk_ec_loyal_tier CHECK ((tier)::text = ANY (ARRAY['BRONZE'::character varying, 'SILVER'::character varying, 'GOLD'::character varying, 'PLATINUM'::character varying]))
);
ALTER TABLE ec_loyalty_programs OWNER TO postgres;
CREATE INDEX idx_ec_loyal_cust ON ec_loyalty_programs(customer_id);
CREATE INDEX idx_ec_loyal_org ON ec_loyalty_programs(organization_id);

-- ============================================================
-- GROUP 19: Gift Cards
-- ============================================================

CREATE TABLE ec_gift_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    gift_card_number VARCHAR(50) NOT NULL,
    issue_date TIMESTAMP(6) NOT NULL,
    expiry_date TIMESTAMP(6) NOT NULL,
    initial_balance NUMERIC(18,2) NOT NULL,
    current_balance NUMERIC(18,2) NOT NULL,
    sender_name VARCHAR(200),
    recipient_name VARCHAR(200),
    recipient_email VARCHAR(200),
    message TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT REFERENCES ec_customers(id),
    CONSTRAINT uq_ec_gift_number UNIQUE (organization_id, gift_card_number)
);
ALTER TABLE ec_gift_cards OWNER TO postgres;
CREATE INDEX idx_ec_gift_org ON ec_gift_cards(organization_id);
CREATE INDEX idx_ec_gift_cust ON ec_gift_cards(customer_id);

-- ============================================================
-- GROUP 20: Content & CMS
-- ============================================================

CREATE TABLE ec_newsletter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    email VARCHAR(200) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    subscribed BOOLEAN NOT NULL,
    subscription_date TIMESTAMP(6),
    unsubscription_date TIMESTAMP(6),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_news_email UNIQUE (organization_id, email)
);
ALTER TABLE ec_newsletter OWNER TO postgres;
CREATE INDEX idx_ec_news_org ON ec_newsletter(organization_id);
CREATE INDEX idx_ec_news_sub ON ec_newsletter(subscribed);

CREATE TABLE ec_seo_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    canonical_url VARCHAR(700),
    meta_description VARCHAR(1000),
    meta_keywords VARCHAR(500),
    meta_title VARCHAR(255),
    no_follow BOOLEAN,
    no_index BOOLEAN,
    og_description VARCHAR(1000),
    og_image VARCHAR(700),
    og_title VARCHAR(255),
    page_url VARCHAR(700) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_seo_url UNIQUE (organization_id, page_url)
);
ALTER TABLE ec_seo_metadata OWNER TO postgres;
CREATE INDEX idx_ec_seo_org ON ec_seo_metadata(organization_id);
CREATE INDEX idx_ec_seo_url ON ec_seo_metadata(page_url);

CREATE TABLE ec_blog_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    active BOOLEAN NOT NULL,
    description TEXT,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(250) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_blogcat_slug UNIQUE (organization_id, slug)
);
ALTER TABLE ec_blog_categories OWNER TO postgres;
CREATE INDEX idx_ec_blogcat_org ON ec_blog_categories(organization_id);

CREATE TABLE ec_blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT REFERENCES sec_users(id),
    updated_at TIMESTAMP(6),
    updated_by BIGINT REFERENCES sec_users(id),
    active BOOLEAN NOT NULL,
    content TEXT,
    excerpt TEXT,
    featured_image VARCHAR(700),
    meta_description VARCHAR(1000),
    meta_title VARCHAR(255),
    publish_date TIMESTAMP(6),
    published BOOLEAN NOT NULL,
    slug VARCHAR(250) NOT NULL,
    tags VARCHAR(500),
    title VARCHAR(300) NOT NULL,
    blog_category_id BIGINT REFERENCES ec_blog_categories(id),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_blogpost_slug UNIQUE (organization_id, slug)
);
ALTER TABLE ec_blog_posts OWNER TO postgres;
CREATE INDEX idx_ec_blogpost_org ON ec_blog_posts(organization_id);
CREATE INDEX idx_ec_blogpost_cat ON ec_blog_posts(blog_category_id);
CREATE INDEX idx_ec_blogpost_pub ON ec_blog_posts(published, publish_date);

CREATE TABLE ec_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT REFERENCES sec_users(id),
    updated_at TIMESTAMP(6),
    updated_by BIGINT REFERENCES sec_users(id),
    content TEXT,
    meta_description VARCHAR(1000),
    meta_title VARCHAR(255),
    publish_date TIMESTAMP(6),
    published BOOLEAN NOT NULL,
    slug VARCHAR(250) NOT NULL,
    title VARCHAR(300) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_page_slug UNIQUE (organization_id, slug)
);
ALTER TABLE ec_pages OWNER TO postgres;
CREATE INDEX idx_ec_page_org ON ec_pages(organization_id);

CREATE TABLE ec_media_library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    alt_text VARCHAR(500),
    caption VARCHAR(500),
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(700) NOT NULL,
    file_size BIGINT,
    file_type VARCHAR(100),
    height INTEGER,
    width INTEGER,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE ec_media_library OWNER TO postgres;
CREATE INDEX idx_ec_media_org ON ec_media_library(organization_id);
CREATE INDEX idx_ec_media_type ON ec_media_library(file_type);

-- ============================================================
-- GROUP 21: Configuration & Settings
-- ============================================================

CREATE TABLE ec_url_redirects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    active BOOLEAN NOT NULL,
    redirect_type VARCHAR(10) NOT NULL,
    source_url VARCHAR(700) NOT NULL,
    target_url VARCHAR(700) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_redir_source UNIQUE (organization_id, source_url),
    CONSTRAINT chk_ec_redir_type CHECK ((redirect_type)::text = ANY (ARRAY['301'::character varying, '302'::character varying]))
);
ALTER TABLE ec_url_redirects OWNER TO postgres;
CREATE INDEX idx_ec_redir_org ON ec_url_redirects(organization_id);

CREATE TABLE ec_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    description TEXT,
    setting_group VARCHAR(100),
    setting_key VARCHAR(200) NOT NULL,
    setting_value TEXT NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_setting UNIQUE (organization_id, setting_key)
);
ALTER TABLE ec_settings OWNER TO postgres;
CREATE INDEX idx_ec_setting_org ON ec_settings(organization_id);
CREATE INDEX idx_ec_setting_group ON ec_settings(setting_group);

CREATE TABLE ec_feature_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    enabled BOOLEAN NOT NULL,
    feature_key VARCHAR(100) NOT NULL,
    feature_name VARCHAR(200) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_feature UNIQUE (organization_id, feature_key)
);
ALTER TABLE ec_feature_flags OWNER TO postgres;
CREATE INDEX idx_ec_feature_org ON ec_feature_flags(organization_id);

CREATE TABLE ec_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    display_order INTEGER,
    icon VARCHAR(100),
    menu_code VARCHAR(50) NOT NULL,
    menu_name VARCHAR(200) NOT NULL,
    slug VARCHAR(250),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    parent_id BIGINT REFERENCES ec_menus(id),
    CONSTRAINT uq_ec_menu_code UNIQUE (organization_id, menu_code)
);
ALTER TABLE ec_menus OWNER TO postgres;
CREATE INDEX idx_ec_menu_org ON ec_menus(organization_id);
CREATE INDEX idx_ec_menu_parent ON ec_menus(parent_id);
CREATE INDEX idx_ec_menu_order ON ec_menus(display_order);

CREATE TABLE ec_delivery_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    active BOOLEAN NOT NULL,
    current_orders INTEGER,
    day_of_week INTEGER NOT NULL,
    end_time TIME NOT NULL,
    max_orders INTEGER,
    slot_name VARCHAR(200) NOT NULL,
    start_time TIME NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT chk_ec_delslot_dow CHECK ((day_of_week)::integer = ANY (ARRAY[0, 1, 2, 3, 4, 5, 6]))
);
ALTER TABLE ec_delivery_slots OWNER TO postgres;
CREATE INDEX idx_ec_delslot_org ON ec_delivery_slots(organization_id);
CREATE INDEX idx_ec_delslot_day ON ec_delivery_slots(day_of_week);

-- ============================================================
-- GROUP 22: Document Mapping & GL Account Defaults
-- ============================================================

CREATE TABLE ec_document_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    document_id BIGINT NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    ec_entity_id BIGINT NOT NULL,
    ec_entity_type VARCHAR(50) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE ec_document_mapping OWNER TO postgres;
CREATE INDEX idx_ec_docmap_org ON ec_document_mapping(organization_id);
CREATE INDEX idx_ec_docmap_doc ON ec_document_mapping(document_type, document_id);
CREATE INDEX idx_ec_docmap_ec ON ec_document_mapping(ec_entity_type, ec_entity_id);

CREATE TABLE ec_gl_account_defaults (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    account_category VARCHAR(50) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    credit_account_id BIGINT REFERENCES acc_chart_of_accounts(id),
    debit_account_id BIGINT REFERENCES acc_chart_of_accounts(id),
    CONSTRAINT uq_ec_gl_default UNIQUE (organization_id, account_category)
);
ALTER TABLE ec_gl_account_defaults OWNER TO postgres;
CREATE INDEX idx_ec_gldef_org ON ec_gl_account_defaults(organization_id);

-- ============================================================
-- GROUP 23: API Configurations, KPIs, Audit Logs, Notifications
-- ============================================================

CREATE TABLE ec_api_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    api_key VARCHAR(500),
    api_name VARCHAR(200) NOT NULL,
    api_secret VARCHAR(500),
    endpoint_url VARCHAR(700),
    is_active BOOLEAN NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_ec_apiconf_name UNIQUE (organization_id, api_name)
);
ALTER TABLE ec_api_configurations OWNER TO postgres;
CREATE INDEX idx_ec_apiconf_org ON ec_api_configurations(organization_id);

CREATE TABLE ec_dashboard_kpis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    kpi_name VARCHAR(200) NOT NULL,
    kpi_period VARCHAR(30),
    kpi_value NUMERIC(18,2),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE ec_dashboard_kpis OWNER TO postgres;
CREATE INDEX idx_ec_kpi_org ON ec_dashboard_kpis(organization_id);
CREATE INDEX idx_ec_kpi_period ON ec_dashboard_kpis(kpi_period);

CREATE TABLE ec_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    action VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    ip_address VARCHAR(50),
    new_value TEXT,
    old_value TEXT,
    user_agent TEXT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    created_by BIGINT REFERENCES sec_users(id)
);
ALTER TABLE ec_audit_logs OWNER TO postgres;
CREATE INDEX idx_ec_audit_org ON ec_audit_logs(organization_id);
CREATE INDEX idx_ec_audit_entity ON ec_audit_logs(entity_type, entity_id);
CREATE INDEX idx_ec_audit_user ON ec_audit_logs(created_by);
CREATE INDEX idx_ec_audit_time ON ec_audit_logs(created_at);

CREATE TABLE ec_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT REFERENCES sec_users(id),
    is_read BOOLEAN NOT NULL,
    message TEXT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    read_at TIMESTAMP(6),
    recipient_id BIGINT,
    recipient_type VARCHAR(30) NOT NULL,
    title VARCHAR(300) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT chk_ec_notif_type CHECK ((notification_type)::text = ANY (ARRAY['ORDER'::character varying, 'PAYMENT'::character varying, 'SHIPPING'::character varying, 'RETURN'::character varying, 'REVIEW'::character varying, 'PROMOTIONAL'::character varying, 'SYSTEM'::character varying])),
    CONSTRAINT chk_ec_notif_recip CHECK ((recipient_type)::text = ANY (ARRAY['CUSTOMER'::character varying, 'USER'::character varying, 'ALL'::character varying]))
);
ALTER TABLE ec_notifications OWNER TO postgres;
CREATE INDEX idx_ec_notif_org ON ec_notifications(organization_id);
CREATE INDEX idx_ec_notif_recip ON ec_notifications(recipient_type, recipient_id);
CREATE INDEX idx_ec_notif_read ON ec_notifications(is_read);

-- ============================================================
-- GROUP 24: Abandoned Cart
-- ============================================================

CREATE TABLE ec_abandoned_cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    abandoned_at TIMESTAMP(6) NOT NULL,
    cart_total NUMERIC(18,2),
    recovered BOOLEAN NOT NULL,
    recovery_date TIMESTAMP(6),
    reminder_count INTEGER NOT NULL,
    reminder_sent BOOLEAN NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    cart_id BIGINT REFERENCES ec_cart(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id)
);
ALTER TABLE ec_abandoned_cart OWNER TO postgres;
CREATE INDEX idx_ec_abancart_org ON ec_abandoned_cart(organization_id);
CREATE INDEX idx_ec_abancart_cust ON ec_abandoned_cart(customer_id);
CREATE INDEX idx_ec_abancart_recover ON ec_abandoned_cart(recovered);
CREATE INDEX idx_ec_abancart_time ON ec_abandoned_cart(abandoned_at);

-- ============================================================
-- GROUP 25: Reviews & Review Sub-Entities
-- ============================================================

CREATE TABLE ec_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT,
    updated_at TIMESTAMP(6),
    updated_by BIGINT,
    active BOOLEAN NOT NULL,
    approved_at TIMESTAMP(6),
    approved_by BIGINT,
    cons TEXT,
    dislikes_count INTEGER NOT NULL,
    helpful_count INTEGER NOT NULL,
    likes_count INTEGER NOT NULL,
    pros TEXT,
    rating INTEGER NOT NULL,
    recommendation BOOLEAN,
    report_count INTEGER NOT NULL,
    review_status VARCHAR(20) NOT NULL,
    review_text TEXT,
    review_title VARCHAR(200),
    verified_purchase BOOLEAN NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    order_item_id BIGINT REFERENCES ec_order_items(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    CONSTRAINT chk_ec_rev_status CHECK ((review_status)::text = ANY (ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'HIDDEN'::character varying]))
);
ALTER TABLE ec_reviews OWNER TO postgres;
CREATE INDEX idx_ec_rev_prod ON ec_reviews(product_id);
CREATE INDEX idx_ec_rev_cust ON ec_reviews(customer_id);
CREATE INDEX idx_ec_rev_status ON ec_reviews(review_status);
CREATE INDEX idx_ec_rev_rating ON ec_reviews(rating);
CREATE INDEX idx_ec_rev_org ON ec_reviews(organization_id);

CREATE TABLE ec_review_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    image_url VARCHAR(700) NOT NULL,
    is_primary BOOLEAN,
    review_id BIGINT NOT NULL REFERENCES ec_reviews(id)
);
ALTER TABLE ec_review_images OWNER TO postgres;
CREATE INDEX idx_ec_revimg_rev ON ec_review_images(review_id);

CREATE TABLE ec_review_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    vote_type VARCHAR(10) NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    review_id BIGINT NOT NULL REFERENCES ec_reviews(id),
    CONSTRAINT uq_ec_revvote UNIQUE (review_id, customer_id),
    CONSTRAINT chk_ec_revvote_type CHECK ((vote_type)::text = ANY (ARRAY['UP'::character varying, 'DOWN'::character varying]))
);
ALTER TABLE ec_review_votes OWNER TO postgres;
CREATE INDEX idx_ec_revvote_rev ON ec_review_votes(review_id);
CREATE INDEX idx_ec_revvote_cust ON ec_review_votes(customer_id);

-- ============================================================
-- GROUP 26: Product Questions & Answers
-- ============================================================

CREATE TABLE ec_product_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT REFERENCES sec_users(id),
    updated_at TIMESTAMP(6),
    updated_by BIGINT REFERENCES sec_users(id),
    question_text TEXT NOT NULL,
    question_status VARCHAR(20) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    customer_id BIGINT NOT NULL REFERENCES ec_customers(id),
    product_id BIGINT NOT NULL REFERENCES ec_product_catalog(id),
    CONSTRAINT chk_ec_prodq_status CHECK ((question_status)::text = ANY (ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying]))
);
ALTER TABLE ec_product_questions OWNER TO postgres;
CREATE INDEX idx_ec_prodq_prod ON ec_product_questions(product_id);
CREATE INDEX idx_ec_prodq_cust ON ec_product_questions(customer_id);
CREATE INDEX idx_ec_prodq_status ON ec_product_questions(question_status);

CREATE TABLE ec_product_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by BIGINT REFERENCES sec_users(id),
    updated_at TIMESTAMP(6),
    updated_by BIGINT REFERENCES sec_users(id),
    answer_text TEXT NOT NULL,
    answered_by BIGINT REFERENCES sec_users(id),
    question_id BIGINT NOT NULL REFERENCES ec_product_questions(id)
);
ALTER TABLE ec_product_answers OWNER TO postgres;
CREATE INDEX idx_ec_proda_ques ON ec_product_answers(question_id);
