-- =============================================================================
-- Travel Module Schema (trv_*)
-- Version: V8
-- Description: Core travel schema including airlines, airports, hotels,
--              packages, tours, bookings, air tickets, visa applications,
--              and related entities.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Independent tables (no foreign key dependencies)
-- -----------------------------------------------------------------------------

CREATE TABLE trv_airlines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airline_code VARCHAR(3) NOT NULL CONSTRAINT uq_trv_airline_code UNIQUE,
    airline_name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP(6),
    is_active BOOLEAN NOT NULL
);
ALTER TABLE trv_airlines OWNER TO postgres;

CREATE TABLE trv_airports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport_code VARCHAR(3) NOT NULL CONSTRAINT uq_trv_airport_code UNIQUE,
    airport_name VARCHAR(200) NOT NULL,
    city VARCHAR(100),
    country VARCHAR(100),
    created_at TIMESTAMP(6)
);
ALTER TABLE trv_airports OWNER TO postgres;

CREATE TABLE trv_cabin_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_code VARCHAR(10) NOT NULL CONSTRAINT uq_trv_cabin_class_code UNIQUE,
    class_name VARCHAR(100) NOT NULL
);
ALTER TABLE trv_cabin_classes OWNER TO postgres;

CREATE TABLE trv_meal_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    description VARCHAR(300),
    plan_code VARCHAR(10) NOT NULL CONSTRAINT uq_trv_meal_plan_code UNIQUE,
    plan_name VARCHAR(100) NOT NULL
);
ALTER TABLE trv_meal_plans OWNER TO postgres;

CREATE TABLE trv_tour_guides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150),
    guide_name VARCHAR(150) NOT NULL,
    is_active BOOLEAN NOT NULL,
    languages VARCHAR(200),
    phone VARCHAR(30)
);
ALTER TABLE trv_tour_guides OWNER TO postgres;

CREATE TABLE trv_visa_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(100) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    description VARCHAR(500),
    fee_amount NUMERIC(18,2) NOT NULL,
    processing_days INTEGER,
    visa_category VARCHAR(100) NOT NULL
);
ALTER TABLE trv_visa_types OWNER TO postgres;

-- -----------------------------------------------------------------------------
-- 2. Hotels & Rooms (depends on org_organizations)
-- -----------------------------------------------------------------------------

CREATE TABLE trv_hotel_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    category_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE trv_hotel_categories OWNER TO postgres;

CREATE TABLE trv_hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    address VARCHAR(500),
    category_id BIGINT REFERENCES trv_hotel_categories(id),
    city VARCHAR(100),
    contact_email VARCHAR(150),
    contact_person VARCHAR(150),
    contact_phone VARCHAR(30),
    country VARCHAR(100),
    hotel_code VARCHAR(30) NOT NULL,
    hotel_name VARCHAR(200) NOT NULL,
    is_active BOOLEAN NOT NULL,
    star_rating INTEGER,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_trv_hotel_org_code UNIQUE (organization_id, hotel_code)
);
ALTER TABLE trv_hotels OWNER TO postgres;

CREATE TABLE trv_room_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    base_price NUMERIC(18,2),
    currency VARCHAR(3),
    hotel_id BIGINT NOT NULL REFERENCES trv_hotels(id),
    is_active BOOLEAN NOT NULL,
    max_occupancy INTEGER,
    room_type_name VARCHAR(150) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE trv_room_types OWNER TO postgres;

CREATE TABLE trv_room_facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    facility_name VARCHAR(150) NOT NULL,
    room_type_id BIGINT NOT NULL REFERENCES trv_room_types(id)
);
ALTER TABLE trv_room_facilities OWNER TO postgres;

-- -----------------------------------------------------------------------------
-- 3. Packages & Tours (depends on org_organizations)
-- -----------------------------------------------------------------------------

CREATE TABLE trv_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    base_price NUMERIC(18,2) NOT NULL,
    category VARCHAR(50),
    currency VARCHAR(3) NOT NULL,
    description VARCHAR(2000),
    destination VARCHAR(150),
    duration_days INTEGER,
    duration_nights INTEGER,
    is_active BOOLEAN NOT NULL,
    package_code VARCHAR(30) NOT NULL,
    package_name VARCHAR(200) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_trv_pkg_org_code UNIQUE (organization_id, package_code)
);
ALTER TABLE trv_packages OWNER TO postgres;

CREATE TABLE trv_package_inclusions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(300) NOT NULL,
    inclusion_type VARCHAR(10) NOT NULL CHECK ((inclusion_type)::text = ANY (ARRAY['INCLUDED'::character varying, 'EXCLUDED'::character varying])),
    package_id BIGINT NOT NULL REFERENCES trv_packages(id)
);
ALTER TABLE trv_package_inclusions OWNER TO postgres;

CREATE TABLE trv_package_itinerary_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_number INTEGER NOT NULL,
    description VARCHAR(1000),
    title VARCHAR(200),
    package_id BIGINT NOT NULL REFERENCES trv_packages(id)
);
ALTER TABLE trv_package_itinerary_days OWNER TO postgres;

CREATE TABLE trv_tours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    base_price NUMERIC(18,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    description VARCHAR(1000),
    destination VARCHAR(150),
    duration_hours NUMERIC(6,2),
    is_active BOOLEAN NOT NULL,
    tour_code VARCHAR(30) NOT NULL,
    tour_name VARCHAR(200) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_trv_tour_org_code UNIQUE (organization_id, tour_code)
);
ALTER TABLE trv_tours OWNER TO postgres;

-- -----------------------------------------------------------------------------
-- 4. Bookings (depends on org_organizations, acc_journal_entry_master,
--              acc_chart_of_accounts_sub, sec_users, crm_leads, crm_opportunities)
-- -----------------------------------------------------------------------------

CREATE TABLE trv_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    approval_request_id BIGINT,
    booking_date DATE NOT NULL,
    booking_no VARCHAR(50) NOT NULL,
    booking_type VARCHAR(20) NOT NULL CHECK ((booking_type)::text = ANY (ARRAY['PACKAGE'::character varying, 'HOTEL'::character varying, 'AIR'::character varying, 'COMBINED'::character varying])),
    currency VARCHAR(3) NOT NULL,
    discount_amount NUMERIC(18,2) NOT NULL,
    due_amount NUMERIC(18,2) NOT NULL,
    exchange_rate NUMERIC(18,4) NOT NULL,
    journal_entry_id BIGINT,
    lead_id BIGINT,
    opportunity_id BIGINT,
    paid_amount NUMERIC(18,2) NOT NULL,
    party_id BIGINT,
    remarks VARCHAR(1000),
    sales_agent_id BIGINT,
    status VARCHAR(20) NOT NULL CHECK ((status)::text = ANY (ARRAY['DRAFT'::character varying, 'CONFIRMED'::character varying, 'PARTIALLY_PAID'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])),
    subtotal_amount NUMERIC(18,2) NOT NULL,
    tax_amount NUMERIC(18,2) NOT NULL,
    total_amount NUMERIC(18,2) NOT NULL,
    travel_end_date DATE,
    travel_start_date DATE,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_trv_booking_org_no UNIQUE (organization_id, booking_no)
);
ALTER TABLE trv_bookings OWNER TO postgres;

CREATE TABLE trv_booking_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_center_id BIGINT,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    description VARCHAR(500),
    discount_amount NUMERIC(18,2) NOT NULL,
    line_total NUMERIC(18,2) NOT NULL,
    quantity NUMERIC(12,3) NOT NULL,
    reference_id BIGINT,
    service_type VARCHAR(20) NOT NULL CHECK ((service_type)::text = ANY (ARRAY['HOTEL'::character varying, 'AIR'::character varying, 'PACKAGE'::character varying, 'TOUR'::character varying, 'VISA'::character varying])),
    tax_amount NUMERIC(18,2) NOT NULL,
    unit_cost NUMERIC(18,2) NOT NULL,
    unit_price NUMERIC(18,2) NOT NULL,
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    booking_id BIGINT NOT NULL REFERENCES trv_bookings(id)
);
ALTER TABLE trv_booking_services OWNER TO postgres;

CREATE TABLE trv_passengers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    date_of_birth DATE,
    email VARCHAR(150),
    first_name VARCHAR(100) NOT NULL,
    gender VARCHAR(10) CHECK ((gender)::text = ANY (ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])),
    is_lead_passenger BOOLEAN NOT NULL,
    last_name VARCHAR(100),
    nationality VARCHAR(100),
    passenger_type VARCHAR(10) NOT NULL CHECK ((passenger_type)::text = ANY (ARRAY['ADULT'::character varying, 'CHILD'::character varying, 'INFANT'::character varying])),
    passport_expiry DATE,
    passport_number VARCHAR(50),
    phone VARCHAR(30),
    remarks VARCHAR(500),
    title VARCHAR(10),
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    booking_id BIGINT NOT NULL REFERENCES trv_bookings(id)
);
ALTER TABLE trv_passengers OWNER TO postgres;

CREATE TABLE trv_passenger_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dietary_restriction VARCHAR(300),
    meal_preference VARCHAR(100),
    passenger_id BIGINT NOT NULL CONSTRAINT uq_trv_pass_pref UNIQUE REFERENCES trv_passengers(id),
    remarks VARCHAR(500),
    seat_preference VARCHAR(100),
    special_assistance VARCHAR(300)
);
ALTER TABLE trv_passenger_preferences OWNER TO postgres;

CREATE TABLE trv_booking_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES trv_bookings(id),
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    note_text OID NOT NULL,
    note_type VARCHAR(20) NOT NULL CHECK ((note_type)::text = ANY (ARRAY['INTERNAL'::character varying, 'CUSTOMER'::character varying]))
);
ALTER TABLE trv_booking_notes OWNER TO postgres;

CREATE TABLE trv_booking_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    changed_at TIMESTAMP(6),
    changed_by VARCHAR(100),
    remarks VARCHAR(500),
    status VARCHAR(20) NOT NULL
);
ALTER TABLE trv_booking_status_history OWNER TO postgres;

-- -----------------------------------------------------------------------------
-- 5. Hotel Bookings & Air Tickets (depends on booking_services, trv_hotels,
--      trv_room_types, trv_airlines, trv_airports, trv_passengers)
-- -----------------------------------------------------------------------------

CREATE TABLE trv_hotel_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    adults INTEGER NOT NULL,
    booking_service_id BIGINT NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    children INTEGER NOT NULL,
    confirmation_number VARCHAR(100),
    hotel_id BIGINT NOT NULL,
    meal_plan_id BIGINT,
    nights INTEGER,
    rate_per_night NUMERIC(18,2),
    room_type_id BIGINT,
    rooms_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL CHECK ((status)::text = ANY (ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])),
    supplier_reference VARCHAR(100),
    total_amount NUMERIC(18,2) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE trv_hotel_bookings OWNER TO postgres;

CREATE TABLE trv_hotel_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_booking_id BIGINT NOT NULL,
    room_number VARCHAR(30),
    room_type_snapshot VARCHAR(150)
);
ALTER TABLE trv_hotel_rooms OWNER TO postgres;

CREATE TABLE trv_hotel_guests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_booking_id BIGINT NOT NULL,
    passenger_id BIGINT NOT NULL,
    room_id BIGINT
);
ALTER TABLE trv_hotel_guests OWNER TO postgres;

CREATE TABLE trv_hotel_cancellations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancellation_date DATE NOT NULL,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    hotel_booking_id BIGINT NOT NULL,
    penalty_amount NUMERIC(18,2) NOT NULL,
    reason VARCHAR(500),
    refund_amount NUMERIC(18,2) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK ((status)::text = ANY (ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'COMPLETED'::character varying]))
);
ALTER TABLE trv_hotel_cancellations OWNER TO postgres;

CREATE TABLE trv_air_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    airline_id BIGINT,
    arrival_date DATE,
    arrival_time TIME(0),
    booking_service_id BIGINT NOT NULL,
    cabin_class_id BIGINT,
    departure_date DATE,
    departure_time TIME(0),
    destination_airport_id BIGINT,
    fare_amount NUMERIC(18,2) NOT NULL,
    origin_airport_id BIGINT,
    pnr VARCHAR(20),
    status VARCHAR(20) NOT NULL CHECK ((status)::text = ANY (ARRAY['ISSUED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])),
    supplier_reference VARCHAR(100),
    tax_amount NUMERIC(18,2) NOT NULL,
    total_amount NUMERIC(18,2) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE trv_air_tickets OWNER TO postgres;

CREATE TABLE trv_passenger_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    air_ticket_id BIGINT NOT NULL,
    baggage_allowance VARCHAR(100),
    passenger_id BIGINT NOT NULL,
    seat_number VARCHAR(20),
    status VARCHAR(20) NOT NULL CHECK ((status)::text = ANY (ARRAY['ISSUED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])),
    ticket_number VARCHAR(50)
);
ALTER TABLE trv_passenger_tickets OWNER TO postgres;

-- -----------------------------------------------------------------------------
-- 6. Package & Tour Bookings (depends on trv_bookings via booking_service_id,
--                              trv_packages, trv_tours)
-- -----------------------------------------------------------------------------

CREATE TABLE trv_package_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    booking_service_id BIGINT NOT NULL,
    confirmation_number VARCHAR(100),
    package_id BIGINT NOT NULL,
    pax_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL CHECK ((status)::text = ANY (ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])),
    supplier_reference VARCHAR(100),
    total_amount NUMERIC(18,2) NOT NULL,
    travel_date DATE,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE trv_package_bookings OWNER TO postgres;

CREATE TABLE trv_tour_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    booking_service_id BIGINT NOT NULL,
    confirmation_number VARCHAR(100),
    guide_id BIGINT,
    pax_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL CHECK ((status)::text = ANY (ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])),
    total_amount NUMERIC(18,2) NOT NULL,
    tour_date DATE,
    tour_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE trv_tour_bookings OWNER TO postgres;

-- -----------------------------------------------------------------------------
-- 7. Visa Applications & Documents (depends on trv_visa_types, trv_passengers,
--                                    trv_bookings via booking_service_id)
-- -----------------------------------------------------------------------------

CREATE TABLE trv_visa_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    application_number VARCHAR(100),
    approval_date DATE,
    booking_service_id BIGINT NOT NULL,
    expected_date DATE,
    fee_amount NUMERIC(18,2) NOT NULL,
    passenger_id BIGINT NOT NULL,
    remarks VARCHAR(1000),
    status VARCHAR(20) NOT NULL CHECK ((status)::text = ANY (ARRAY['PENDING'::character varying, 'SUBMITTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'COLLECTED'::character varying])),
    submission_date DATE,
    visa_type_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE trv_visa_applications OWNER TO postgres;

CREATE TABLE trv_visa_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_name VARCHAR(150) NOT NULL,
    is_received BOOLEAN NOT NULL,
    remarks VARCHAR(300),
    visa_application_id BIGINT NOT NULL REFERENCES trv_visa_applications(id)
);
ALTER TABLE trv_visa_documents OWNER TO postgres;

-- -----------------------------------------------------------------------------
-- 8. Supplier Costs, Documents, Config (depends on org_organizations, various)
-- -----------------------------------------------------------------------------

CREATE TABLE trv_supplier_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    booking_service_id BIGINT NOT NULL,
    cost_amount NUMERIC(18,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    invoice_reference VARCHAR(100),
    payment_status VARCHAR(20) NOT NULL CHECK ((payment_status)::text = ANY (ARRAY['UNPAID'::character varying, 'PARTIAL'::character varying, 'PAID'::character varying])),
    supplier_id BIGINT,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE trv_supplier_costs OWNER TO postgres;

CREATE TABLE trv_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    content_type VARCHAR(150),
    document_type VARCHAR(30) NOT NULL CHECK ((document_type)::text = ANY (ARRAY['PASSPORT'::character varying, 'VISA'::character varying, 'TICKET'::character varying, 'PHOTO'::character varying, 'INVOICE'::character varying, 'CONFIRMATION'::character varying, 'RECEIPT'::character varying, 'OTHER'::character varying])),
    entity_id BIGINT NOT NULL,
    entity_type VARCHAR(30) NOT NULL CHECK ((entity_type)::text = ANY (ARRAY['BOOKING'::character varying, 'PASSENGER'::character varying, 'HOTEL_BOOKING'::character varying, 'AIR_TICKET'::character varying, 'VISA_APPLICATION'::character varying, 'PACKAGE_BOOKING'::character varying, 'TOUR_BOOKING'::character varying, 'SUPPLIER_COST'::character varying])),
    file_path VARCHAR(500) NOT NULL,
    file_size_bytes BIGINT,
    original_file_name VARCHAR(255) NOT NULL,
    remarks VARCHAR(500),
    stored_file_name VARCHAR(255) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id)
);
ALTER TABLE trv_documents OWNER TO postgres;

CREATE TABLE trv_gl_account_defaults (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    accounts_receivable_id BIGINT,
    cost_of_service_account_id BIGINT,
    supplier_payable_default_id BIGINT,
    travel_revenue_account_id BIGINT,
    organization_id BIGINT NOT NULL CONSTRAINT uq_trv_gldef_org UNIQUE REFERENCES org_organizations(id)
);
ALTER TABLE trv_gl_account_defaults OWNER TO postgres;

CREATE TABLE trv_document_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    created_by VARCHAR(100),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(100),
    auto_create BOOLEAN NOT NULL,
    credit_account_id BIGINT,
    debit_account_id BIGINT,
    erp_document_type VARCHAR(50),
    trv_document_type VARCHAR(50) NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES org_organizations(id),
    CONSTRAINT uq_trv_docmap UNIQUE (organization_id, trv_document_type)
);
ALTER TABLE trv_document_mapping OWNER TO postgres;

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE INDEX idx_trv_hotel_cat ON trv_hotels(category_id);
CREATE INDEX idx_trv_room_type_hotel ON trv_room_types(hotel_id);
CREATE INDEX idx_trv_room_facility_room ON trv_room_facilities(room_type_id);
CREATE INDEX idx_trv_pkg_inc_pkg ON trv_package_inclusions(package_id);
CREATE INDEX idx_trv_pkg_itinerary_pkg ON trv_package_itinerary_days(package_id);
CREATE INDEX idx_trv_pass_booking ON trv_passengers(booking_id);
CREATE INDEX idx_trv_booking_svc_booking ON trv_booking_services(booking_id);
CREATE INDEX idx_trv_hotel_booking_svc ON trv_hotel_bookings(booking_service_id);
CREATE INDEX idx_trv_hotel_rooms_hb ON trv_hotel_rooms(hotel_booking_id);
CREATE INDEX idx_trv_hotel_guests_hb ON trv_hotel_guests(hotel_booking_id);
CREATE INDEX idx_trv_air_ticket_svc ON trv_air_tickets(booking_service_id);
CREATE INDEX idx_trv_pass_ticket_air ON trv_passenger_tickets(air_ticket_id);
CREATE INDEX idx_trv_pkg_book_svc ON trv_package_bookings(booking_service_id);
CREATE INDEX idx_trv_tour_book_svc ON trv_tour_bookings(booking_service_id);
CREATE INDEX idx_trv_visa_app_svc ON trv_visa_applications(booking_service_id);
CREATE INDEX idx_trv_visa_doc_app ON trv_visa_documents(visa_application_id);
CREATE INDEX idx_trv_supp_cost_svc ON trv_supplier_costs(booking_service_id);
CREATE INDEX idx_trv_doc_entity ON trv_documents(entity_type, entity_id);
