package com.asg.spindleserp.global.documents;

public enum MovementType {
    PURCHASE_RECEIPT, PRODUCTION_RECEIPT, SALE_ISSUE, STORE_ISSUE,
    PRODUCTION_MATERIAL_ISSUE, TRANSFER_IN, TRANSFER_OUT,
    ADJUSTMENT_IN, ADJUSTMENT_OUT, CUSTOMER_RETURN, SUPPLIER_RETURN,
    ECOM_SALE_ISSUE, ECOM_RETURN_RECEIPT
}
