-- =============================================================================
--  sec_user_access_scopes — User access scope table
--  Run this ONCE before deploying UserAccessScope entity.
--  Idempotent via IF NOT EXISTS.
-- =============================================================================

CREATE TABLE IF NOT EXISTS sec_user_access_scopes
(
    id           bigint generated by default as identity primary key,
    user_id      bigint       not null
        constraint fk_uas_user
            references sec_users (id)
            on delete cascade,
    scope_type   varchar(30)  not null
        constraint sec_user_access_scopes_scope_type_check
            check (scope_type IN ('ORGANIZATION', 'BUSINESS_UNIT', 'COST_CENTER', 'WAREHOUSE')),
    reference_id bigint       not null,
    created_at   timestamp(6),
    constraint uq_uas_user_scope_ref
        unique (user_id, scope_type, reference_id)
);

CREATE INDEX IF NOT EXISTS idx_uas_user  ON sec_user_access_scopes (user_id);
CREATE INDEX IF NOT EXISTS idx_uas_scope ON sec_user_access_scopes (scope_type);
CREATE INDEX IF NOT EXISTS idx_uas_ref   ON sec_user_access_scopes (reference_id);
