package com.asg.spindleserp.approval;

/**
 * DocumentType enum — MUST remain complete.
 * Missing values cause ApprovalCallbackRegistry routing failure at runtime.
 */
public enum DocumentType {
    // Procurement
    STORE_REQUISITION, PURCHASE_REQUISITION, REQUEST_FOR_QUOTATION,
    COMPARATIVE_STATEMENT, PURCHASE_ORDER, GOODS_RECEIPT_NOTE,
    PURCHASE_INVOICE, DEBIT_NOTE,
    // Sales
    SALES_QUOTATION, SALES_ORDER, DELIVERY_ORDER,
    DELIVERY_CHALLAN, SALES_INVOICE, CREDIT_NOTE,
    // Production
    PRODUCTION_REQUISITION, PRODUCTION_MATERIAL_ISSUE, FINISHED_GOODS_RECEIVE,
    // Commercial
    EXPORT_PROFORMA_INVOICE, IMPORT_PROFORMA_INVOICE,
    LETTER_OF_CREDIT, COMMERCIAL_INVOICE,
    // Inventory
    MATERIAL_ISSUE, STOCK_TRANSFER, STOCK_ADJUSTMENT,
    // Finance
    JOURNAL_VOUCHER, PAYMENT_VOUCHER, RECEIPT_VOUCHER,
    // eCommerce
    ONLINE_ORDER, ONLINE_SHIPMENT, ONLINE_RETURN, ONLINE_INVOICE
}
