package com.asg.spindleserp.accounts.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * ChartOfAccountSubDTO — one DTO for all eleven sub-ledger partitions.
 *
 * <p>Which fields matter is decided by {@code SubAccountField}, not by this class.
 * Only the four fields every partition needs are validated here; per-type rules
 * live in the service, where the type is actually known.</p>
 *
 * <p>Two changes worth knowing about:</p>
 * <ul>
 *   <li><b>{@code subAccountCode} is no longer {@code @NotBlank}.</b> Leave it empty
 *       and the service generates one (CUS-0001, BNK-0007…). Typing a code by hand
 *       still works and still wins.</li>
 *   <li><b>MOBILE_BANKING, CARD and WALLET fields now exist here.</b> Their columns
 *       were in the table and their entities were registered, but nothing carried
 *       the values across the wire, so the whole payment-instrument half of the
 *       sub-ledger was write-only-nothing.</li>
 * </ul>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChartOfAccountSubDTO {

    private Long id;

    // ── Parent account (AJAX Select2 → /accounts/chart-of-accounts/search) ────
    @NotNull(message = "Main account is required")
    private Long mainAccountId;
    private String mainAccountDisplay;   // "{code} — {name}"

    // ── Core identity ─────────────────────────────────────────────────────────
    @NotBlank(message = "Sub-account type is required")
    private String subAccountType;
    /** Human label for the type, e.g. "Mobile Banking". Read-only, set by the service. */
    private String subAccountTypeLabel;

    /** Blank on create → auto-generated by the service. */
    @Size(max = 50)
    private String subAccountCode;

    @NotBlank(message = "Sub-account name is required")
    @Size(max = 200)
    private String subAccountName;

    @Builder.Default
    private Boolean active = true;

    // ── Common ────────────────────────────────────────────────────────────────
    @Size(max = 200)
    private String contactPerson;
    @Size(max = 20)
    private String contactPhone;
    @Size(max = 100)
    private String contactEmail;
    @Size(max = 500)
    private String address;
    @Size(max = 50)
    private String city;
    @Size(max = 50)
    private String state;
    @Size(max = 50)
    private String country;
    @Size(max = 20)
    private String postalCode;
    @Size(max = 50)
    private String taxId;
    @Size(max = 50)
    private String vatRegistrationNo;
    @Size(max = 20)
    private String currency;
    @Size(max = 1000)
    private String description;
    @Size(max = 1000)
    private String remarks;

    private BigDecimal openingBalance;
    /** Read-only — maintained by GL posting, never accepted from the client. */
    private BigDecimal currentBalance;

    // ── BANK ──────────────────────────────────────────────────────────────────
    private Long bankId;
    private String bankName;              // resolved display for the Select2
    @Size(max = 50)
    private String accountNumber;
    @Size(max = 200)
    private String accountTitle;
    @Size(max = 200)
    private String bankNameManual;
    @Size(max = 20)
    private String bankAccountType;
    @Size(max = 100)
    private String branchName;
    @Size(max = 10)
    private String branchCode;
    @Size(max = 200)
    private String branchAddress;
    @Size(max = 20)
    private String branchPhone;
    @Size(max = 9)
    private String routingNumber;
    @Size(max = 11)
    private String swiftCode;
    @Size(max = 34)
    private String ibanNumber;
    private BigDecimal interestRate;
    private BigDecimal overdraftLimit;
    private BigDecimal overdraftInterestRate;

    // ── CASH ──────────────────────────────────────────────────────────────────
    @Size(max = 20)
    private String cashAccountType;
    @Size(max = 100)
    private String location;
    @Size(max = 100)
    private String custodian;
    @Size(max = 100)
    private String custodianEmail;
    @Size(max = 20)
    private String custodianPhone;
    private BigDecimal maximumLimit;
    private BigDecimal minimumLimit;
    private BigDecimal approvalLimit;
    @Builder.Default
    private Boolean requiresApproval = false;

    // ── MOBILE_BANKING ────────────────────────────────────────────────────────
    @Size(max = 30)
    private String mfsProvider;
    @Size(max = 20)
    private String mfsAccountNumber;
    @Size(max = 20)
    private String mfsAccountType;
    @Size(max = 50)
    private String merchantNumber;
    @Size(max = 20)
    private String mfsShortCode;
    private BigDecimal mfsChargeRate;
    private BigDecimal dailyTransactionLimit;

    // ── CARD ──────────────────────────────────────────────────────────────────
    @Size(max = 30)
    private String cardNetwork;
    private Long cardAcquirerBankId;
    private String cardAcquirerBankName;   // resolved display
    @Size(max = 50)
    private String terminalId;
    @Size(max = 50)
    private String merchantId;
    @Size(max = 50)
    private String posSerialNumber;
    private Integer settlementDays;
    private BigDecimal mdrRate;

    // ── WALLET ────────────────────────────────────────────────────────────────
    @Size(max = 50)
    private String walletProvider;
    @Size(max = 100)
    private String walletIdentifier;
    @Size(max = 30)
    private String walletType;

    /** Bank sub-account a CARD / MFS / WALLET balance sweeps into. */
    private Long settlementAccountId;
    private String settlementAccountDisplay;

    // ── CUSTOMER ──────────────────────────────────────────────────────────────
    private BigDecimal creditLimit;
    @Size(max = 100)
    private String paymentTerms;
    private Integer creditDays;
    @Size(max = 100)
    private String salesRepresentative;
    @Size(max = 50)
    private String customerGroup;
    private Integer loyaltyPoints;
    @Builder.Default
    private Boolean isExportCustomer = false;

    // ── SUPPLIER ──────────────────────────────────────────────────────────────
    private Integer leadTimeDays;
    @Size(max = 3)
    private String preferredCurrency;
    private String certifications;
    @Builder.Default
    private Boolean isImportSupplier = false;

    // ── LC ────────────────────────────────────────────────────────────────────
    @Size(max = 100)
    private String lcNumber;
    @Size(max = 100)
    private String manualLcNumber;
    @Size(max = 30)
    private String lcType;
    @Size(max = 30)
    private String lcStatus;
    @Size(max = 20)
    private String transactionCurrency;
    private BigDecimal lcAmount;
    private BigDecimal exchangeRate;
    private LocalDate issueDate;
    private LocalDate expiryDate;
    private LocalDate shipmentDate;
    private LocalDate receivingDate;
    private Integer tenureDays;
    @Size(max = 100)
    private String masterLcNo;
    @Size(max = 100)
    private String btbLcNo;
    private LocalDate masterLcDate;
    @Size(max = 30)
    private String paymentTerm;
    @Size(max = 20)
    private String shipmentMode;
    private Boolean partialShipmentAllowed;
    private Boolean btmaCertificateRequired;
    private String termsCondition;

    // ── Legacy mirrors ────────────────────────────────────────────────────────
    // These columns duplicate subAccountCode and predate it. They are still
    // written (older reports read them) but are never rendered and never accepted
    // from the client — see ChartOfAccountSubServiceImpl.mirrorLegacyCodes().
    private String bankAccountCode;
    private String cashAccountCode;
    private String customerCode;
    private String supplierCode;

    // ── Audit ─────────────────────────────────────────────────────────────────
    private String createdAt;
    private String updatedAt;
    private String createdBy;
    private String updatedBy;
}
